openshift/cincinnati-graph-data

- blocked-edges/4.3.0-rc.0.yaml
- channels/candidate-4.3.yaml
New channel for the new 4.3.z-stream.
> channels/candidate-4.3: Promote 4.3.0-rc.0-x86_64

- OWNERS_ALIASES
> Adding LalatenduMohanty as cincinnati-graph-data-approvers

- blocked-edges/4.3.0.yaml
https://bugzilla.redhat.com/show_bug.cgi?id=1793635
> Blocking all the edges to 4.3.0 because of bz 1793635

- blocked-edges/4.3.0-rc.3.yaml
> Blocking edges to candidate 4.3.0-rc.3

- channels/fast-4.3.yaml
We have already blocked the edges to this because of https://bugzilla.redhat.com/show_bug.cgi?id=1793635
> Adding 4.3.0 GA bits to fast channel

- channels/stable-4.3.yaml
We have already blocked the edges to this because of https://bugzilla.redhat.com/show_bug.cgi?id=1793635
> Adding 4.3.0 GA bits to stable channel

- hack/graph-util.py
We have introduced architectures into channels by mistake because the logs
talk about the 'release' but don't make it obvious that release might be for
multiple archs. This prints the versions similar to how they would have to be
listed in the config files if you wanted arch specificity.
> Print the architecture in log messages

- channels/fast-4.2.yaml
Split of https://github.com/openshift/cincinnati-graph-data/pull/67
> channels/fast-4.2: Promote 4.2.20

- channels/fast-4.3.yaml
Split of https://github.com/openshift/cincinnati-graph-data/pull/67
> channels/fast-4.3: Promote 4.2.20+amd64

- channels/fast-4.3.yaml
- channels/stable-4.3.yaml
> Adding information why 4.3.2 and 4.3.3 is not in fast,stable 4.3

- channels/candidate-4.2.yaml
> Adding 4.1.37 to candidate-4.2

- channels/candidate-4.3.yaml
- channels/fast-4.3.yaml
- channels/stable-4.3.yaml
> Adding information about 4.3.4

- channels/fast-4.3.yaml
> Adding 4.3.5 to fast-4.3 channel

- channels/stable-4.3.yaml
> Adding 4.3.5 to stable-4.3 channel

- channels/candidate-4.4.yaml
```console
$ oc adm release info quay.io/openshift-release-dev/ocp-release:4.4.0-rc.0-x86_64 | grep Upgrades
Upgrades: 4.3.5
```
> channels/candidate-4.4: Add 4.4.0-rc.0 and its update source 4.3.5

- hack/graph-util.py
I was regularly running the script grepping out the DEBUG lines
to make seeing the changes easy. Just make it a command line arg
> Add logging verbosity

- channels/stable-4.2.yaml
It was promoted the feeder fast-4.2 by 78a82d3016 (#120, 2020-03-24).
> channels/stable-4.2: Promote 4.1.38 to stable-4.2

- hack/errata.py
And push to Slack's Incoming WebHook.
> hack/errata: Poll for recent errata events

- OWNERS_ALIASES
This drops myself from approvers list, as I don't really have any
part in the approval flow here.
> OWNERS: remove lucab from approvers

- OWNERS_ALIASES
Blocked edges are the only changes that require release-admin approval.
> Add all OTA members as approvers

- blocked-edges/4.3.11.yaml
- channels/fast-4.3.yaml
- channels/stable-4.3.yaml
> Blocking edges to 4.3.11

- channels/fast-4.2.yaml
- channels/prerelease-4.1.yaml
- channels/stable-4.1.yaml
- channels/stable-4.2.yaml
> Adding information on 4.1.39 and 4.1.40

- channels/candidate-4.4.yaml
- channels/fast-4.3.yaml
- channels/fast-4.4.yaml
- channels/stable-4.3.yaml
- channels/stable-4.4.yaml
> Adding info on 4.3.14

- channels/candidate-4.3.yaml
- channels/candidate-4.4.yaml
- channels/fast-4.3.yaml
- channels/fast-4.4.yaml
- channels/stable-4.3.yaml
- channels/stable-4.4.yaml
> Adding information on 4.3.15, 4.3.16 and 4.3.17

- blocked-edges/4.4.3.yaml
- blocked-edges/4.4.4.yaml
- blocked-edges/4.4.5.yaml
- blocked-edges/4.4.6.yaml
> blocked-edges/4.4.*: Fix 1827335 -> 1827337 typo for 4.3 bugs

- blocked-edges/4.5.1.yaml
> Blocking edges to 4.5.1

- blocked-edges/4.5.1.yaml
- blocked-edges/4.5.2.yaml
> Blocking edges from 4.4.* to 4.5.2

- blocked-edges/4.5.3.yaml
Merge after #350 and #351 
/hold
/assign @vrutkovs
> Block: 4.5.3 on multiple known quality and upgrade impacting bugs

- hack/errata.py
This change would add a comment with the LGTM to the PR promoting to
fast after errata has changed status to SHIPPED_LIVE. After datagrepper
gets notified that errata state has changed, it would parse PRs
targetting fast (expects default title), extract errata number and
compare to the received message. If errata numbers match the script
would comment with `/lgtm`.
This requires the hook to be deployed with GITHUB_TOKEN set, which
would be taken care of in internal autoreport repo.
/cc @LalatenduMohanty @wking
> errata.py: autoLGTM the fast PR after errata has shipped

- hack/errata.py
Errata-hook deployment on datahub is crashing and not notifying us correctly. This ensures exception is trapped, more debug messages added, and PRs which already have lgtm label are skipped.
> hack/errata.py: trap exceptions in lgtm_fast_pr_for_errata

- blocked-edges/4.6.0.yaml
> Block edges to 4.6.0

- blocked-edges/4.5.14-15-to-4.6.1.yaml
> Require 4.5.16 or later to upgrade to 4.6

- hack/errata.py
We won't be able to find a matching PR for this, because the PR will talk about 4.6.1, and the errata just has `4.6 GA`, but 4.6.1 is our general-availability release:
```console
$ curl -sH 'Accept:application/json' 'https://api.openshift.com/api/upgrades_info/v1/graph?channel=stable-4.6' | jq -r '.nodes[] | .version + " " + .metadata.url'
4.6.1 https://access.redhat.com/errata/RHBA-2020:4196
```
and the synopsis for that errata is `OpenShift Container Platform 4.6 GA Images`.
/assign @vrutkovs
> hack/errata: Match 'OpenShift Container Platform 4.6 GA Images' synopsis

- blocked-edges/4.6.9.yaml
> Block upgrades to 4.6.9

- build-suggestions/4.7.yaml
This will likely be updated again before GA, at least z_min.
> build-suggestions: Update 4.7

- OWNERS_ALIASES
Stefan has moved on to other things :(.
> OWNERS_ALIASES: Drop steveeJ

- blocked-edges/4.6.22.yaml
- blocked-edges/4.6.23.yaml
Impact statement [here][1].
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1944679#c10
> blocked-edges/4.6.2[23]: Block all incoming edge on OVN

- graph-data.rs/Cargo.lock
- graph-data.rs/Cargo.toml
> graph-data.rs: update Cincinnati config

- build-suggestions/4.8.yaml
> Adding build suggestion for 4.8

- channels/candidate-4.7.yaml
- channels/candidate-4.8.yaml
[rhbz#1958420](https://bugzilla.redhat.com/show_bug.cgi?id=1958420).
> channels/candidate-4.[78]: Tombstone 4.7.10 on serviceEndpoints segfaults

- channels/candidate-4.7.yaml
- channels/candidate-4.8.yaml
> Tombstone 4.7.15 in candidate 4.7 and 4.8 channels

- graph-data.rs/Cargo.lock
- graph-data.rs/Cargo.toml
Update cincinnati dep to latest as of Jun 17
> graph-data.rs: bump to latest Cincinnati

- blocked-edges/4.7.5.yaml
- blocked-edges/4.7.6.yaml
- blocked-edges/4.7.7.yaml
- blocked-edges/4.7.8.yaml
- blocked-edges/4.7.9.yaml
> Blocking the edges from 4.7.5 to 4.7.9

- hack/stabilization-changes.py
In single-shot mode, assume the caller has the local directory where they want it to be.  For poll-mode, do that for the first round, although there's a chance we've gone a bit stale since the image was built (in which case we might fail while trying to recreate an existing upstream branch, but no big deal).  But after waking up from the poll-sleep for the next attempt, fetch and checkout the upstream tip, to ensure we stay up to date.  At least with the graph-data; we won't be picking up new Python code this way.
I'd somewhat prefer to [trigger our BuildConfig with a GitHub webhook][1] to get this same effect (rebuilding based on the upstream tip, and then bumping the deployment to run that new build).  That would get new Python picked up too.  But we can't do that conveniently today, …
> hack/stabilization-changes: Automatically follow upstream before new poll rounds

- hack/stabilization-changes.py
Avoid:
```
Branch promote-4.6.39-to-stable-4.6 set up to track remote branch master from origin.
[promote-4.6.39-to-stable-4.6 71a3666] channels/stable-4.6: Promote 4.6.39
1 file changed, 1 insertion(+)
fatal: could not read Username for 'https://github.com': No such device or address
ERROR:   failed to promote 4.6.39 to stable-4.6: Command '['git', 'push', '-u', 'origin', 'promote-4.6.39-to-stable-4.6']' returned non-zero exit status 128.
```
I think that's Git saying "I need to authenticate this push.  Let me ask for credentials using the TTY.  What!?  No TTY in this container!  Aaaah!".
I spent a while looking at [`git-credentials(7)`][1], which sounded promising, but while there is clear discussion on how to set up the cache helper and such, and how to insert creds into the cache via …
> hack/stabilization-changes: Use the configured token to push

- blocked-edges/4.8.2.yaml
- blocked-edges/4.8.3.yaml
- blocked-edges/4.8.4.yaml
Blocking 4.7.z to 4.8.{2-4} edges due to BZ1988576.
> Block edges from 4.7.z to 4.8.{2-4}

- graph-data.rs/Cargo.lock
- graph-data.rs/Cargo.toml
- graph-data.rs/Dockerfile
- graph-data.rs/src/check_channels.rs
- graph-data.rs/src/check_releases.rs
This adds several unit tests for `graph-data.rs`
> OTA-342: Add unit tests for graph-data.rs

- blocked-edges/4.7.24.yaml
- blocked-edges/4.7.28.yaml
- blocked-edges/4.8.2.yaml
- blocked-edges/4.8.3.yaml
- blocked-edges/4.8.4.yaml
- blocked-edges/4.8.5.yaml
- blocked-edges/4.8.9.yaml
> Updating the impacted blocked edges because of BZ 1999591

- blocked-edges/4.7.10.yaml
- blocked-edges/4.7.14.yaml
- blocked-edges/4.7.15.yaml
- blocked-edges/4.7.20.yaml
Copying over the messages we used when tombstoning them.
> blocked-edges/4.7: Adjust comments for 4.7.10, 14, 15, and 20

- build-suggestions/4.8.yaml
- build-suggestions/4.9.yaml
See individual commits for per release justification
> Raise minimums

- graph-data.rs/Cargo.lock
- graph-data.rs/Cargo.toml
* Update to latest Cincinnati from master
* Unpin actix-http/actix-service
* Bump tokio
> graph-data.rs: bump dependencies

- graph-data.rs/src/check_channels.rs
- graph-data.rs/src/check_releases.rs
- graph-data.rs/src/check_signatures.rs
Fix errors found by `cargo clippy --all-targets --all-features` to make code more ideomatic
> graph-data.rs: fix issues found by rust-clippy

- hack/generate-weekly-report.py
- hack/show-edges.py
- hack/stabilization-changes.py
- hack/util.py
- hack/validate-blocked-edges.py
Run like:
```console
$ hack/generate-weekly-report.py --stats https://ota-reports.example.com/.../stats.html ac07fe96e8bf19551102c2a651731415e836ac72
```
Paste into the code-edit view of the internal blog, edit/extend as needed, and publish!
Also factors some shared code out into `util.py`, as described in 59d8ff6da0fe53.
> hack/generate-weekly-report: Automate some busywork

- internal-channels/candidate.yaml
On [access to public images][1].
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=2060605
> internal-channels/candidate: Tombstone 4.10.0

- hack/release-ga.sh
Make it harder to forget something.  I've left of the final:
```console
$ git add channels/*
$ git commit
```
but we could do that in the future if we wanted to control the commit message.
> hack/release-ga: Automate GA steps

- hack/show-edges.py
With this change:
```console
$ hack/show-edges.py stable-4.7 | grep '> 4[.]7[.][49]'
4.6.15 -(blocked: AuthOAuthProxyLeakedConnections, VSphereHW14CrossNodeNetworkingError, VSphereNodeNameChanges)-> 4.7.4
4.6.16 -(blocked: AuthOAuthProxyLeakedConnections, VSphereHW14CrossNodeNetworkingError, VSphereNodeNameChanges)-> 4.7.4
...
4.6.23 -(blocked: AuthOAuthProxyLeakedConnections, VSphereHW14CrossNodeNetworkingError, VSphereNodeNameChanges)-> 4.7.4
4.6.25 -(blocked: None)-> 4.7.9
4.6.26 -(blocked: None)-> 4.7.9
4.6.27 -(blocked: None)-> 4.7.9
4.7.0 -(blocked: VSphereNodeNameChanges)-> 4.7.4
4.7.0 -> 4.7.9
...
```
This makes it easier to remember why a particular edge is risky.
> hack/show-edges: Include blocked reasons, when we have them

- blocked-edges/4.9.0.yaml
- blocked-edges/4.9.10.yaml
- blocked-edges/4.9.11.yaml
- blocked-edges/4.9.12.yaml
- blocked-edges/4.9.13.yaml
- blocked-edges/4.9.15.yaml
- blocked-edges/4.9.17.yaml
- blocked-edges/4.9.18.yaml
- blocked-edges/4.9.19.yaml
- blocked-edges/4.9.21.yaml
- blocked-edges/4.9.22.yaml
- blocked-edges/4.9.23.yaml
- blocked-edges/4.9.24.yaml
- blocked-edges/4.9.25.yaml
- blocked-edges/4.9.26.yaml
- blocked-edges/4.9.4.yaml
- blocked-edges/4.9.5.yaml
- blocked-edges/4.9.6.yaml
- blocked-edges/4.9.7.yaml
- blocked-edges/4.9.8.yaml
- blocked-edges/4.9.9.yaml
> Blocking all update edges from ocp 4.8 to 4.9

- hack/stabilization-changes.py
So we'll get:
```
* FAILED channels/stable-4.10: Promote 4.10.6. It was promoted to the feeder stable by 28cfb674bc (Merge pull request #1709 from openshift/promote-4.10.6-to-stable, 2022-04-04) 0:54:46.091883 ago. Command '['git', 'push', '-u', 'https://REDACTED@github.com/openshift/cincinnati-graph-data.git', 'promote-4.10.6-to-stable-4.10']' returned non-zero exit status 1.
```
and similar, instead of writing the secret token to container logs and Slack.
> hack/stabilization-changes: Redact GitHub tokens from logged messages

- hack/stabilization-changes.py
The bot no longer has powers to label pull requests in the OpenShift repository, and with openshift/release#27826 teaching Prow to trust the bot, we don't need that anymore anyway.  Add a new command-line option for folks who do want labels set (developers covering for a bot outage, etc.).
> hack/stabilization-changes: Move labeling to optional --labels

- blocked-edges/4.11.0-fc.0-cluster-verison-precondition-check.yaml
Validate it with the `show-edges.py` script i.e. `hack/show-edges.py candidate-4.11`
> Adding conditional risk ClusterVersionPreconditionCheck for 4.11.0-fc.0

- blocked-edges/4.9.38.yaml
- blocked-edges/4.9.39.yaml
> Blocking all edges to 4.9.38 and 4.9.39

- blocked-edges/4.11.0-fc.0-rpm-ostree-timeout.yaml
- blocked-edges/4.11.0-fc.3-rpm-ostree-timeout.yaml
- blocked-edges/4.11.0-rc.0-rpm-ostree-timeout.yaml
- blocked-edges/4.11.0-rc.1-rpm-ostree-timeout.yaml
- blocked-edges/4.11.0-rc.2-rpm-ostree-timeout.yaml
- blocked-edges/4.11.0-rc.3-rpm-ostree-timeout.yaml
- blocked-edges/4.11.0-rc.4-rpm-ostree-timeout.yaml
- blocked-edges/4.11.0-rc.5-rpm-ostree-timeout.yaml
- blocked-edges/4.11.0-rc.6-rpm-ostree-timeout.yaml
- blocked-edges/4.11.0-rc.7-rpm-ostree-timeout.yaml
- blocked-edges/4.11.0-rpm-ostree-timeout.yaml
> Adding Conditional update edge from 4.10 to 4.11 because of BZ:2111817

- blocked-edges/4.11.1-rpm-ostree-timeout.yaml
> blocked-edges/4.11.1: Conditional block from 4.10

- hack/show-edges.py
For output like:
```console
$ hack/show-edges.py --revision 3511fa8 --list-unable-to-reach-target-minor-version stable-4.8 | tail -n3
4.8.9 -> 4.8.45
4.8.9 -> 4.8.46
No unconditional paths from 4.7.54 to 4.8
```
To make it easier to understand historical exposure to the issue that 674e8299c0 (#2059) was trying to fix.
> hack/show-edges: Add --list-unable-to-reach-target-minor-version

- OWNERS_ALIASES
@vrutkovs is focusing on assisted-installer stuff now.
> OWNERS: Prune vrutkovs

- blocked-edges/4.10.38-node-creation-fails.yaml
> Adding conditional risk for 4.10.38

- internal-channels/candidate.yaml
> Tombstone 4.11.19

- hack/show-edges.py
To make it easier to subset the graph when looking at something recent, without all the noise of older releases.  For example:
```console
$ hack/show-edges.py --root-version 4.10.42 stable-4.11
4.10.42 -> 4.10.43
4.10.42 -> 4.10.45
4.10.42 -(blocked: ARM64SecCompError524)-> 4.11.17
4.10.42 -(blocked: ARM64SecCompError524)-> 4.11.18
4.10.42 -(blocked: ARM64SecCompError524)-> 4.11.20
4.10.43 -> 4.10.45
4.10.43 -(blocked: ARM64SecCompError524)-> 4.11.17
4.10.43 -(blocked: ARM64SecCompError524)-> 4.11.18
4.10.43 -(blocked: ARM64SecCompError524)-> 4.11.20
4.10.45 -(blocked: ARM64SecCompError524)-> 4.11.20
4.11.17 -> 4.11.18
4.11.17 -> 4.11.20
4.11.18 -> 4.11.20
```
We may want to pair this with `--leaf-version` or some such if we wanted to to rule out some newer releases, but I'm leaving that …
> hack/show-edges: Add --root-version

- hack/show-edges.py
I'd originally written show-edges in 0d323fd766 (#1043) to make it easier to look at historical and in-flight-pull-request renderings of graph-data, without having to involve the complication of feeding the graph-data into Cincinnati to get Cincinnati graphs.  However, graph-data only includes some of the metadata required to build a graph, so the script had been walking tags in an image registry repository to get more data about each release, mostly the baked-in update-source metadata like:
```console
$ oc adm release info -o json quay.io/openshift-release-dev/ocp-release:4.13.0-ec.1-multi | jq -c .metadata.previous
["4.12.0-rc.0","4.12.0-rc.1","4.12.0-rc.2","4.12.0-rc.3"]
```
But walking all of those tags down into manifests and layers to find that data is slow, and some folks may want …
> hack/show-edges: Add --cincinnati option

- OWNERS_ALIASES
> Removing Jack from owners file

- blocked-edges/4.11.26-arm64-seccomp-error-524.yaml
Fixed via https://issues.redhat.com/browse/OCPBUGS-7033
> Add fixedIn 4.11.27 for ARM64SecCompError524

- blocked-edges/4.12.3-leaked-machineconfig.yaml
- blocked-edges/4.12.4-leaked-machineconfig.yaml
- blocked-edges/4.12.5-leaked-machineconfig.yaml
- blocked-edges/4.12.6-leaked-machineconfig.yaml
- blocked-edges/4.12.7-leaked-machineconfig.yaml
Following up on 472ed90abc (#3243).
> blocked-edges/4.12.*-leaked-machineconfig: Adjust 'to' for target patch

- hack/validate-blocked-edges.py
Prevent gotchas like the one in https://github.com/openshift/cincinnati-graph-data/pull/3243 that needed to be fixed in https://github.com/openshift/cincinnati-graph-data/pull/3249:
When run on https://github.com/openshift/cincinnati-graph-data/pull/3243, this results in the following validation failure:
```console
$ ./hack/validate-blocked-edges.py
Traceback (most recent call last):
File "/home/pmuller/Projects/RH/cincinnati-graph-data/./hack/validate-blocked-edges.py", line 79, in <module>
validate_blocked_edges(directory='blocked-edges')
File "/home/pmuller/Projects/RH/cincinnati-graph-data/./hack/validate-blocked-edges.py", line 13, in validate_blocked_edges
raise ValueError('invalid blocked edge {}: {}'.format(path, error)) from None
ValueError: invalid blocked edge …
```
> validate-blocked-edges: match target version in content and filename

- build-suggestions/4.13.yaml
https://issues.redhat.com/browse/OCPBUGS-9977
https://issues.redhat.com/browse/OCPBUGS-10318
> Bump minimum for 4.13 upgrades to 4.12.9 for multiple bugs

- blocked-edges/4.11.36-PatchesOlderRelease.yaml
- blocked-edges/4.12.12-PatchesOlderRelease.yaml
> Add fixedIn for PatchesOlderRelease

- hack/stabilization-changes.py
When checking for concerns about risk extensions, take into account also versions that are still candidates for the same channel. It is possible that the (earlier) version that carries the information about the fix (`fixedIn`) is also still just a candidate to the channel, and in that case we would previously log a spurious error message.
For the case where 4.11.40 file contained `fixedIn: 4.11.41` and both versions were still just candidates for stable:
https://github.com/openshift/cincinnati-graph-data/blob/e7567e45e4e1c4857f34f0cf22f341536c1e55af/blocked-edges/4.11.40-KeepalivedMulticastSkew.yaml#L3
Before:
```
* Recommend waiting to promote 4.11.40 to stable; it was promoted the feeder fast by ebf3b7c6fa (Merge pull request #3623 from openshift-ota-bot/promote-4.11.40-to-fast, …
```
> Do not warn about risks fixed in earlier candidate to the same channel

- hack/show-edges.py
We are declaring risks.  Users are free to evaluate those risks and update or not, as they see fit.
> hack/show-edges: Replace "blocked:" with "risks:"

- blocked-edges/4.12.18-MultiNetworkAttachmentsWhereaboutsVersion.yaml
- blocked-edges/4.12.19-MultiNetworkAttachmentsWhereaboutsVersion.yaml
- blocked-edges/4.12.20-MultiNetworkAttachmentsWhereaboutsVersion.yaml
- blocked-edges/4.12.21-MultiNetworkAttachmentsWhereaboutsVersion.yaml
- blocked-edges/4.12.22-MultiNetworkAttachmentsWhereaboutsVersion.yaml
- blocked-edges/4.12.23-MultiNetworkAttachmentsWhereaboutsVersion.yaml
- blocked-edges/4.12.24-MultiNetworkAttachmentsWhereaboutsVersion.yaml
- blocked-edges/4.12.25-MultiNetworkAttachmentsWhereaboutsVersion.yaml
- blocked-edges/4.13.0-MultiNetworkAttachmentsWhereaboutsVersion.yaml
- blocked-edges/4.13.0-ec.1-MultiNetworkAttachmentsWhereaboutsVersion.yaml
- blocked-edges/4.13.0-ec.2-MultiNetworkAttachmentsWhereaboutsVersion.yaml
- blocked-edges/4.13.0-ec.3-MultiNetworkAttachmentsWhereaboutsVersion.yaml
- blocked-edges/4.13.0-ec.4-MultiNetworkAttachmentsWhereaboutsVersion.yaml
- blocked-edges/4.13.0-rc.0-MultiNetworkAttachmentsWhereaboutsVersion.yaml
- blocked-edges/4.13.0-rc.2-MultiNetworkAttachmentsWhereaboutsVersion.yaml
- blocked-edges/4.13.0-rc.3-MultiNetworkAttachmentsWhereaboutsVersion.yaml
- blocked-edges/4.13.0-rc.4-MultiNetworkAttachmentsWhereaboutsVersion.yaml
- blocked-edges/4.13.0-rc.5-MultiNetworkAttachmentsWhereaboutsVersion.yaml
- blocked-edges/4.13.0-rc.6-MultiNetworkAttachmentsWhereaboutsVersion.yaml
- blocked-edges/4.13.0-rc.7-MultiNetworkAttachmentsWhereaboutsVersion.yaml
- blocked-edges/4.13.0-rc.8-MultiNetworkAttachmentsWhereaboutsVersion.yaml
- blocked-edges/4.13.1-MultiNetworkAttachmentsWhereaboutsVersion.yaml
- blocked-edges/4.13.2-MultiNetworkAttachmentsWhereaboutsVersion.yaml
- blocked-edges/4.13.3-MultiNetworkAttachmentsWhereaboutsVersion.yaml
- blocked-edges/4.13.4-MultiNetworkAttachmentsWhereaboutsVersion.yaml
```console
$ sed -i 's|https://issues.redhat.com/browse/SDN-4019|https://access.redhat.com/solutions/7024726|g' $(git grep -l https://issues.redhat.com/browse/SDN-4019)
```
> blocked-edges/4.12.18-MultiNetworkAttachmentsWhereaboutsVersion: Link KCS

- blocked-edges/4.13.0-RHSB2023001.yaml
- blocked-edges/4.13.1-RHSB2023001.yaml
- blocked-edges/4.13.2-RHSB2023001.yaml
- blocked-edges/4.13.3-RHSB2023001.yaml
- blocked-edges/4.13.4-RHSB2023001.yaml
- blocked-edges/4.13.5-RHSB2023001.yaml
- blocked-edges/4.13.6-RHSB2023001.yaml
Created the 4.13.0 file manually, then copied the rest via
```console
$ for x in (seq 1 6)
cp 4.13.0-RHSB2023001.yaml 4.13.$x-RHSB2023001.yaml
sed -i "s|4.13.0|4.13.$x|" 4.13.$x-RHSB2023001.yaml 
end
```
> OTA-1000: RHSB2023-001: Add for 4.12.23+ -> 4.13 edges

- hack/release-stable-minor.sh
- Use the iteration with git to execute stabilization-changes.py until
it stops making changes.
- Improve logging: mention EUSness, hide stabilization-changes.py
log unless it fails, and log just individual iterations
Example output from 30a5c082abf96e2751c337f474d8f901c2a62640
```console
$ git co 30a5c082abf96e2751c337f474d8f901c2a62640
$ git co improve-release-scripts hack/release-stable-minor.sh
$ git commit -a -m "This needs to be clean git state"
$ ./hack/release-stable-minor.sh 4.13
4.13 is not an EUS release, will not create an EUS channel
Running stabilization-changes.py: iteration 1
Running stabilization-changes.py: iteration 2
Running stabilization-changes.py: iteration 3
Running stabilization-changes.py: iteration 4
See /tmp/tmp.D5bo4N466Z for stabilization-changes.py output if …
```
> release-stable-minor.sh: QoL improvements

- build-suggestions/4.15.yaml
- channels/candidate-4.15.yaml
As these are required for 4.15 development
> Adding the build suggestion and candidate channel yaml file

- blocked-edges/4.14.0-rc.3-OVNWebhookUserConflict.yaml
- blocked-edges/4.14.0-rc.4-OVNWebhookUserConflict.yaml
- blocked-edges/4.15.0-ec.0-OVNWebhookUserConflict.yaml
Which I'd missed with a sloppy copy/paste in 54c73a994103 (#4203).
> blocked-edges/*-OVNWebhookUserConflict: Fix the name

- blocked-edges/4.13.27-OVNKubeMasterDSPrestop.yaml
As OCPBUGS-22293 is not fixed yet
> Extending the risk for 4.13.27

- blocked-edges/4.15.0-rc.8-GCPMintModeRoleAdmin.yaml
https://github.com/openshift/cincinnati-graph-data/pull/4827
> GCPMintModeRoleAdmin fixed in 4.15.0

- hack/stabilization-changes.py
Conditional risks on minor version updates (4.y to 4.(y+1)) are not great, because they make it more complicated to update and pick up new features.  But conditional risks on patch version updates (4.y.z to 4.y.z') are worse, because they make it more more complicated to pick up bug fixes.  Make it easier to keep track of those by messaging about them in daily bot reports.
> hack/stabilization-changes: Log about patch connection

- build-suggestions/4.18.yaml
- channels/candidate-4.18.yaml
Like 3eb8e55eb2 (#2758) and 1e37be475b (#5361), and similar, but for 4.18.  Generated with:
```console
$ hack/release-open.sh 4.18
$ git add build-suggestions/4.18.yaml channels/*4.18.yaml
```
> *: Prepare for 4.18 development

- blocked-edges/4.15.39-OVNIPsecConnectivity.yaml
The respective bug [1] is in the state Assigned.
[1] https://issues.redhat.com/browse/OCPBUGS-41823
> blocked-edges/4.15.39-OVNIPsecConnectivity: Extend the risk

- blocked-edges/4.18.8-OVNWithMultipleClusterNetworks.yaml
Based on OCPBUGS-54671 being ON_QA
Ref: https://issues.redhat.com/browse/OCPBUGS-54671 https://issues.redhat.com/browse/CORENET-5832
> OVNWithMultipleClusterNetworks fixedIn 4.18.9

- hack/validate-blocked-edges.py
It has been used in other places already:
```console
$ rg 'env python'
hack/show-edges.py
1:#!/usr/bin/env python3
hack/generate-weekly-report.py
1:#!/usr/bin/env python3
hack/stabilization-changes.py
1:#!/usr/bin/env python3
```
> Use python3 shebang

- hack/release-ga.sh
Follow up https://github.com/openshift/cincinnati-graph-data/pull/7455#discussion_r2152920396
> Make hack/release-ga.sh mac-friendly

- blocked-edges/4.19.0-OldBootImagesComposeFSvsGrubProbe.yaml
Follow up https://issues.redhat.com/browse/OCPBUGS-52485?focusedId=27450051&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-27450051
> COS-3357: Rename the issue to OldBootImagesComposeFSvsGrubProbe

- blocked-edges/4.11.0-fc.0-stale-selinux-policies.yaml
- blocked-edges/4.11.0-fc.3-stale-selinux-policies.yaml
- blocked-edges/4.11.0-rc.0-stale-selinux-policies.yaml
- blocked-edges/4.11.0-rc.1-stale-selinux-policies.yaml
- blocked-edges/4.11.0-rc.2-stale-selinux-policies.yaml
- blocked-edges/4.11.0-rc.3-stale-selinux-policies.yaml
- blocked-edges/4.11.0-rc.4-stale-selinux-policies.yaml
- blocked-edges/4.11.0-rc.5-stale-selinux-policies.yaml
- blocked-edges/4.11.0-rc.6-stale-selinux-policies.yaml
- blocked-edges/4.11.0-rc.7-stale-selinux-policies.yaml
- blocked-edges/4.11.0-stale-selinux-policies.yaml
- blocked-edges/4.11.1-stale-selinux-policies.yaml
- blocked-edges/4.11.2-stale-selinux-policies.yaml
- blocked-edges/4.11.3-stale-selinux-policies.yaml
> StaleSELinuxPolicies: unify the message

- blocked-edges/4.11.6-ovn-namespace.yaml
- blocked-edges/4.11.7-ovn-namespace.yaml
- blocked-edges/4.11.8-ovn-namespace.yaml
- blocked-edges/4.11.9-ovn-namespace.yaml
> OVNNetworkPolicyLongName: unify the message

- blocked-edges/4.11.0-fc.0-stale-insights-run-level-label.yaml
- blocked-edges/4.11.0-fc.3-stale-insights-run-level-label.yaml
- blocked-edges/4.11.0-rc.0-stale-insights-run-level-label.yaml
- blocked-edges/4.11.0-rc.1-stale-insights-run-level-label.yaml
- blocked-edges/4.11.0-rc.2-stale-insights-run-level-label.yaml
- blocked-edges/4.11.0-rc.3-stale-insights-run-level-label.yaml
- blocked-edges/4.11.0-rc.4-stale-insights-run-level-label.yaml
- blocked-edges/4.11.0-rc.5-stale-insights-run-level-label.yaml
- blocked-edges/4.11.0-rc.6-stale-insights-run-level-label.yaml
- blocked-edges/4.11.0-rc.7-stale-insights-run-level-label.yaml
- blocked-edges/4.11.0-stale-insights-run-level-label.yaml
- blocked-edges/4.11.1-stale-insights-run-level-label.yaml
- blocked-edges/4.11.2-stale-insights-run-level-label.yaml
- blocked-edges/4.11.3-stale-insights-run-level-label.yaml
- blocked-edges/4.11.4-stale-insights-run-level-label.yaml
> StaleInsightsRunLevelLabel: unify the message

- blocked-edges/4.10.14-release-data-with-hyphen-prefix.yaml
- blocked-edges/4.10.15-release-data-with-hyphen-prefix.yaml
- blocked-edges/4.10.16-release-data-with-hyphen-prefix.yaml
- blocked-edges/4.10.17-release-data-with-hyphen-prefix.yaml
- blocked-edges/4.10.18-release-data-with-hyphen-prefix.yaml
> ReleaseDataWithHyphenPrefix: unify the message

- blocked-edges/4.18.0-rc.0-MachineConfigServerCARotation.yaml
- blocked-edges/4.18.0-rc.1-MachineConfigServerCARotation.yaml
- blocked-edges/4.18.0-rc.10-MachineConfigServerCARotation.yaml
- blocked-edges/4.18.0-rc.2-MachineConfigServerCARotation.yaml
- blocked-edges/4.18.0-rc.3-MachineConfigServerCARotation.yaml
- blocked-edges/4.18.0-rc.4-MachineConfigServerCARotation.yaml
- blocked-edges/4.18.0-rc.5-MachineConfigServerCARotation.yaml
- blocked-edges/4.18.0-rc.6-MachineConfigServerCARotation.yaml
- blocked-edges/4.18.0-rc.7-MachineConfigServerCARotation.yaml
- blocked-edges/4.18.0-rc.8-MachineConfigServerCARotation.yaml
- blocked-edges/4.18.0-rc.9-MachineConfigServerCARotation.yaml
To be aligned with https://github.com/openshift/cincinnati-graph-data/pull/6506/files
/cc @wking
> MachineConfigServerCARotation: unify the message

- blocked-edges/4.19.3-AROMissingInternalLBSAN.yaml
- blocked-edges/4.19.6-AROMissingInternalLBSAN.yaml
To be aligned with https://github.com/openshift/cincinnati-graph-data/pull/7669
/cc @wking @fahlmant
> AROMissingInternalLBSAN: unify the message

- blocked-edges/4.19.10-IPsecLargeClusterConnectivity.yaml
https://issues.redhat.com/browse/OCPBUGS-55453 is still Unresolved
> CORENET-6196: extend to 4.19.10
