README.md
Also update the header to catch up with the pivot to Title Case from ff4c10a8cb (#6).
=> README: Link from workflow list to Quay-label section

hack/graph-util.py
This reverts commit 830db32ea5e358f81f6f38e32802dd50447e5727, #4.
Sorting by string is stable, and not terribly far from SemVer sorting.  Exact SemVer sorting would be nice, but is not important enough to be worth adding a dependency outside Python's standard libraries.
=> Revert "Process versions in semver order"

hack/graph-util.py
the quay API is slow.
With this change:
time hack/graph-util.py push-to-quay
real	0m15.458s
Without this change:
time hack/graph-util.py push-to-quay
real	2m45.408s
=> Make the calls to sync multithreaded

README.md, hack/graph-util.py
So folks can distinguish between the 4.2.14 build for amd64 and the one built for s390x, etc.
```console
$ oc adm release info quay.io/openshift-release-dev/ocp-release:4.2.14-x86_64 | grep 'Name\|Digest\|Arch'
Name:          4.2.14
Digest:        sha256:3fabe939da31f9a31f509251b9f73d321e367aba2d09ff392c2f452f6433a95a
OS/Arch:       linux/amd64
$ oc adm release info quay.io/openshift-release-dev/ocp-release:4.2.14-s390x | grep 'Name\|Digest\|Arch'
Name:          4.2.14
Digest:        sha256:26ba0c17618872c68a2e9a5002c3f3e48f75ae844fcf66e83063bd72a104cfc7
OS/Arch:       linux/s390x
```
=> hack/graph-util: Handle architecture build metadata

channels/candidate-4.2.yaml, channels/fast-4.2.yaml, channels/stable-4.2.yaml
We scrapped 4.2.15 because 4.2.16 (with an additional console fix, openshift/console#3991) recycled its errata link:
```console
$ oc adm release info quay.io/openshift-release-dev/ocp-release:4.2.16-x86_64 | grep errata
url: https://access.redhat.com/errata/RHBA-2020:0107
$ oc adm release info quay.io/openshift-release-dev/ocp-release:4.2.15-x86_64 | grep errata
url: https://access.redhat.com/errata/RHBA-2020:0107
```
By including a comment about that, we make the reasoning more discoverable for folks who wonder "what happened to 4.2.15?".
=> channels/*-4.2: Explain why we skipped 4.2.15

blocked-edges/OWNERS
Copied from `channels/OWNERS`.  graph-data folks are responsible for the tooling, but only release-admins get the final say on graph changes.
=> blocked-edges/OWNERS: Only release-admins can approve

channels/candidate-4.3.yaml
792cc4c3d7 (#40) pulled the block to allow this edge, but to get an edge in a given channel, both the source and target release need to be in that channel.
See also #44, which goes into more detail on 4.2->4.3 failure modes, some of which still occur on 4.2.16->4.3.0.
=> channels/candidate-4.3: Promote 4.2.16+amd64

blocked-edges/4.3.0-rc.0.yaml, blocked-edges/4.3.0-rc.3.yaml
Baked in edges:
```console
$ oc adm release info quay.io/openshift-release-dev/ocp-release:4.3.0-rc.0-x86_64 | grep Upgrades
Upgrades: 4.2.13
$ oc adm release info quay.io/openshift-release-dev/ocp-release:4.3.0-rc.3-x86_64 | grep Upgrades
Upgrades: 4.2.16, 4.3.0-rc.0, 4.3.0-rc.1, 4.3.0-rc.2
```
The wide `from` regexp was appropriate for 4.3.0-rc.0, which had no 4.3 update sources.  But rc.3 does have update sources, and we want to allow 4.3.0-rc.0 -> 4.3.0-rc.3, because it is not impacted by the
4.2->4.3 GCP update bug.  The overly-strict regexp was from 6d3db09996 (#34).
Also expand the referenced bugs to for the blocked 4.2 -> 4.3 edges (elaborating on [this comment][0]):
* Update hangs with [rhbz#1786993][1]:
Working towards 4.3.0...: 13% complete
and machine-config going …
=> blocked-edges/4.3.0-rc.3: Allow 4.3.0-rc.0 -> 4.3.0-rc.3

hack/graph-util.py
before it would just throw and exception. Now it complains that no command
was found and says the only valid one is {'push-to-quay'}
=> Return a better error if you forget to add the subcommand

README.md
Now that openshift/openshift-docs@42c10066ed (openshift/openshift-docs#18944) and its backports have landed.  Ideally we'd have a link here that could float with versions, but I'm fine manually bumping every so often as we cut new minor releases.
=> README: Link to docs for channel semantics

channels/candidate-4.2.yaml, channels/fast-4.2.yaml, channels/prerelease-4.1.yaml, channels/stable-4.1.yaml, channels/stable-4.2.yaml
I actually have no idea why we skipped these, but 4.1.34 is the next release after 4.1.31.
=> channels: Explain why we skipped 4.1.32 and 4.1.33

channels/candidate-4.2.yaml, channels/candidate-4.3.yaml, channels/fast-4.2.yaml, channels/fast-4.3.yaml, channels/stable-4.2.yaml, channels/stable-4.3.yaml
@vikaslaad on 2020-02-10:
> 4.2.17 was skipped due to multiple weeks in between
I'm not entirely clear on the motivation there, but have added a comment about the skip with an attempt at explaining it to all the channels in which 4.2.17 might have appeared.
=> channels: Explain why we skipped 4.2.17

channels/candidate-4.2.yaml, channels/fast-4.2.yaml, channels/stable-4.2.yaml
Not too sure about 4.2.3.  I'd guess we delayed it for long enough waiting for some important patch that we decided to just call it 4.2.4.
For 4.2.5:
```console
$ oc adm release info quay.io/openshift-release-dev/ocp-release:4.2.5 | grep Upgrades
Upgrades: 4.1.23, 4.2.4
$ oc adm release info quay.io/openshift-release-dev/ocp-release:4.2.7 | grep Upgrades
Upgrades: 4.1.24, 4.2.0, 4.2.1, 4.2.2, 4.2.4
```
For 4.2.6:
```
$ oc adm release info --pullspecs quay.io/openshift-release-dev/ocp-release:4.2.6 | grep '\.ci\.' | head -n1
aws-machine-controllers                       registry.svc.ci.openshift.org/ocp/4.2-art-latest-2019-11-13-203727@sha256:3ebe28f0fd7c77c667b787957d28609d5d04fb4ad901805d2af4ef09951c2d7a
```
=> channels: Explain the lack of 4.2.3, 4.2.5, and 4.2.6

blocked-edges/4.3.1.yaml, channels/candidate-4.2.yaml, channels/candidate-4.3.yaml, channels/fast-4.2.yaml, channels/fast-4.3.yaml, channels/stable-4.2.yaml, channels/stable-4.3.yaml
The release has been in the candidate analogs since 6ed3a35fa1 (#49), which is plenty of cook time.
=> channels/fast-4.2: Promote 4.2.18 (and 4.2.18+amd64 to fast-4.3)

blocked-edges/4.3.0-rc.0.yaml, blocked-edges/4.3.0-rc.3.yaml, blocked-edges/4.3.0.yaml, channels/candidate-4.3.yaml, channels/fast-4.3.yaml
The 4.2 machine-config fix was [rhbz#1782152][1], [landed in bd358bb][2], which is new in 4.2.18:
```console
$ oc adm release info --commits quay.io/openshift-release-dev/ocp-release:4.2.16-x86_64 | grep machine-config
machine-config-operator                       https://github.com/openshift/machine-config-operator                       31fed93186c9f84708f5cdfd0227ffe4f79b31cd
$ oc adm release info --commits quay.io/openshift-release-dev/ocp-release:4.2.18-x86_64 | grep machine-config
machine-config-operator                       https://github.com/openshift/machine-config-operator                       9366460085b2a24d825380759f554769ec5ab4f9
$ git --no-pager log --oneline --first-parent -2 9366460085
93664600 Merge pull request #1362 from rphillips/fixes/1787581_4.2
bd358bb7 Merge pull …
```
=> blocked-edges/4.3.0: Block 4.2.16 and earlier updating to 4.3

channels/candidate-4.3.yaml, channels/fast-4.3.yaml
Once a node enters a channel, we don't want to remove it.  Doing so would leave existing residents in that channel with the `VersionNotFound` error out of the cluster-version operator.  Restore 4.2.16+amd64 to the channels it was in before c22d57ef1b (#59), and rely on `blocked-edges` alone (also from c22d57ef1b) to keep 4.2.16 -> 4.3.0 out of the graph.
Folks on 4.2.16 in candidate-4.3 or fast-4.3 will now be suggested to take the 4.2.16 -> 4.2.18 -> 4.3.1 pathway into 4.3.
=> channels: Add 4.2.16+amd64 back to candidate-4.3 and fast-4.3

raw/OWNERS, raw/metadata.json
The metadata in this has been manually added on quay in the past.  It's
my understanding that we don't plan to a convenient mapping for adding
edges using `previous.add`, so we don't want a convenience structure for
this.
---
This is part of https://github.com/openshift/cincinnati/pull/226.
=> raw/metadata.json: add historical metadata from quay

channels/fast-4.2.yaml
It was promoted the feeder candidate-4.2 by 1ecf01587f (Merge pull request #50 from thiagoalessio/candidate-4.1, 2020-02-17).
This promotion is recommeneded via the script in #75, but should still be vetted by comparison with Telemetry/Insights data.
=> channels/fast-4.2: Promote 4.1.34 to fast-4.2

blocked-edges/4.3.2.yaml, blocked-edges/4.3.3.yaml, channels/fast-4.3.yaml, channels/stable-4.3.yaml
These releases are available on the customer portal. They are available for fresh installs, so should have representation in fast/stable. Edges are disabled as upgrading to these versions is not desired.
=> Added 4.3.2->4.3.3 to channels

channels/stable-4.3.yaml
This introduces edges from 4.2.20, 4.2.21 to 4.3.5.
Earlier versions of 4.2 were tested only against 4.3.0, 4.3.1, 4.3.2, 4.3.3 so withhold those versions. 4.2.20 and 4.2.21 is approximately 20% of the 4.2 fleet today, however 4.2.20 is growing rapidly.
=> Add 4.2 edges into stable-4.3

channels/candidate-4.4.yaml, channels/fast-4.4.yaml, channels/stable-4.4.yaml
So that Cincinnati doesn't complain when the console bumps its hard-coded list of channels and starts asking for stable-4.4 (openshift/enhancements#123 is in flight to remove the need for the console to hard-code available channels, but hasn't seen much recent progress).  And even without the console issue, the installer has been putting new clusters in stable-4.4 since openshift/installer@d7fb12c07a (openshift/installer#2940).
=> channels: Add candidate-4.4, fast-4.4, and stable-4.4

channels/candidate-4.5.yaml, channels/fast-4.5.yaml, channels/stable-4.5.yaml
Like 6947046673 (#111), but for 4.5.  There are no 4.5 consumers yet, but this change sets Cincinnati up for them once they arrive (and now that release-4.4 is no longer being fast-forwarded, the 4.5 consumers may land in the installer and console masters anytime).
=> channels: Add candidate-4.5, fast-4.5, and stable-4.5

blocked-edges/4.2.22.yaml, blocked-edges/4.3.5.yaml
These releases enable automated ca rotation without unique ca serial numbers which can break non-golang tls clients as per [1].
1: https://bugzilla.redhat.com/show_bug.cgi?id=1810036
=> Block upgrades to 4.3.5 and 4.2.22

hack/graph-util.py
The vast majority of the time we run this script we don't want
the debug data. Only the INFO data.
=> Switch logging level to 'info' by default

channels/fast-4.2.yaml, channels/stable-4.1.yaml, channels/stable-4.2.yaml
It was promoted the feeder prerelease-4.1 and candidate-4.2 four days ago by fe9434117f (Merge pull request #110 from joepvd/4.1.38-candidate, 2020-03-12).
[The bug which killed 4.1.37][1] was [fixed in d9f0019][2], which landed after 4.1.37:
```console
$ oc adm release info --commits quay.io/openshift-release-dev/ocp-release:4.1.37-x86_64 | grep ' jenkins '
jenkins                                       https://github.com/openshift/jenkins                                       76904bc459f27f8ea823d5c45a64a2748e782e4d
$ git --no-pager log --oneline -3 origin/release-4.1
d9f0019 (origin/release-4.1) Merge pull request #1033 from akram/4.1-nss-wrapper-2.204.2-and-plugins-updates
1cd33d9 - Bump jenkins 2.204.2 and all plugins versions - Symlink to Dockerfile.localdev
76904bc Merge pull …
```
=> channels/stable-4.1: Promote 4.1.38 to stable-4.1 and fast-4.2

blocked-edges/4.2.0.yaml, blocked-edges/4.2.1.yaml, blocked-edges/4.2.10.yaml, blocked-edges/4.2.11-s390x.yaml, blocked-edges/4.2.12-s390x.yaml, blocked-edges/4.2.12.yaml, blocked-edges/4.2.13-s390x.yaml, blocked-edges/4.2.13.yaml, blocked-edges/4.2.14.yaml, blocked-edges/4.2.16.yaml, blocked-edges/4.2.18.yaml, blocked-edges/4.2.19.yaml, blocked-edges/4.2.2.yaml, blocked-edges/4.2.20.yaml, blocked-edges/4.2.4.yaml, blocked-edges/4.2.7.yaml, blocked-edges/4.2.8.yaml, blocked-edges/4.2.9.yaml, blocked-edges/4.3.0.yaml, blocked-edges/4.3.1.yaml, blocked-edges/4.3.2.yaml, blocked-edges/4.3.3.yaml, channels/candidate-4.2.yaml, channels/fast-4.3.yaml, channels/stable-4.3.yaml
Expanding on the links from b1465b73da (#87).
Port bug:
* 4.4.0: [rhbz#1801300](https://bugzilla.redhat.com/show_bug.cgi?id=1801300), openshift/cluster-version-operator#322 which made it into 4.4.0-rc.0:
```console
$ oc adm release info --commits quay.io/openshift-release-dev/ocp-release:4.4.0-rc.0-x86_64 | grep cluster-version
cluster-version-operator                       https://github.com/openshift/cluster-version-operator                       23856901003b95b559087b8e83bffdee82872b2b
$ git --no-pager log --oneline --first-parent -6 origin/release-4.4
2385690 (origin/release-4.4) Merge pull request #332 from openshift-cherrypick-robot/cherry-pick-328-to-release-4.4
...
2df3d56 Merge pull request #322 from vrutkovs/remove-outdated-ports
```
* 4.3.z: …
=> blocked-edges: Details on bugs for 4.3.2 and 4.3.3

blocked-edges/4.3.0.yaml, blocked-edges/4.3.2.yaml, blocked-edges/4.3.3.yaml, blocked-edges/4.3.5.yaml, blocked-edges/4.3.8.yaml
Seems like a low-probability flake (we've had many successful 4.2->4.3 before seeing this), but we don't have a recovery procedure yet, so pull the edges while we get more details.
https://bugzilla.redhat.com/show_bug.cgi?id=1816302
=> blocked-edges/4.3: Block all 4.2->4.3 on PodIP vs. PodIPs, bug 1816302

channels/stable-4.3.yaml
It's been at least 24 days since the fast promotions landed, so finish the "phased rollout" and put them in stable.
* 4.2.16+amd64 was promoted to the feeder fast-4.3 by 7660e1d14c (#73, 2020-02-21).
* There was no 4.2.17 (no releases in the week after 4.2.16).
* 4.2.18+amd64 was promoted to the feeder fast-4.3 by fa66fd41b4 (#60, 2020-02-20).
* 4.2.19+amd64 was promoted to the feeder fast-4.3 by 04c5b057d2 (#64, 2020-02-24).
The previous comments about "only valid into" were from 505f7a64b1 (#109), and I'm not clear on the motivation.
=> channels/stable-4.3: Add 4.2.16 through 4.2.19 (amd64)

README.md, hack/graph-util.py
Now that Cincinnati is reading directly from the master branch, there is no need to manually publish to Quay labels.  Drop the `--token` argument to help make that clear.  We can't drop this script completely yet, because we need to slot in some Rust binary to cover pre-merge CI (e.g. "channels/whatever.yaml talks about 4.5.6.  Is there at least one release on quay.io with that version baked in?").
=> hack/graph-util: Drop --token

blocked-edges/4.3.9.yaml
Still not fixed in 4.3.z, [rhbz#1817040][1].
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1817040
=> blocked-edges/4.3.9: Block 4.2 -> 4.3.9 on PodIP vs. PodIPs, bug 1816302

blocked-edges/4.3.10.yaml, blocked-edges/4.3.11.yaml, blocked-edges/4.3.12.yaml, blocked-edges/4.3.9.yaml
4.3.8 introduced a change which blocks upgrades when the default SCCs are
mutated. That change was merged under the assumption that the CVO would not
block z-stream upgrades on that condition. However that change had not
merged yet and thus ~40% of clusters which have upgraded to 4.3.8-4.3.12
are now blocked from upgrading with out specifying the --force flag. 4.3.13
relaxes the Upgradeable=False such that you can now apply z-stream updates
when that condition is set. A future update, likely 4.3.14 will revert the change
which began setting that condition.
Because the slim majority of subscribed clusters had already upgraded into
this problem and because of the numerous previously blocked upgrades we
had decided to live with the problem until 4.3.13 ships. So once 4.3.13 is
promoted into …
=> Block edges to 4.3.8 through 4.3.12 on DefaultSecurityContextConstraints_Mutated

channels/candidate-4.3.yaml
https://coreos.slack.com/archives/CB95J6R4N/p1588689093421200?thread_ts=1588687463.420800&cid=CB95J6R4N for background
=> candidate-4.3: allow 4.2 s390x upgrades

channels/candidate-4.4.yaml
We put all architectures into fast-4.4 in b8bef52e3c (#214).  Catch candidate back up with an arch-agnostic version.
=> channels/candidate-4.4: Promote remaining 4.3.18 arches

blocked-edges/4.4.3.yaml
There's [a reasonably easy workaround][1] for folks who do get stuck, so not worth pulling the edge immediately.  But we want to pull the edge once there's a 4.3 -> 4.4 route that is not exposed to the fix, so cluster admins don't have to discover the workaround.  Blocking on that 4.3 -> 4.4 route (e.g. via 4.4.4).
/hold
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1830409#c7
=> blocked-edges/4.4.3: Block 4.3 -> 4.4.3 on etcd DNS SAN peer certs

blocked-edges/4.4.4.yaml
Need to have fixes for https://bugzilla.redhat.com/show_bug.cgi?id=1827337
before upgrading to 4.4. We didn't run into this with 4.4.3 because it only included 4.3.18+
=> Block 4.3.12, 4.3.13 to 4.4.4

blocked-edges/4.4.3.yaml, blocked-edges/4.4.5.yaml, blocked-edges/4.4.6.yaml
Extending 0a65fffd68 (#253) to subsequent releases which included the older 4.3 in their baked-in update sources.
Also consolidate the inline comment to be a one-liner for easier
grepping, and drop the unnecessary pipe from [23] character class.
=> blocked-edges/4.4.*: Block 4.3.12 and 4.3.13 -> 4.4

channels/fast-4.5.yaml
The versions of 4.4.z is the same versions present in the release image manifest for upgrades
=> Adding 4.4.10 and 4.4.11 to fast-4.5 channel

blocked-edges/4.3.29.yaml, channels/stable-4.3.yaml
Not sure this is the right format but trying to capture that 4.3.29 is broken for one arch.
https://bugzilla.redhat.com/show_bug.cgi?id=1855807 => https://coreos.slack.com/archives/CFFJUNP6C/p1594411217405400
=> block updates to 4.3.29 for s390x

hack/graph-util.py
Lots of our publish runs die with errors [like][1]:
```
DEBUG: syncing node=4.4.0-rc.2+amd64 channels=candidate-4.4
Traceback (most recent call last):
File "hack/graph-util.py", line 494, in <module>
push(directory='.', push_versions=args.versions)
File "hack/graph-util.py", line 247, in push
pool.map(sync, sync_nodes)
File "/usr/lib64/python2.7/multiprocessing/pool.py", line 250, in map
return self.map_async(func, iterable, chunksize).get()
File "/usr/lib64/python2.7/multiprocessing/pool.py", line 554, in get
raise self._value
urllib2.HTTPError: HTTP Error 429: Too Many Requests
```
We're no longer actually publishing with this script, see 397129c0e6 (#149).  This commit short-circuits `push()` to only get the load-time validation.  Hopefully soon we'll get a Rust replacement and can …
=> hack/graph-util: Stop dry-run syncing nodes in 'push'

blocked-edges/4.5.2.yaml
Now that 4.5.3 has shipped 4.5.1 folks should go directly to 4.5.3
/cc @LalatenduMohanty
=> Widen the block to 4.5.2 to include all releases

blocked-edges/4.5.6.yaml
Suspected increase I/O during 8.1 to 8.2 RHCOS upgrade tipping over etcd https://bugzilla.redhat.com/show_bug.cgi?id=1861017
This makes 4.5.6 match 4.5.5 minimum 4.4.z versions
```
$ oc adm release info quay.io/openshift-release-dev/ocp-release:4.5.6-x86_64  | grep Upgrade
Upgrades: 4.4.11, 4.4.12, 4.4.13, 4.4.14, 4.4.15, 4.4.16, 4.4.17, 4.5.1, 4.5.2, 4.5.3, 4.5.4, 4.5.5
$ oc adm release info quay.io/openshift-release-dev/ocp-release:4.5.5-x86_64  | grep Upgrade
Upgrades: 4.4.13, 4.4.14, 4.4.15, 4.4.16, 4.5.1, 4.5.2, 4.5.3, 4.5.4
```
=> Block upgrades from 4.4.12- to 4.5.6

blocked-edges/4.4.12-to-4.5.7.yaml
Suspected increase I/O during 8.1 to 8.2 RHCOS upgrade tipping over etcd
https://bugzilla.redhat.com/show_bug.cgi?id=1861017
=> 4.4.13 is the minimum version required to upgrade to 4.5

hack/errata.py
Some day we will automatically promote to fast when the errata goes public, but, for now, mention the folks responsible for manually approving the pull request.
Syntax described [here][1].  `STE7S7ZU2` is `@ota-monitor`.
[1]: https://api.slack.com/reference/surfaces/formatting#mentioning-groups
=> hack/errata: Mention @ota-monitor

hack/errata.py
This makes it easier to [integrate with a Kubernetes secret][1].
[1]: https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables
=> hack/errata: Support 'WEBHOOK' environemnt variable

blocked-edges/4.5.9.yaml
We're not clear on whether any of the regressions in kernel-0-4.18.0-193.19.1.el8_2-x86_64 -> kernel-0-4.18.0-193.14.3.el8_2-x86_64, etc. will have a meaningful impact on OpenShift clusters, but blocking the edge now before either release goes into stable avoids the risk that the regression is important.
=> blocked-edges/4.5.9: Block 4.4.21 -> 4.5.9 to avoid kernel downgrades

hack/errata.py
erratahoook deployment on datahub adds extra `\n` to the github token stored in the secret in the resulting queries. I checked the secret and it doesn't contain extra new line, so it must be python argparse doing that.
This would ensure received arguments are stripped.
/cc @wking
=> hack/errata: strip newlines in argparse arguments

hack/errata.py
PyGithub can't filter by author in query params, so PRs need to be checked in the loop.
Fixes
```
DEBUG:root:looking for errata 59090 in open PRs for repo Repository(full_name="openshift/cincinnati-graph-data")
WARNING:root:Error looking up PRs: get_pulls() got an unexpected keyword argument 'author'
```
/cc @wking
=> hack/errata: pygithub can't filter by author - skip PRs unless bot has created it

hack/errata.py
And use it to double-check the update service's errata URI for that version vs. the advisory title.  This should avoid matching on errata like [OpenShift Container Platform 4.5.11 optional CSI driver
Operators bug fix update][1] (we're interested in OCP core release images, not in CSI and other optional operators).
Comparing with candidate errata gives us additional assurance that we aren't using errata promotion to recommend fast promotion for something that hasn't landed in candidate yet.
CC @LalatenduMohanty, @vrutkovs
[1]: https://access.redhat.com/errata/RHBA-2020:3768
=> hack/errata: Extract version from errata synopsis

channels/fast-4.6.yaml, channels/stable-4.6.yaml
Like adde027889 (#113), but without candidate because we got that in 713f464bc4 (#376).  This sets us up to avoid `VersionNotFound` issues once [rhbz#1884760][1] lands.
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1884760
=> channels: Add fast-4.6 and stable-4.6

graph-data.rs/Cargo.lock, graph-data.rs/Cargo.toml
Use protoc/protobuf 2.8.0 compatible with Rust 1.43. This fixes rehearsal issue in https://github.com/openshift/release/pull/12491
=> graph-data.rs: pin protobuf and protoc

graph-data.rs/Cargo.lock, graph-data.rs/Cargo.toml
Tilde notation brings in 2.8.2, which breaks [cincinnati build](https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_release/12491/rehearse-12491-pull-ci-openshift-cincinnati-graph-data-master-images/1313860052322357248/build-log.txt)
=> graph-data.rs: pin protobuf to 2.8.0

graph-data.rs/Dockerfile, graph-data.rs/src/verify_yaml.rs
Previously Rust CI tool was using `graph-data.rs` context, so that it would produce an image with just the binary. The plan was to promote it to `cincinnati-ci` namespace and avoid rebuilding it to save time.
However that didn't really work well:
* CI can't do optional builds atm, so there is no way to skip the build even if `graph-data.rs` is not touched
* There is no easy way to run the image with other src from the repo. CI provides a way to build `bin` container from `src`, but currently it would break existing python script, so implementation of that needs to be postponed.
This PR would rework graph-data Dockerfile so that it would include the whole repo and adjust the test to run from current directory (previously the binary was expected to run from the subfolder)
/cc @steveeJ
=> Graphdata rework dockerfile

hack/errata.py
Bot should show a link to Github UI instead of API URL.
/cc @wking
=> hack/errata: show HTML link in bot message

graph-data.rs/Dockerfile
In newer openshift versions builds must explicitly declare a user,
otherwise these would run as unprivileged user. However copied source
would be owned by root, so `target/release` cannot be created.
=> graph-data.rs/Dockerfile: run cargo install as root

hack/errata.py
Some erratas may include security fixes, so their format changes from
```
OpenShift Container Platform 4.3.40 bug fix update
```
to
```
Low: OpenShift Container Platform 4.3.40 security and bug fix update
```
This PR optionally matches impact and "security and " stanza.
=> hack/errata: include erratas with security update

graph-data.rs/Cargo.lock, graph-data.rs/Cargo.toml, graph-data.rs/src/check_releases.rs, graph-data.rs/src/check_signatures.rs, graph-data.rs/src/main.rs, graph-data.rs/src/verify_yaml.rs
This uses several constants from CVO to verify that all images have a
signature file present. This doesn't verify the that the signature is
valid though.
TODO:
Ref: https://issues.redhat.com/browse/OTA-153
=> graph-data.rs: ensure signatures are present for all scraped images

blocked-edges/4.5.14-15-to-4.6.1.yaml, blocked-edges/4.6.1.yaml, blocked-edges/4.6.3.yaml
4.5.16+ to 4.6.4 is the best known upgrade path at this point in
time
=> Block 4.5 to 4.6.1 and 4.6.3

build-suggestions/4.3.yaml, build-suggestions/4.4.yaml, build-suggestions/4.5.yaml, build-suggestions/4.6.yaml, build-suggestions/4.7.yaml
This adds minor_min, minor_block_list, minor_max, z_min, z_block_list,
and z_max which define the minimum, a list of blocked versions, and a
maximum version which can be used to filter upgrade edges. It's expected
that this is applied atop a list of versions already present in a
channel so the block_list may not see much use.
There's a default as well as arch specific definitions. If you define
arch specific data you are expected to define the entire structure.
=> Add suggestions

hack/errata.py
To match:
Moderate: OpenShift Container Platform 4.5.20 bug fix and golang security update
while continuing to exclude:
OpenShift Container Platform 4.5.11 optional CSI driver Operators bug fix update
from ee59956db5 (#480).  I'm not sure why the 4.5.20 approach differs from:
Low: OpenShift Container Platform 4.3.40 security and bug fix update
from d161733812 (#513), but we don't get to name these, we just have to match the names other folks pick.
Also adds a commit to log excluded synopses, to make debugging this sort of match failure easier going forward.
=> hack/errata: Match '... bug fix and golang security update' synopsis

blocked-edges/4.6.4.yaml
We fixed ~ 35 bugs in 4.6.6 and one of them was a prometheus storage
utilization regression from 4.5, so lets funnel everyone to the best
4.6.
=> Block 4.5 to 4.6.4

blocked-edges/4.6.6.yaml, blocked-edges/4.6.7.yaml
There aren't all that many born-in-4.1 clusters within striking distance of 4.6.6+, so the number of vulnerable clusters is small. But `*.apps` breaking would be really bad, so block the edges to protect that small subset.  [rhbz#1904582](https://bugzilla.redhat.com/show_bug.cgi?id=1904582).
We could keep 4.6.6 -> 4.6.7 in place, but I didn't bother to figure out the regexp for "all versions that aren't 4.6.6".
=> blocked-edges/4.6.6: Block * -> 4.6.(6|7) on born-in-4.1 ingress

blocked-edges/4.7.0.yaml
Baked in update sources:
```console
$ oc adm release info quay.io/openshift-release-dev/ocp-release:4.7.0-x86_64 | grep Upgrades
Upgrades: 4.6.15, 4.6.16, 4.6.17, 4.6.18, 4.6.19, 4.7.0-fc.1, 4.7.0-fc.2, 4.7.0-fc.3, 4.7.0-fc.4, 4.7.0-fc.5, 4.7.0-rc.1, 4.7.0-rc.2, 4.7.0-rc.3
```
But 4.6.18 is the latest 4.6.z.  Block edges from 4.6.19 to 4.7.0 for now, so we aren't recommending an update that would regress (e.g. if 4.6.19 fixes a kernel CVE or whatever, and 4.7.0 was cut before that CVE was fixed).  If it turns out that 4.6.19 has no fixes that aren't included in 4.7.0, we can drop the block.
=> blocked-edges/4.7.0: Block edges from 4.6.19

.gitignore, hack/requirements.txt, hack/test_errata.py
Initial unit tests for the errata-webhook.
Pull request related to https://issues.redhat.com/browse/OTA-356.
=> errata-webhook: add initial unit tests

graph-data.rs/Dockerfile
RHEL8-based Rust 1.47 as a builder and minimal UBI 8 as a base image. UBI minimal already inlcudes openssl-libs so `openssl` is no longer required.
TODO:
https://github.com/openshift/release/pull/13484 would make CI use cached image
=> graph-data.rs/Dockerfile: use rhel8/rust-toolset:1.47

.github/dependabot.yml
Cargo.toml is in `graph-data.rs`, not `hack`
Fixes issue in https://github.com/openshift/cincinnati-graph-data/network/updates/96914164
=> dependabot: fix directory

blocked-edges/4.7.1.yaml, blocked-edges/4.7.2.yaml, blocked-edges/4.7.3.yaml
4.7 has cross-node SDN issues on vSphere Virtual Hardware Version 14 and later: [rhbz#1935539][1].
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1935539
=> blocked-edges/4.7: Block all edges from 4.6

build-suggestions/4.7.yaml
We've had a few stable releases out in 4.7.z now, so anyone still running the FCs and RCs should be able to update to one of those (e.g. 4.7.2), and then update from there on to later 4.7.z.  Raising this floor makes life easier for ART, because they attempt to validate all the update edges we bake into release images.  Raising the floor means we no longer need to test FC and RC -> 4.7.z for new releases.
=> build-suggestions/4.7: Bump z_min to 4.7.0

blocked-edges/4.7.4.yaml
[Impact statement on rhbz#1942207][1].
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1942207#c3
=> blocked-edges/4.7.4: Block all edges into 4.7.4 on vSphere node hostnames

build-suggestions/4.7.yaml
[rhbz#1943143][1], child of [4.8's rhbz#1942207][2], didn't make it into 4.7.5, so we want to block all edges into 4.7.5 (like we did for 4.7.4 in 26b44c6efe, #731).  Raising the suggestion floors into the distant future will get 4.7.5 built without update suggestions, which will avoid a confusing message about update sources in the generated errata message.
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1943143
[2]: https://bugzilla.redhat.com/show_bug.cgi?id=1942207
=> build-suggestions/4.7: Raise *_min to 4.y.9999

build-suggestions/4.7.yaml
This partially reverts commit f190365bec2619b041a8c5035f92baf7429b6a94, #732.
The vSphere hostname thing is [verified fixed in 4.7][1].  And [the vSphere HW thing][2].  A new-in-4.7.3 OVN thing that we'd [been on the
fence about blocking on][3] should also [be fixed][4].
4.6.4 will fix [an issue][5] with non-control-plane UPI vSphere MachineConfigPools getting stuck if you update to 4.7 while they're churning a 4.6 udpate, so we're setting the 4.6 floor at 4.6.24.  Folks on older 4.6 will have to get to at least 4.6.24 to pick up that fix before they can go to 4.7.
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1943143#c4
[2]: https://bugzilla.redhat.com/show_bug.cgi?id=1941246#c6
[3]: https://bugzilla.redhat.com/show_bug.cgi?id=1940498#c12
[4]: …
=> Partially revert "build-suggestions/4.7: Raise *_min to 4.y.9999"

hack/test_errata.py
Testing the regular expression against content that has tripped us up before.  The examples I'm using were mentioned in commit messages:
* 4f969bfd43 (#522).
* 6e8d3fbadd (#558)
* d161733812 (#513).
* ee59956db5 (#480).
And:
Moderate: OpenShift Container Platform 4.7.5 security and bug fix update
which [just shipped][1].
[1]: https://access.redhat.com/errata/RHSA-2021:1005
=> hack/test_errata: Test synopsis matching

graph-data.rs/Cargo.lock, graph-data.rs/Cargo.toml, graph-data.rs/src/main.rs
This updates graph-data.rs to latest Cincinnati, so that we could use latest tokio and reqwest crates.
/cc @PratikMahajan @wking @LalatenduMohanty
=> Cargo: bump Cincinnati

graph-data.rs/Cargo.lock, graph-data.rs/Cargo.toml, graph-data.rs/src/main.rs
Reverts openshift/cincinnati-graph-data#752
I dunno if this has been causing [the "unresolved import `actix_service::pipeline_factory`" errors][1] or not, but floating a revert and watching it's CI is an easy way to check.
[1]: https://github.com/openshift/cincinnati-graph-data/pull/759#issuecomment-821672409
=> Revert "Cargo: bump Cincinnati"

hack/errata.py, hack/test_errata.py
Additional unit tests for the errata-webhook.
- New unit tests mainly focused on the `public_errata_uri` and the `process_message` functions.
- Refactoring of the initial unit tests.
- Refactoring the `errata.py` to be more testable.
- Fixing a potential bug in the `errata.py`.
Pull request related to https://issues.redhat.com/browse/OTA-356.
=> errata-webhook: add additional unit tests, refactor, and a fix

graph-data.rs/Cargo.lock, graph-data.rs/Cargo.toml, graph-data.rs/src/main.rs
* recent Cincinnati commit
* tokio 1.5
* lazy_static 1.4.0
* reqwest 0.11
Pinned actix-http and actix-service to be compatible with Cincinnati
See #752 for previous attempt
=> Cargo: update dependencies

channels/fast-4.8.yaml
These are in candidate-4.8, and also have public errata, so the stabilizer wants them in fast-4.8:
```console
$ hack/stabilization-changes.py
...
INFO: considering promotions from candidate-4.8 to fast-4.8 after P1W
INFO:   recommended: 4.7.0 (7 days, 20:34:17.149479)
DEBUG:     channels/fast-4.8: Promote 4.7.0 to fast-4.8
DEBUG:     It was promoted the feeder candidate-4.8 by 8a206158ff (Merge pull request #761 from wking/backfill-4.8-into-candidate-4.8, 2021-04-20).
...
```
But we want to keep them out of stable-4.8, because with our current lack of phased rollouts, because that's our mechanism for delaying the 4.7 -> 4.8 stable update recommendations.  [Lala doesn't want them in fast-4.8 either][1], out of concern that their presence would confuse users before the 4.8 GA.
[1]: …
=> channels/fast-4.8: Exclude 4.7.z releases

channels/candidate-4.7.yaml, channels/candidate-4.8.yaml
As described in [rhbz#1967614][1], this can wedge updates between releases where monitoring/Prometheus had soft-anti-affinity to releases where it had hard-anti-affinity, in some storage/monitoring/topology situations.
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1967614
=> channels/candidate-4.[78]: Tombstone 4.7.14 on hard anti-affinity vs. volume affinity

blocked-edges/4.6.30.yaml
CMO goes degraded when user monitoring workflow is enabled due to DNS changes https://bugzilla.redhat.com/show_bug.cgi?id=1953518
=> Block 4.6.30 due to bug 1953518

hack/errata.py, hack/test_errata.py
It has a slightly different bug/security phrasing than previous bug/security errata.  Also add a helper to treat RHBA and RHSA as synonyms, because ART sometimes guesses wrong when baking the URI into the release image (details in the commit messages).
=> hack/errata: Match the 4.7.13 errata message

channels/candidate-4.6.yaml, channels/candidate-4.7.yaml
It was renamed to 4.6.34 using the same errata:
```console
$ curl -sH accept:application/json 'https://api.openshift.com/api/upgrades_info/v1/graph?channel=candidate-4.6' | jq -r '
>    .nodes as $n |
>     [$n[].metadata.url] | unique[] | . as $url |
>     ([$n[] | select(.metadata.url == $url).version]) as $versions |
>     select(($versions | length) > 1) | $url + " " + ($versions | join(" "))
>   ' | sort
...
https://access.redhat.com/errata/RHBA-2021:2267 4.6.33 4.6.34
...
```
=> channels/candidate-4.[67]: Tombstone 4.6.33

channels/candidate-4.7.yaml, channels/candidate-4.8.yaml
MCO does not cordon nodes on upgrade https://bugzilla.redhat.com/show_bug.cgi?id=1973006
=> Tombstone 4.7.17

channels/eus-4.6.yaml
It was promoted to the feeder stable-4.6 by 566e20146c (Merge pull request #888 from openshift/promote-4.6.35-to-stable-4.6, 2021-06-24) 0:14:35.245033 ago.
=> channels/eus-4.6: Promote 4.6.35

build-suggestions/4.8.yaml
z_min will of course be updated at GA but minor_min will not be updated again unless we become aware of a specific identified issue affecting upgrade success
=> Align minimum 4.7.z to latest at code freeze

blocked-edges/4.7.0.yaml, blocked-edges/4.7.1.yaml, blocked-edges/4.7.2.yaml, blocked-edges/4.7.3.yaml, blocked-edges/4.7.4.yaml, blocked-edges/4.7.5.yaml, blocked-edges/4.7.6.yaml, blocked-edges/4.7.7.yaml, blocked-edges/4.7.8.yaml, blocked-edges/4.7.9.yaml
1dd86a31bb (#891) was a bit too broad.  This commit makes two changes:
* The bug was an issue with all the early 4.7, up until the fix landed in 4.7.11.  So even though 4.7.4 and earlier already had incoming blocks for other bugs, I'd have added comments there too about their exposure to this bug.  That also helps set patterns for when we do have targeted edge blocking, so folks considering ignoring our recommendations and doing 4.6 -> 4.7.4, for example, would know they were exposed to all three of the blocker-worthy bugs that are known (so far) to affect that edge.
* The fact that this was a 4.6-to-4.7 regression, and not a 4.7.z regression, means that 4.7.4->4.7.5 and such were not increasing your exposure to the issue (much, I guess memory would be tighter while the nodes were …
=> blocked-edges/4.7: Soften auth connection-leak blocking

channels/candidate-4.6.yaml, channels/candidate-4.7.yaml
The fix for [rhbz#1926944][1], which landed in 4.6.37, caused a regression in proxy handling in 4.6.37 ([rbhz#1978041][2]).
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1926944
[2]: https://bugzilla.redhat.com/show_bug.cgi?id=1978041
=> channels/candidate-4.[67]: Tombstone 4.6.37

blocked-edges/4.5.41-to-4.6.35.yaml, blocked-edges/4.5.41-to-4.6.36.yaml
As the OS version in 4.5.41 is higher than 4.6.35 and 4.6.36
=> Blocking edge from 4.5.41 to 4.6.35 and 4.6.36

README.md, channels/fast-4.2.yaml, channels/fast-4.3.yaml, channels/fast-4.4.yaml, channels/fast-4.5.yaml, channels/fast-4.6.yaml, channels/fast-4.7.yaml, channels/fast-4.8.yaml, channels/stable-4.1.yaml, hack/stabilization-changes.py
We currently have hack/errata.py to look for errata notifications in data-grepper, but data-grepper requires VPN access and fiddly synopsis matching.  Teaching stabilization-changes.py about checking directly for public errata is a step towards making stabilization changes something we can run in an external cluster without VPN access.
=> hack/stabilization-changes: Check for public errata

build-suggestions/4.8.yaml
On account of https://bugzilla.redhat.com/show_bug.cgi?id=1977383
which leads to potential workload disruption during upgrades to
4.8. Note, this is only the assumed target version, this may change.
=> Update minimum 4.7.z to 4.8

requirements.txt
The file is [consumed by source-to-image Python builds][1], which helps for things like running `hack/stabilization-changes.py` in a development cluster.  The format is documented [here][2].  The current latest releases for our two deps are [PyYAML 5.4.1][3] and [PyGithub 1.55][4].  I'm not bothering to freeze out the deeper dependencies, because they seem unlikely to break us, and if they do, we can notice and pin them in the future.
[1]: https://github.com/sclorg/s2i-python-container/tree/9d15b0d9d13777821d90a80f24f4ef0ced198c23/3.6#source-repository-layout
[2]: https://pip.pypa.io/en/latest/cli/pip_install/#requirements-file-format
[3]: https://pypi.org/project/PyYAML/
[4]: https://pypi.org/project/PyGithub/
=> requirements: Add requirements for Python scripts

hack/stabilization-changes.py
I'd added the pull code in f1ff8663dd (#926), to catch the local state up as the upstream branch advanced (via the bot's own stabilization pull requests landing or via other folks' pull requests).  But we aren't triggering rebuilds of the stabilization-changes image on branch bumps today, so when the robot pod is rescheduled or otherwise comes back up, it may be days or more stale.  We want to catch it up with upstream before the first stabilization check, so it doesn't pester our Slack channel with:
> * FAILED channels/fast-4.6: Promote 4.6.39. It was promoted to the feeder candidate-4.6 by 52f31155ee (Enable 4.6.39 in candidate channel(s), 2021-07-14) 7 days, 14:45:15.448017 ago. https://access.redhat.com/errata/RHBA-2021:2684 is public. version 4.6.39 has already been promoted to …
=> hack/stabilization-changes: When polling, always pull before checking for stabilization

channels/candidate-4.8.yaml
s390x missed a kernel bump that went into the other platforms.  We're building 4.8.2 to catch s390x up.
=> channels/candidate-4.8: Tombstone 4.8.1

channels/fast-4.8.yaml
It was promoted to the feeder candidate-4.8 by 693ccc8fa4 (Merge pull request #939 from openshift/pr-candidate-4.8.2, 2021-07-22) 5 days, 3:06:13.159115 ago. https://access.redhat.com/errata/RHSA-2021:2438 is public.
=> channels/fast-4.8: Promote 4.8.2

channels/stable-4.7.yaml, channels/stable-4.8.yaml
The most current minor goes to 96hr, and in order to avoid the previous
minor not having upgrade paths into the latest minor extend its delay to
reduce the likelihood of that happening. This may be moot until we actually
bring stable channel upgrades to 4.8 and perhaps by the time we achieve
that milestone we decide to get closer to 72, 48, 24 across 4.N, 4.N-1, 4.N-2.
/cc @wking @LalatenduMohanty
=> Extend promotion delays

channels/stable-4.8.yaml
It was promoted to the feeder fast-4.8 by 6c1dd9adcb (Merge pull request #959 from openshift/promote-4.8.3-to-fast-4.8, 2021-08-03) 4 days, 0:13:40.762332 ago.
=> channels/stable-4.8: Promote 4.8.3

channels/stable-4.8.yaml
It was promoted to the feeder fast-4.8 by b08946faaa (Merge pull request #973 from openshift/promote-4.8.4-to-fast-4.8, 2021-08-10) 4 days, 0:08:15.936925 ago.
=> channels/stable-4.8: Promote 4.8.4

channels/candidate-4.7.yaml, channels/candidate-4.8.yaml
Both releases [have CRI-O-not-found issues][1] on clusters born in 4.5 or earlier.
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1995785
=> channels/candidate-4.[78]: Tombstone 4.7.25 and 4.8.6 on CRI-O path

channels/fast-4.9.yaml, channels/stable-4.9.yaml
Now that ART has created candidate-4.9 with 4f8341049f (#997), create fast and stable consumers.  These won't hold any versions until 4.9 GAs, but creating the files with 'filter' makes that policy explicit.  Holding fast and stable 4.(y-1) releases out at this point avoids getting folks on those supported channels too excited about 4.y before it GAs. With the filter on fast-4.y, there is no need for a subsequent filter on stable-4.y, anything in fast is free to flow into stable after the configured delay.  But I've set the same filter in the stable channel anyway, because that's what we'll be using there post GA, while we look at 4.8 -> 4.9 updates in the fast channel before adding them to the stable channel.
=> channels/{fast,stable}-4.9: Stub in for candidate-phase 4.9 flow

blocked-edges/4.7.24.yaml, blocked-edges/4.7.28.yaml, blocked-edges/4.8.5.yaml, blocked-edges/4.8.9.yaml
From [the impact statement][1], vulnerable releases:
* 4.6.43 is unaffected, next 4.6.z to ship will be unless we fix things.
* 4.7.24 - 4.7.28 include the regression.
* 4.8.5 - 4.8.9 include the regression.
But looking at `channel/fast-4.8.yaml`, a bunch of the impacted releases did not ship.  This commit picks out the three which have, and also includes 4.7.28, which is expected to ship soon, and blocks updates to them from any released, unaffected update sources.
For example, annotating output with comments:
```console
$ oc adm release info -o json quay.io/openshift-release-dev/ocp-release:4.8.9-x86_64 | jq -r '.metadata.previous[]'
4.7.21  # blocking
4.7.22  # blocking
4.7.23  # blocking
4.7.24  # allowing, because it's already impacted, so updating doesn't make things worse
4.7.25  # …
```
=> blocked-edges: Block some edges into 4.7.24, 4.7.28, 4.8.5, and 4.8.9 on CRI-O /run leak

blocked-edges/4.7.28.yaml
I don't understand why the regexp I was dropping didn't match 4.7.23, but for some reason it wasn't:
```console
$ CHANNEL=fast-4.7 ~/src/openshift/cincinnati/hack/available-updates.sh 4.7.23
4.7.28  quay.io/openshift-release-dev/ocp-release@sha256:b3f38d58057a12b0477bf28971390db3e3391ce1af8ac06e35d0aa9e8d8e5966       https://access.redhat.com/errata/RHSA-2021:3262
```
We don't want folks going from safe releases to this vulnerable release, so block everyone for a bit while we figure out how to phrase "but not 4.7.24".
=> blocked-edges/4.7.28: Block all incoming edges while we sort regexps

blocked-edges/4.7.29.yaml, blocked-edges/4.8.10.yaml
These releases are still in candidate, but they seem to be headed into fast, so set up their edge blocks to keep folks from slipping into [the vulnerable 4.7.24+ or 4.8+][1].  Transitions within the vulnerable set are allowed.  Testing the complicated regexp vs. 4.7.29's built in edges and joining against supported fast-4.7 versions:
```console
$ join <(oc adm release info -o json quay.io/openshift-release-dev/ocp-release:4.7.29-x86_64 | jq -r '.metadata.previous[] | select(test("^(4[.]6[.].*|4[.]7[.][0-9]|4[.]7[.]1[1236789]|4[.]7[.]2[123])$") | not)' | sort) <(curl -s 'https://api.openshift.com/api/upgrades_info/v1/graph?channel=fast-4.7&arch=amd64' | jq -r '.nodes[].version' | sort)
4.7.24
4.7.28
```
And then adding `[+].*` to absorb [the architecture suffix][2].
[1]: …
=> blocked-edges: Block edges into 4.7.29 and 4.8.10 on Ceph corruption

blocked-edges/4.8.10.yaml
So tighten the regexp to only block the older entries:
```console
$ oc adm release info -o json quay.io/openshift-release-dev/ocp-release:4.8.10-x86_64 | jq -r '.metadata.previous[]' | sort -V | grep -v ^4.8
4.7.21
4.7.22
4.7.23
4.7.24
4.7.25
4.7.26
4.7.28
4.7.29
```
=> blocked-edges/4.8.10: Updates from 4.7.24+ already have the Ceph bug

README.md, blocked-edges/4.7.28.yaml
History:
* 2a70cf5bdc (#1022) attempted nuanced edge blocking.
* 49b580829e (#1025) added anchors, to prevent things like the `4[.]7[.][0-9]` alternative matching (and blocking) `4.7.24`, and similar.
* 9d348f9a08 (#1030), which went to `.*` because the anchored regexp was not matching as expected, and was allowing 4.7.23 -> 4.7.28 and similar.
It turns out that the versions Cincinnati is comparing with are [architecture-suffixed release names][1], not the raw release name from the release image's metadata.  So `4.7.24+amd64`, etc.  The new regular expression restores the multiple alternatives and anchors, but includes a new `[+].*` portion to absorb the architecture suffix.
[1]: https://github.com/openshift/cincinnati-graph-data/tree/f653d3828832c0869df0e44dd7af7fc9b2079a63#release-names
=> blocked-edges/4.7.28: Restore nuanced edge blocking

blocked-edges/4.7.10.yaml, blocked-edges/4.7.14.yaml, blocked-edges/4.7.15.yaml, blocked-edges/4.7.20.yaml
As these versions are tombstoned in candidate-4.7 channel but accidentally promoted to fast-4.8 channel in 8da5782
These are the commit id when the versions were the tombstoned: 00045bf4, a6629b78, b63be1be, 54accf9c
=> Blocking all the incoming edges to 4.7.10, 4.7.14, 4.7.15, 4.7.20

blocked-edges/4.7.28.yaml
A few releases slipped into fast-4.8, despite being tombzoned in candidate releases, 4c53c7b4bd (#1035).  Because I'd been comparing with fast-4.7 when developing the 4.7.28 blocker regexp, 2a70cf5bdc (#1022), those zombie releases still had edges:
```console
$ join <(oc adm release info -o json quay.io/openshift-release-dev/ocp-release:4.7.28-x86_64 | jq -r '.metadata.previous[] | select(test("^(4[.]6[.].*|4[.]7[.][0-9]|4[.]7[.]1[1236789]|4[.]7[.]2[123])$") | not)' | sort) <(curl -s 'https://api.openshift.com/api/upgrades_info/v1/graph?channel=fast-4.8&arch=amd64' | jq -r '.nodes[].version' | sort)
4.7.10
4.7.14
4.7.15
4.7.20
4.7.24
```
With this commit, I'm extending the regular expression to exclude them, except for 4.7.24 which is already vulnerable to the bugs impacting 4.7.28: …
=> blocked-edges/4.7.28: Expand blocked release to include fast-4.8 zombies

hack/stabilization-changes.py
Sometimes we accidentally promote releases to fast, despite having tombstoned them in candidate.  Make that sort of thing more discoverable.
=> hack/stabilization-changes: Warn about zombies

blocked-edges/4.7.29.yaml
Like 9ba34fccda (#1038), but for 4.7.29.
=> blocked-edges/4.7.29: Expand blocked release to include fast-4.8 zombies

Dockerfile
Loosely based on [1], but simplified because we have the data in the
local directory and don't need to curl it down.  We still need to
dynamically move it into the expected directory when this image is
invoked as an init-container [2].
[1]: https://docs.openshift.com/container-platform/4.8/updating/installing-update-service.html#update-service-graph-data_update-service
[2]: https://github.com/openshift/cincinnati-operator/blob/1a746871611d4ccb07aa7599c9eac0ef21df56d1/docs/graph-data-init-container.md
=> Dockerfile: For easy graph-data image construction

build-suggestions/4.9.yaml
To ensure OLM is [failing closed on missing `maxOpenShiftVersion`][1], because it's no fun if someone updates from 4.8.2 to 4.9 and has all their v1beta1-CRD-based OLM-installed operators break.
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1989711#c7
=> build-suggestions/4.9: Raise minor_min to 4.8.5

build-suggestions/4.9.yaml
It was bumped to 4.8.11 in fb730b7114 (#1065) to pick up [the Ceph data corruption fix][1].  I'm bumping it to 4.8.12 to pick up [etcd backups][2].  There will be at least one more bump further on to pick up [admin acks][3], but we don't need to wait for that before raising the floor.
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1996680
[2]: https://bugzilla.redhat.com/show_bug.cgi?id=1999777#c19
[3]: https://bugzilla.redhat.com/show_bug.cgi?id=1999092
=> build-suggestions/4.9: Bump minor_min to 4.8.12

blocked-edges/4.6.43.yaml
[rhbz#1997062#c36](https://bugzilla.redhat.com/show_bug.cgi?id=1997062#c36), extending #1022
=> blocked-edges/4.6.43: Turns out that it has the CRI-O /run leak too

channels/stable-4.6.yaml, channels/stable-4.7.yaml, channels/stable-4.8.yaml
Our telemetry analysis works best when we have a certain minimum
number of cluster days and our current delays weren't long enough.
As the fleet grows, participation in the fast channe grows, or we
improve our analysis we will revisit these values.
Aligning them all to the same value also ensures that we're less
likely to push something into stable-4.6 which cannot upgrade to
stable-4.7. We should also consider other solutions to this problem
such as only adding versions which do not match the channels X.Y
after that version has upgrade edges off of that, ie: 4.6.100 would
be added to stable-4.6 per normal delay, however it would not be
added to stable-4.7 until there's an upgrade from 4.6.100 to 4.7.N.
=> Increase fast to stable delay to 7d

channels/stable-4.6.yaml, channels/stable-4.7.yaml, channels/stable-4.8.yaml
Apparently our ISO 8601 duration implementation doesn't like D.
```
Traceback (most recent call last):
File "hack/stabilization-changes.py", line 431, in <module>
stabilization_changes(
File "hack/stabilization-changes.py", line 47, in stabilization_changes
notifications.extend(stabilize_channel(name=name, channel=channel, channels=channels, channel_paths=channel_paths, cache=cache, **kwargs))
File "hack/stabilization-changes.py", line 60, in stabilize_channel
delay = parse_iso8601_delay(delay=delay_string)
File "hack/stabilization-changes.py", line 36, in parse_iso8601_delay
raise ValueError('invalid or unsupported ISO 8601 duration {!r}.  Tooling currently only supports P<number>WT<number>H for week and/or hour offsets')
ValueError: invalid or unsupported ISO 8601 duration {!r}. …
```
=> Use 168H rather than 7D

channels/stable-4.6.yaml, channels/stable-4.7.yaml, channels/stable-4.8.yaml, hack/stabilization-changes.py
From [RFC 3339][1]:
```
Durations:
dur-second        = 1*DIGIT "S"
dur-minute        = 1*DIGIT "M" [dur-second]
dur-hour          = 1*DIGIT "H" [dur-minute]
dur-time          = "T" (dur-hour / dur-minute / dur-second)
dur-day           = 1*DIGIT "D"
dur-week          = 1*DIGIT "W"
dur-month         = 1*DIGIT "M" [dur-day]
dur-year          = 1*DIGIT "Y" [dur-month]
dur-date          = (dur-day / dur-month / dur-year) [dur-time]
duration          = "P" (dur-date / dur-time / dur-week)
```
So fully supported:
* `dur-hour`
* `dur-day` (this commit)
* `dur-week`
Not supported:
* `dur-second`
* `dur-minute`
* `dur-month`
* `dur-year`
Partially supported:
* `dur-time`
* `dur-date`
* `duration`
This allows us to revert 75c9c782a6 (#1103), to regain the more-intuitive days.
[1]: …
=> hack/stabilization-changes: Add support for day durations

hack/validate-blocked-edges.py
To keep us from forgetting to set `url`, etc.
We'll probably [want to have PromQL parser validation later][1], but I write Python a lot faster than I write Go.  This should avoid obvious mistakes while the PromQL parser gets wired up to a validator.
[1]: https://github.com/openshift/enhancements/blob/4412b51182ba6e007f1308a73e290e81fd66d092/enhancements/update/targeted-update-edge-blocking.md#promql-validation
=> hack/validate-blocked-edges: Add basic blocked-edges validation

channels/candidate-4.7.yaml, channels/candidate-4.8.yaml
It's missing errata URIs for s390x and ppc64le:
```console
$ for ARCH in x86_64 s390x ppc64le; do echo -n "${ARCH} "; oc adm release info -o json "quay.io/openshift-release-dev/ocp-release:4.7.35-${ARCH}" | jq -c .metadata.metadata; done
x86_64 {"description":"","url":"https://access.redhat.com/errata/RHSA-2021:3931"}
s390x null
ppc64le null
We want update UIs and similar to have that metadata, so they can link cluster admins to it, so the cluster admins can learn what is new with the target release they're considering updating to.
=> channels/candidate-4.[78]: Tombstone 4.7.35

channels/stable-4.9.yaml
It was promoted to the feeder fast-4.9 by 3c6edc9ab9 (Merge pull request #1161 from openshift/promote-4.9.4-to-fast-4.9, 2021-10-26) 7 days, 0:41:44.203011 ago.
=> channels/stable-4.9: Promote 4.9.4

channels/eus-4.8.yaml
At least until we hit 4.7.100, which my regexp would reject.  I expect that will never happen, and even if it does, it will be a long way off, and easy to recover from with further regexp tweaks.
This automates part of the promotion process that began manually in 470f191be3 (#1189), so now the stabilization robot will manage 4.7.z and 4.8.z promotion into this channel.  We'll still need to handle 4.6.z promotion manually for now, because the feeder stable-4.8 does not include any 4.6.z.  There are a few options being discussed to get that automated too, but in the meantime, this filter relaxation will reduce the amount of manual toil needed to maintain this channel.
=> channels/eus-4.8: Adjust filter to accept 4.6.z and 4.7.(z >= 34)

channels/stable-4.9.yaml
It was promoted to the feeder fast-4.9 by 1ff27c1803 (Merge pull request #1179 from openshift/promote-4.9.5-to-fast-4.9, 2021-11-01) 7 days, 0:08:35.404817 ago.
=> channels/stable-4.9: Promote 4.9.5

channels/eus-4.6.yaml
It was promoted to the feeder fast-4.6 by 0cfef393d4 (Merge pull request #1191 from openshift/promote-4.6.49-to-fast-4.6, 2021-11-03) 7 days, 0:52:56.103151 ago.
=> channels/eus-4.6: Promote 4.6.49

build-suggestions/4.10.yaml
Still plenty of time before we start cutting 4.10 feature candidates, but no harm in getting this content stubbed in ahead of time.
=> build-suggestions/4.10: Add initial build suggestions for 4.10

graph-data.rs/Cargo.lock, graph-data.rs/Cargo.toml
Ensure that latest cincinnati-graph-data is compatible with production Cincinnati, as agreed in https://hackmd.io/YoAQ5IkzQoSWqZMcDqPxAQ?edit
=> graph-data.rs: sync Cincinnati with prod commit

graph-data.rs/src/check_errata_link.rs, graph-data.rs/src/check_releases.rs, graph-data.rs/src/main.rs
This commit adds a new test to ensure that all released versions have valid errata links:
* Fetch all parsed releases in all channels
* Extract predicate from version. If its not empty it should match arch suffix (arm64/amd64), if its not this release is omitted from the check
* If the version without a predicate matches a known faulty version its being omitted
The test verifies the following things:
* Release can be converted into `ConcreteRelease`
* Release has "url" metadata key
* URL in the key matches errata URL regex
=> OTA-509: Add a test to verify that all stable releases have errata link

hack/show-edges.py
Because showing graphs for those can be convenient too.  Catches up with stabilization-changes pivots in bda213e3ef (#112).
=> hack/show-edges: Teach to walk internal-channels

build-suggestions/4.10.yaml
https://bugzilla.redhat.com/show_bug.cgi?id=2037665
While 4.9.18 includes logic to ensure that clusters cannot upgrade
to 4.10 without addressing the pre-requisite it introduces a minor
regression where it incorrectly blips through Upgradeable=False. As
such we will file a subsequent bump to a build with the complete
set of changes when that 4.9.z is tagged. Bumping now will avoid
potential known issues in upgrading between 4.9 and 4.10, so we'll
bump twice.
=> A prerequsite for 4.9 to 4.10 upgrades has been identified

blocked-edges/4.10.0-fc.2-modified-aws-load-balancer-service.yaml
Since 39bc2fb686 (#1056), we've had some example conditional updates back on `* -> 4.7.4`.  But now that 4.10 has feature candidates, this commit adds a conditional edge based on a minor 4.10.0-fc.2 issue that was fixed in fc.3.  Folks interested in seeing conditional edges in action can install fc.0 or fc.1 on AWS, and see that this conditional edge is not recommended.  Or they can install fc.0 or fc.1 on a non-AWS platform to see that the conditional edge is recommended.
=> blocked-edges/4.10.0-fc.2-modified-aws-load-balancer-service: Example conditional update

build-suggestions/4.10.yaml
Following up on 430e5364fa (#1401), now that 4.9.19 has been named, includes openshift/cluster-kube-scheduler-operator#403, and [rhbz#2037665][2] has been VERIFIED.
[2]: https://bugzilla.redhat.com/show_bug.cgi?id=2037665
=> build-suggestions/4.10: Bump minor min to 4.9.19

blocked-edges/4.10.0-fc.4-alibaba-storage-fixes.yaml
Following up on 38028a8931 (#1437) with a new invented, demo conditional update.  The earlier demo worked locally, but did not excercise Insights tooling, because [Insights only bumped their openshift/api vendor in fc.3][1]:
```console
$ for X in fc.0 fc.1 fc.2 fc.3 fc.4 rc.0; do echo -n "${X} "; oc adm release info --commits "quay.io/openshift-release-dev/ocp-release:4.10.0-${X}-x86_64" 2>/dev/null | grep insights-operator; done
fc.0   insights-operator                              https://github.com/openshift/insights-operator                              cafe71a62bda6ca7ea790da90753b7b7d3c006b7
fc.1   insights-operator                              https://github.com/openshift/insights-operator                              e2887e735adefb572a2e785d5cc071ec5844b123
fc.2 …
```
=> blocked-edges/4.10.0-fc.4-alibaba-storage-fixes: Example conditional update

hack/generate-weekly-report.py
And rename "failed" to "slow", because we don't want to imply that reconciliation stops at 8 hours.
=> hack/generate-weekly-report: Define stats columns

internal-channels/candidate.yaml
They were missing baked-in update edges from the most same-week's previous minor release:
```console
$ diff -u0 <(oc adm release info -o json quay.io/openshift-release-dev/ocp-release:4.8.30-x86_64 | jq -r '.metadata.previous[]' | sort -V) <(oc adm release info -o json quay.io/openshift-release-dev/ocp-release:4.8.31-x86_64 | jq -r '.metadata.previous[]' | sort -V)
--- /dev/fd/63  2022-02-09 12:12:23.429003517 -0800
+++ /dev/fd/62  2022-02-09 12:12:23.432003517 -0800
@@ -21,0 +22 @@
+4.7.43
@@ -48,0 +50 @@
+4.8.30
$ diff -u0 <(oc adm release info -o json quay.io/openshift-release-dev/ocp-release:4.9.19-x86_64 | jq -r '.metadata.previous[]' | sort -V) <(oc adm release info -o json quay.io/openshift-release-dev/ocp-release:4.9.21-x86_64 | jq -r '.metadata.previous[]' | sort -V)
--- …
```
=> internal-channels/candidate: Tombstone 4.8.30 and 4.9.19

graph-data.rs/src/verify_yaml.rs
Apart from officially supported stable/fast/candidate channels we also maintain internal-channels. Releases defined there should be included in the checks as well
=> graph-data.rs: check internal-channels

blocked-edges/4.10.0-fc.0.yaml, blocked-edges/4.10.0-fc.1.yaml, blocked-edges/4.10.0-fc.2.yaml, blocked-edges/4.10.0-fc.3.yaml, blocked-edges/4.10.0-fc.4.yaml, blocked-edges/4.10.0-rc.0.yaml
While we raised the minimums someone running versions less than the new minimum may see available 4.10 upgrades in the candidate channel and take them. We'd prefer everyone meet the current minimum version requirements so that we're not chasing down any bugs from those versions.
I can into this because I installed 4.9.18 and it offered me upgrades to 4.10.0-rc.0.
=> Block 4.10 upgrades from less than 4.9.19

internal-channels/candidate.yaml
On [some network policies blocking pod egress][1].
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=2060956
=> internal-channels/candidate: Tombstone 4.10.1

internal-channels/candidate.yaml
The 4.10.2 fix [was incomplete][1], and we'll need a 4.10.3.
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=2060956#c5
=> internal-channels/candidate: Tombstone 4.10.2

hack/stabilization-changes.py
We recently had this script hang for a day, with the traceback suggesting it was stuck in `get_cincinnati_channel`'s `urlopen` call.  From [the `urlopen` docs][1]:
> The optional *timeout* parameter specifies a timeout in seconds for blocking operations like the connection attempt (if not specified, the global default timeout setting will be used). This actually only works for HTTP, HTTPS and FTP connections.
And from [the `setdefaulttimeout` docs][2]:
> Set the default timeout in seconds (float) for new socket objects. When the socket module is first imported, the default is `None`. See `settimeout()` for possible values and their respective meanings.
With this commit, we'll fail on these stuck connections instead of hanging.  It seems unlikely that we'd have more than 60s of latency in …
=> hack/stabilization-changes: Set a default socket timeout of 60s

channels/eus-4.10.yaml
It was promoted to the feeder stable by 37c8bb64bb (Merge pull request #1660 from openshift/promote-4.10.4-to-stable, 2022-03-23) 0:47:45.378523 ago.
=> channels/eus-4.10: Promote 4.10.4

channels/stable-4.10.yaml
It was promoted to the feeder stable by 37c8bb64bb (Merge pull request #1660 from openshift/promote-4.10.4-to-stable, 2022-03-23) 0:47:57.481349 ago.
=> channels/stable-4.10: Promote 4.10.4

blocked-edges/4.9.27.yaml
Since we decided not to raise the floor we'll need to chase new 4.9.z
until we're comfortable unblocking 4.8 to 4.9 upgrades again.
=> Blocking all update edges from ocp 4.8 to 4.9.27

internal-channels/candidate.yaml
```console
$ diff -u0 <(oc adm release info quay.io/openshift-release-dev/ocp-release:4.10.7-x86_64) <(oc adm release info quay.io/openshift-release-dev/ocp-release:4.10.8-x86_64)
--- /dev/fd/63  2022-04-01 16:11:16.480328693 -0700
+++ /dev/fd/62  2022-04-01 16:11:16.482328693 -0700
@@ -1,3 +1,3 @@
-Name:      4.10.7
-Digest:    sha256:347fcefa4cff84074fa56ff73a483b9fee7ba98b9a71752763502f11182a11af
-Created:   2022-04-01T03:01:24Z
+Name:      4.10.8
+Digest:    sha256:0696e249622b4d07d8f4501504b6c568ed6ba92416176a01a12b7f1882707117
+Created:   2022-04-01T19:36:11Z
@@ -7 +7 @@
-Pull From: quay.io/openshift-release-dev/ocp-release@sha256:347fcefa4cff84074fa56ff73a483b9fee7ba98b9a71752763502f11182a11af
+Pull From: quay.io/openshift-release-dev/ocp-release@sha256:0696e249622b4d07d8f4501504b6c …
```
=> internal-channels/candidate: Tombstone 4.10.7 (rerolled as 4.10.8)

hack/stabilization-changes.py
Until now, the stabilization bot had push access to the upstream repository to create branches and pull requests.  But granting that access to bots is unnecessary work.  This change allows a bot to push branches to the bot's own repository, but to still file the pull requests against the central, upstream repository.
=> hack/stabilization-changes: Differentiate between upstream and push repos

build-suggestions/4.10.yaml
Not many folks still running pre-GA 4.10, and they are candidate releases anyway.  Having them update out to 4.10.10 might leave them exposed to whatever bugs we fix in 4.10.(>10), but they're already probably exposed to them in their current candidate release.  And they can add a second hop to get out to 4.10.(>10) and pick up fixes.  Raising the floor limits the number of update edges we test in CI to the ones that we actually support.
Like #1153 and earlier.
=> build-suggestions/4.10: Raise z_min to 4.10.3 (the GA release)

internal-channels/candidate.yaml
4.8.38 will get an RHCOS update and become 4.8.39
4.9.30 will be dropped this week
=> 4.8.38 and 4.9.30 had misaligned kernel and kernel-rt packages

build-suggestions/4.11.yaml
So we know that the cluster-version operator will be [using `ReleaseAccepted`][3] to pass the RecentBackup message to the etcd operator.  Details on the dance change [here][1].  CVO [pivot to using `ReleaseAccepted`][3] shipped [in 4.10.8][2].
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=2076793
[2]: https://bugzilla.redhat.com/show_bug.cgi?id=2064991#c7
[3]: https://github.com/openshift/cluster-version-operator/pull/753/files#diff-db97dc5ae62ef3b4c4dabfdc43cbc3ae0ceae9b58748cadebde679e32b5bec2bR160
=> build-suggestions/4.11: Raise minor_min to 4.10.8

build-suggestions/4.11.yaml
This fixes the `APIRemovedInNextReleaseInUse` alert `expr`, so admins will hear if the minor update to 4.11 would break a current deprecated-API consumer ([bug][1], [`expr` change][2]).
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=2071030#c6
[2]: https://github.com/openshift/cluster-kube-apiserver-operator/pull/1335/files#diff-d89e2ca0888b4394370e2849c02d91eb0f9857427db974f27408b0398df53f33L19-R19
=> build-suggestions/4.11: Raise minor_min to 4.10.12

hack/release-stable-minor.sh
Continuing in the spirit of 288b5daa57 (#1613) and d45fac659e (#1720).  These lifecycle events aren't frequent, and automating them decreases the odds that we fumble an unfamiliar transition.
I've left off the final:
```console
$ git add channels/*
$ git commit
```
but we could do that in the future if we wanted to control the commit message.
=> hack/release-stable-minor: Script minor-update stablization

build-suggestions/4.11.yaml
Because https://bugzilla.redhat.com/show_bug.cgi?id=2079097 needs to be
fixed in 4.10.z for the upgrade to 4.11
=> Bumping the minor_min to 4.10.14 because of BZ 2079097

internal-channels/candidate.yaml
because of https://bugzilla.redhat.com/show_bug.cgi?id=2088196
=> Tombstone 4.8.40 and 4.9.34

blocked-edges/4.10.10-parallel-ceph_fsync.yaml, blocked-edges/4.10.11-parallel-ceph_fsync.yaml, blocked-edges/4.10.12-parallel-ceph_fsync.yaml, blocked-edges/4.10.13-parallel-ceph_fsync.yaml, blocked-edges/4.10.14-parallel-ceph_fsync.yaml, blocked-edges/4.10.15-parallel-ceph_fsync.yaml, blocked-edges/4.10.4-parallel-ceph_fsync.yaml, blocked-edges/4.10.5-parallel-ceph_fsync.yaml, blocked-edges/4.10.6-parallel-ceph_fsync.yaml, blocked-edges/4.10.7-parallel-ceph_fsync.yaml, blocked-edges/4.10.8-parallel-ceph_fsync.yaml, blocked-edges/4.10.9-parallel-ceph_fsync.yaml
Some clusters have a number of these, mostly differing by instance:
```
ceph_health_status{..., container="mgr", endpoint="http-metrics", instance="10.128.4.12:9283", job="rook-ceph-mgr", namespace="openshift-storage", pod="rook-ceph-mgr-a-6886bc75b8-m6xkd", prometheus="openshift-monitoring/k8s", receive="true", service="rook-ceph-mgr", ...}  1
ceph_health_status{..., container="mgr", endpoint="http-metrics", instance="10.128.4.16:9283", job="rook-ceph-mgr", namespace="openshift-storage", pod="rook-ceph-mgr-a-6886bc75b8-m6xkd", prometheus="openshift-monitoring/k8s", receive="true", service="rook-ceph-mgr", ...}  1
...
```
But we don't care how many there are, we just care if there are any.  Wrapping `ceph_health_status` in a `group(...)` call ignores all the labels and aggregates down to …
=> blocked-edges/4.10.*parallel-ceph_fsync: Handle multiple ceph_health_status series

README.md, blocked-edges/4.10.10-parallel-ceph_fsync.yaml, blocked-edges/4.10.11-parallel-ceph_fsync.yaml, blocked-edges/4.10.12-parallel-ceph_fsync.yaml, blocked-edges/4.10.13-parallel-ceph_fsync.yaml, blocked-edges/4.10.14-parallel-ceph_fsync.yaml, blocked-edges/4.10.15-parallel-ceph_fsync.yaml, blocked-edges/4.10.4-parallel-ceph_fsync.yaml, blocked-edges/4.10.5-parallel-ceph_fsync.yaml, blocked-edges/4.10.6-parallel-ceph_fsync.yaml, blocked-edges/4.10.7-parallel-ceph_fsync.yaml, blocked-edges/4.10.8-parallel-ceph_fsync.yaml, blocked-edges/4.10.9-parallel-ceph_fsync.yaml
Continuing to clean up the PromQL from 707ec48c76 (#1915), which I'd previously revised in da76bd14ab (#1932).  We'd still been getting:
invalid PromQL result length must be one, but is 2
The semantics for [`or` are][1]:
> `vector1 or vector2` results in a vector that contains all original elements (label sets + values) of `vector1` and additionally all elements of `vector2` which do not have matching label sets in `vector1`.
I'd missed the `+ values` part of it, but it meant that when:
label_replace(group(ceph_health_status), "ceph", "yes", "", "")
hit, returning a series like `{ceph="yes"}=1`, and:
label_replace(0 * group(cluster_version), "ceph", "no", "", "")
hit, returning a series like `{ceph="no"}=0`, we'd return both of those series.  This commit wraps the expression in a …
=> blocked-edges/4.10.*parallel-ceph_fsync: Wrap in topk

blocked-edges/4.10.16-parallel-ceph_fsync.yaml
Extend conditional edges into 4.10.16 as we're still waiting on the
kernel fix.
=> blocked-edges/4.10.16: Parallel ceph_fsync risk for 4.10.4 and later

channels/eus-4.10.yaml
4.9.34 was rebuilt as 4.9.35 after 4.10.15 had already been built, 81edd48b89 (#1923).  Because we didn't rebuild a 4.10.16 to include updates from 4.9.35, that week's releases lack a 4.9 -> 4.10 update recommendation.  Hold 4.9 and 4.8 out of 4.10 for now, to avoid recommending 4.8 -> 4.9.35 -> no-path-to-4.10-just-now updates to those folks.  We'll revert this commit once we get a fresh 4.10.z in stable channels.
Alternative to #1974.
=> channels/eus-4.10: Hold 4.8.z and 4.9.z out

build-suggestions/4.11.yaml
More around the etcd-snapshot dance, last mentioned in 1ae2c3d3a6 (#1807):
* [4.10.8 pivoted][1] the cluster-version operator to using `ReleaseAccepted`.
* [4.10.14 taught][2] the etcd operator to look at `ReleaseAccepted`.
* [4.10.15 fixed][3] the cluster-version opetator's precondition revisits, which allows it to notice that the etcd operator has completed its snapshot.
We want all three of those in place before folks head off to 4.11.
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=2064991#c7
[2]: https://bugzilla.redhat.com/show_bug.cgi?id=2079660#c6
[3]: https://bugzilla.redhat.com/show_bug.cgi?id=2083370#c7
=> build-suggestions/4.11: Raise minor_min to 4.10.15

blocked-edges/4.9.38.yaml, blocked-edges/4.9.39.yaml
Because of https://bugzilla.redhat.com/show_bug.cgi?id=2095264#c9
=> Blocking z stream upgrade paths to 4.9.38 and 4.9.39

build-suggestions/4.11.yaml
We work really hard to test updates and identify regressions before shipping releases.  But there is a chance we miss something, and need to declare it as a conditional risk affecting 4.10 to 4.11 updates. [rbhz#2087041][1] landed web-console support for conditional updates in 4.10.16, so raising the minimum here ensures all users will have that convenient experience navigating any conditional risks which may have turned up by the time we're recommending supported updates to 4.11.
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=2087041#c5
=> build-suggestions/4.11: Raise minor_min to 4.10.16

channels/eus-4.10.yaml, channels/stable-4.9.yaml
Reverts openshift/cincinnati-graph-data#2093
4.9.40 has entered stable/EUS channels via #2154, #2155, #2156, so there are now paths out from 4.8.tip into 4.9, and we no longer need to delay these promotions.
=> Revert "channels: Delay 4.8 promotions into stable-4.9 and eus-4.10"

internal-channels/candidate.yaml
4.9.44 is dropped as it needs the fix for https://bugzilla.redhat.com/show_bug.cgi?id=2103982#c16
The fix is already available in the latest 4.9.z nightly.
Without the fix it will cause a regression for clusters upgrading from
4.9.z versions.
=> internal-channels/candidate: Tombstone 4.9.44

hack/stabilization-changes.py
We sometimes tombstone or otherwise do not release a 4.y.z in a given week, when we do release 4.(y-1).z'. Hypothetical example:
1. Some bug shows up which makes 4.98.0-to-4.99 conditionally risky, and we've raised `minor_min` to 4.98.25 for new 4.99 builds.
2. Week 1: 4.98.90 and 4.99.50 are built. All is well.
3. Week 2: 4.98.91 and 4.99.51 are built, but 4.99.51 gets tombstoned.
4. Week 3: 4.98.91 enters fast channels, including fast-4.99.
5. Alice is on 4.98.0, and decides to move to 4.99 via `fast-4.99`. There are no recommended updates to 4.99.50 or 4.9.51 because of the long-standing `minor_min` floor.
6. Alice sees recommendations to 4.98.90 and 4.98.91, and heads off to 4.98.91 because it fixes more bugs.
7. Oh no, there are no recommendations to get from 4.98.91 to 4.99. Alice …
=> hack/stabilization-changes: Gate 4.(y-1).z into fast-4.y, etc. on update paths to 4.y

channels/eus-4.8.yaml, channels/fast-4.8.yaml, channels/stable-4.8.yaml
Reverting #2253 and fd6471d96f7fc9c50ae60eafdc4e354897acc827 from #2245, now that #2059 has merged and been deployed to automate that sort of thing.  Testing locally:
```console
$ hack/stabilization-changes.py 
...
* Recommend waiting to promote 4.6.60 to eus-4.8; it was promoted the feeder stable by d0a81cd507 (Merge pull request #2267 from openshift-ota-bot/promote-4.6.60-to-stable, 2022-07-28, 6 days, 7:34:07.861655) No unconditional paths from 4.6.60 to 4.8 in https://api.openshift.com/api/upgrades_info/v1/graph?channel=candidate-4.8&arch=amd64 https://api.openshift.com/api/upgrades_info/v1/graph?channel=candidate-4.7&arch=amd64
* Recommend waiting to promote 4.7.54 to eus-4.8; it was promoted the feeder stable by 0a4c588e81 (Merge pull request #2237 from …
```
=> Revert temporary feeder adjustments

hack/show-edges.py
Avoid warnings like:
```console
$ hack/show-edges.py eus-4.10
WARNING: unable to get release metadata for quay.io/openshift-release-dev/ocp-release@sha256:97be7dfb62abe6dbf266d7037c0f31fcca9007f232021b0633cf1944a55250a0 {'name': '4.12.0-0.nightly-multi-2022-07-25-220750', 'reversion': False, 'start_ts': 1658787279, 'manifest_digest': 'sha256:97be7dfb62abe6dbf266d7037c0f31fcca9007f232021b0633cf1944a55250a0', 'is_manifest_list': True, 'size': None, 'last_modified': 'Mon, 25 Jul 2022 22:14:39 -0000'} : unsupported media type for quay.io/openshift-release-dev/ocp-release@sha256:97be7dfb62abe6dbf266d7037c0f31fcca9007f232021b0633cf1944a55250a0 manifest: application/vnd.docker.distribution.manifest.list.v2+json
...
```
and speed up repeated show-edges calls by allowing the caching of …
=> hack/show-edges: Process manifest lists

hack/release-ga.sh
Because of:
```console
$ man grep | grep -A1 'EXIT STATUS'
EXIT STATUS
Normally the exit status is 0 if a line is selected, 1 if no lines were selected, and 2 if an error occurred.  However, if the -q or --quiet or --silent is used and a line is selected, the exit  status  is  0  even  if  an  error
```
running:
```console
$ hack/release-ga 4.11
```
before there was a 4.11.* release in the fast channel to promote would cause the script to silently exit 1, which was confusing. 
With this commit, that situation now results in:
```console
$ hack/release-ga.sh 4.11
failed to find 4.11 releases in internal-channels/fast.yaml
```
=> hack/release-ga: Add error message when run before fast membership

blocked-edges/4.11.0-fc.0-cluster-verison-precondition-check.yaml, blocked-edges/4.4.12-to-4.5.4.yaml, blocked-edges/4.4.12-to-4.5.7.yaml, blocked-edges/4.5.41-to-4.6.35.yaml, blocked-edges/4.5.41-to-4.6.36.yaml
We've built up some unescaped values over time, most recently in 8467cfc174 (#2069).  In this commit, I escape them, to reduce the risk of folks copy/pasting and forgetting that `from` is a regular expression.
=> blocked-edges: Escape literal periods in 'from'

build-suggestions/4.11.yaml
Not many folks still running pre-GA 4.11, and they are candidate releases anyway.  Having them update out to 4.11.0 might leave them exposed to whatever bugs we fix in 4.11.(>0), but they're already probably exposed to them in their current candidate release.  And they can add a second hop to get out to 4.11.(>0) and pick up fixes. Raising the floor limits the number of update edges we test in CI to the ones that we actually support.
Similiar to 4.10's 07a7e88994 (#1752).
=> build-suggestions/4.11: Raise z_min to 4.11.0 (the GA release)

blocked-edges/4.11.0-fc.0-rpm-ostree-timeout.yaml, blocked-edges/4.11.0-fc.3-rpm-ostree-timeout.yaml, blocked-edges/4.11.0-rc.0-rpm-ostree-timeout.yaml, blocked-edges/4.11.0-rc.1-rpm-ostree-timeout.yaml, blocked-edges/4.11.0-rc.2-rpm-ostree-timeout.yaml, blocked-edges/4.11.0-rc.3-rpm-ostree-timeout.yaml, blocked-edges/4.11.0-rc.4-rpm-ostree-timeout.yaml, blocked-edges/4.11.0-rc.5-rpm-ostree-timeout.yaml, blocked-edges/4.11.0-rc.6-rpm-ostree-timeout.yaml, blocked-edges/4.11.0-rc.7-rpm-ostree-timeout.yaml, blocked-edges/4.11.0-rpm-ostree-timeout.yaml
The KCS is pretty and mutable.  The bug comment is ugly and frozen.
```console
$ sed -i 's|bugzilla.redhat.com/show_bug.cgi?id=2111817#c22|https://access.redhat.com/solutions/6972394|' $(git grep -l '2111817#c22')
```
=> blocked-edges/4.11.0*: Link RPMOSTreeTimeout KCS

blocked-edges/4.11.2-PodmanTermStorageCorruption.yaml
1. [This][1] landed after 4.11.1 and was shipped in 4.11.2, adding a 20s `timeout` to `baremetalRuntimeCfgImage` `podman run ...` calls.
2. The `baremetalRuntimeCfgImage` stuff gets enabled for [a number of infrastructure providers][2].
3. A Podman bug in TERM handling means that timeout TERMs can result in corrupted storage: containers/storage#1136.
4. That corruption bubbles up with errors like:
Can't read link "/var/lib/containers/storage/overlay/..." because it does not exist. A storage corruption might have occurred
or maybe:
Image ... exists in local storage but may be corrupted (remove the image to resolve the issue): layer not known
or maybe both, [OCPBUGS-631][4].
5. 4.11.3 and later [fix the regression][4] by separating the possibly-slow image pull from the container run.
[1]: …
=> blocked-edges/4.11.2-PodmanTermStorageCorruption: Declare regression

blocked-edges/4.11.0-fc.0-stale-insights-run-level-label.yaml, blocked-edges/4.11.0-fc.3-stale-insights-run-level-label.yaml, blocked-edges/4.11.0-rc.0-stale-insights-run-level-label.yaml, blocked-edges/4.11.0-rc.1-stale-insights-run-level-label.yaml, blocked-edges/4.11.0-rc.2-stale-insights-run-level-label.yaml, blocked-edges/4.11.0-rc.3-stale-insights-run-level-label.yaml, blocked-edges/4.11.0-rc.4-stale-insights-run-level-label.yaml, blocked-edges/4.11.0-rc.5-stale-insights-run-level-label.yaml, blocked-edges/4.11.0-rc.6-stale-insights-run-level-label.yaml, blocked-edges/4.11.0-rc.7-stale-insights-run-level-label.yaml, blocked-edges/4.11.0-stale-insights-run-level-label.yaml, blocked-edges/4.11.1-stale-insights-run-level-label.yaml, blocked-edges/4.11.2-stale-insights-run-level-label.yaml, blocked-edges/4.11.3-stale-insights-run-level-label.yaml
Generated by writing `blocked-edges/4.11.0-stale-insights-run-level-label.yaml` , and then copying it out to the other 4.11 releases with:
```console
$ yaml2json <channels/candidate-4.11.yaml | jq -r '.versions[]' | grep '^4[.]11[.]' | grep -v '^4[.]11[.]0$' | while read V; do sed "s/4[.]11[.]0/${V}/g" blocked-edges/4.11.0-stale-insights-run-level-label.yaml > "blocked-edges/${V}-stale-insights-run-level-label.yaml"; done
```
=> blocked-edges/4.11.*: Declare StaleInsightsRunLevelLabel risk

blocked-edges/4.11.4-stale-insights-run-level-label.yaml
Extend b76516a207 (#2457) to 4.11.4, because the fix just landed in the development branch [1] and has yet to be backported to 4.11.z.
```console
$ V=4.11.4; sed "s/4[.]11[.]0/${V}/g" blocked-edges/4.11.0-stale-insights-run-level-label.yaml > "blocked-edges/${V}-stale-insights-run-level-label.yaml"
```
[1]: https://github.com/openshift/insights-operator/pull/672
=> blocked-edges/4.11.4-stale-insights-run-level-label: 4.11.4 isn't fixed

internal-channels/candidate.yaml
It was rerolled with similar metadata as 4.7.59:
```console
$ diff -u0 <(oc adm release info -o json quay.io/openshift-release-dev/ocp-release:4.7.58-x86_64 | grep -v created) <(oc adm release info -o json quay.io/openshift-release-dev/ocp-release:4.7.59-x86_64 | grep -v created)
--- /dev/fd/63  2022-09-14 10:35:40.915796255 -0700
+++ /dev/fd/62  2022-09-14 10:35:40.918796254 -0700
@@ -2,3 +2,3 @@
-  "image": "quay.io/openshift-release-dev/ocp-release:4.7.58-x86_64",
-  "digest": "sha256:dee33ede78272450743ede855e1a2f1611500e388be212ec0cde68d45b801fa7",
-  "contentDigest": "sha256:dee33ede78272450743ede855e1a2f1611500e388be212ec0cde68d45b801fa7",
+  "image": "quay.io/openshift-release-dev/ocp-release:4.7.59-x86_64",
+  "digest": "sha256:5db88217bbc9ee12d95f3c740eb0217668628e2f1f61b9cb2afdd …
```
=> internal-channels/candidate: Tombstone 4.7.58

blocked-edges/4.11.6-ovn-namespace
A regression introduced in 4.11.6 may lead to OVN control plane failure and workload disruption.
=> blocked-edges/4.11.6: Declare OVNNetworkPolicyLongName risk

hack/util.py, hack/validate-blocked-edges.py
So we catch issues in presubmit CI, to avoid needing post-merge fixups like 4d23a343a9 (#2553).  I've set things up so that we can add `.md` or similar to the allow-list in the future, if we wanted to allow `blocked-edges/README.md`, etc.
=> hack/validate-blocked-edges: Require '.yaml' suffix

blocked-edges/4.11.7-ovn-namespace.yaml
Generated by rewording the 4.11.6 `message` to be less specific about when the regression was introduced (and instead just point out that the particular target version being considered is vulnerable).  An then:
```console
$ sed 's/4[.]11[.]6/4.11.7/g' blocked-edges/4.11.6-ovn-namespace.yaml >blocked-edges/4.11.7-ovn-namespace.yaml
```
[OCPBUGS-1750][1] is tracking the 4.11.z fix.
[1]: https://issues.redhat.com//browse/OCPBUGS-1750
=> blocked-edges/4.11.7-ovn-namespace: 4.11.7 does not fix the regression

hack/stabilization-changes.py
So we don't have to do things like 38394e3f4e (#2497) manually.  Personally, whether a conditional update feels connected or disconnected is a bit murky. The `StaleInsightsRunLevelLabel` risk feels connected, because it's a small slice of the relevant fleet, and because it is very easy to manually mitigate (just remove the old label to make your cluster invulnerable).  `RPMOSTreeTimeout` feels disconnected, because it's an `Always` (so the entire relevant fleet), and it's difficult to mitigate either prophylactically or post-update if you get bit.  So there's some risk with this change that folks get an update recommendation to a 4.(y-1).z that doesn't have a workable-for-them path to their desired 4.y.  But at least there will be a conditional risk there explaining what we're concerend …
=> hack/stabilization-changes: Treat conditional edges as connected

blocked-edges/4.11.8-ovn-namespace.yaml
Like 2d6b5fb45f (#2557), but for 4.11.8.  Generated with:
```console
$ sed 's/4[.]11[.]6/4.11.8/g' blocked-edges/4.11.6-ovn-namespace.yaml >blocked-edges/4.11.8-ovn-namespace.yaml
```
=> blocked-edges/4.11.8-ovn-namespace: 4.11.8 does not fix the regression

blocked-edges/4.11.9-ovn-namespace.yaml
Like 2d6b5fb45f (#2557), and a82acb43be (#2599), but for 4.11.9.  Generated with:
```console
$ sed 's/4[.]11[.]6/4.11.9/g' blocked-edges/4.11.6-ovn-namespace.yaml >blocked-edges/4.11.9-ovn-namespace.yaml
```
[OCPBUGS-1750][1] is `MODIFIED` with happy noises from QE, so odds are good that 4.11.10 will have the fix, but we'll see once it's built.
[1]: https://issues.redhat.com/browse/OCPBUGS-1750
=> blocked-edges/4.11.9-ovn-namespace: 4.11.9 does not fix the regression

build-suggestions/4.12.yaml
[OCPBUGS-1939][1] is going out with [4.11.9][2], and we want to raise the floor for:
1. Running 4.10.
2. Pause compute.
3. Update to 4.11.9 with the fix.
4. Machine-config controller with the fix creates a MachineConfig to lock in the 4.11-and-earlier default behavior.  Paused compute means that this doesn't get rolled out to compute nodes yet, but that's fine, they're on 4.10 still, with the 4.11-and-earlier default.
5. Control plane (and any other unpaused compute) updates to pick up the new rendered MachineConfig, but effectively a no-op, because their 4.11 CRI-O still has the 4.11-and-earlier default too.
6. Update to 4.12.
7. Unpause compute.
8. Compute picks up 4.12 CRI-O and the new MachineConfig at the same time, so it will never use the new-in-4.12 default (until the user deletes …
=> build-suggestions/4.12: Raise minor_min to 4.11.9

build-suggestions/4.13.yaml, channels/candidate-4.13.yaml, hack/release-open.sh
Like 2d428f86bc (#2480), but for 4.13.  Run well before feature-freeze, because for 4.13 we plan on cutting sprintly `4.13.0-ec.#` and including them in candidate-4.13.  Generated with:
```console
$ hack/release-open.sh 4.13
$ git add build-suggestions/4.13.yaml channels/*4.13.yaml
```
=> *: Prepare for 4.13 development

blocked-edges/4.11.0-arm64-seccomp-error-524.yaml, blocked-edges/4.11.0-fc.0-arm64-seccomp-error-524.yaml, blocked-edges/4.11.0-fc.3-arm64-seccomp-error-524.yaml, blocked-edges/4.11.0-rc.0-arm64-seccomp-error-524.yaml, blocked-edges/4.11.0-rc.1-arm64-seccomp-error-524.yaml, blocked-edges/4.11.0-rc.2-arm64-seccomp-error-524.yaml, blocked-edges/4.11.0-rc.3-arm64-seccomp-error-524.yaml, blocked-edges/4.11.0-rc.4-arm64-seccomp-error-524.yaml, blocked-edges/4.11.0-rc.5-arm64-seccomp-error-524.yaml, blocked-edges/4.11.0-rc.6-arm64-seccomp-error-524.yaml, blocked-edges/4.11.0-rc.7-arm64-seccomp-error-524.yaml, blocked-edges/4.11.1-arm64-seccomp-error-524.yaml, blocked-edges/4.11.10-arm64-seccomp-error-524.yaml, blocked-edges/4.11.11-arm64-seccomp-error-524.yaml, blocked-edges/4.11.12-arm64-seccomp-error-524.yaml, blocked-edges/4.11.13-arm64-seccomp-error-524.yaml, blocked-edges/4.11.14-arm64-seccomp-error-524.yaml, blocked-edges/4.11.2-arm64-seccomp-error-524.yaml, blocked-edges/4.11.3-arm64-seccomp-error-524.yaml, blocked-edges/4.11.4-arm64-seccomp-error-524.yaml, blocked-edges/4.11.5-arm64-seccomp-error-524.yaml, blocked-edges/4.11.6-arm64-seccomp-error-524.yaml, blocked-edges/4.11.7-arm64-seccomp-error-524.yaml, blocked-edges/4.11.8-arm64-seccomp-error-524.yaml, blocked-edges/4.11.9-arm64-seccomp-error-524.yaml
Although as I point out in [RUN-1668](https://issues.redhat.com//browse/RUN-1668), [rhbz#2140163][2] makes it sound like the risk might be 4.10-to-4.11, not 4.11-to-4.12, so we may need to refine this later.
[2]: https://bugzilla.redhat.com/show_bug.cgi?id=2140163#c2
=> blocked-edges/4.11.*: Declare ARM64SecCompError524 regression

build-suggestions/4.12.yaml
As https://issues.redhat.com/browse/OCPBUGS-2293 and OCPBUGS-2050 is shipped in 4.11.12
=> Raising the minor_min for 4.11 to 4.12 upgrades

blocked-edges/4.11.16-arm64-seccomp-error-524.yaml
[OCPBUGS-2637][1] is tracking the fix, and it's still `New`.  Generated with:
```console
$ V=4.11.16; sed "s/4[.]11[.]0/${V}/g" blocked-edges/4.11.0-arm64-seccomp-error-524.yaml > "blocked-edges/${V}-arm64-seccomp-error-524.yaml"
```
[1]: https://issues.redhat.com/browse/OCPBUGS-2637
=> blocked-edges/4.11.16-arm64-seccomp-error-524: 4.11.16 does not contain a fix

blocked-edges/4.11.17-arm64-seccomp-error-524.yaml
[OCPBUGS-2637](https://issues.redhat.com/browse/OCPBUGS-2637) is tracking the fix, and it's still New.
```console
$ V=4.11.17; sed "s/4[.]11[.]0/${V}/g" blocked-edges/4.11.0-arm64-seccomp-error-524.yaml > "blocked-edges/${V}-arm64-seccomp-error-524.yaml"
```
=> blocked-edges/4.11.17-arm64-seccomp-error-524: 4.11.17 does not contain a fix

blocked-edges/4.11.18-arm64-seccomp-error-524.yaml
[OCPBUGS-2637](https://issues.redhat.com/browse/OCPBUGS-2637) is tracking the fix, and it's still `New`.
```console
$ V=4.11.18; sed "s/4[.]11[.]0/${V}/g" blocked-edges/4.11.0-arm64-seccomp-error-524.yaml > "blocked-edges/${V}-arm64-seccomp-error-524.yaml"
```
=> blocked-edges/4.11.18-arm64-seccomp-error-524: 4.11.18 does not contain a fix

blocked-edges/4.11.19-arm64-seccomp-error-524.yaml
[OCPBUGS-2637](https://issues.redhat.com/browse/OCPBUGS-2637) is tracking the fix, and it's still `Assigned`:
```console
$ V=4.11.19; sed "s/4[.]11[.]0/${V}/g" blocked-edges/4.11.0-arm64-seccomp-error-524.yaml > "blocked-edges/${V}-arm64-seccomp-error-524.yaml"
```
=> blocked-edges/4.11.19-arm64-seccomp-error-524: 4.11.19 does not contain a fix

blocked-edges/4.11.20-arm64-seccomp-error-524.yaml
[OCPBUGS-2637](https://issues.redhat.com/browse/OCPBUGS-2637) is tracking the fix, and it's still `Assigned`:
```console
$ V=4.11.20; sed "s/4[.]11[.]0/${V}/g" blocked-edges/4.11.0-arm64-seccomp-error-524.yaml > "blocked-edges/${V}-arm64-seccomp-error-524.yaml"
```
The fix is [starting to percolate into RHEL 9][2], but apparently not yet [back to RHEL 8.6 releases][3].
[2]: https://bugzilla.redhat.com/show_bug.cgi?id=2140163#c28
[3]: https://bugzilla.redhat.com/show_bug.cgi?id=2152139
=> blocked-edges/4.11.20-arm64-seccomp-error-524: 4.11.20 does not contain a fix

blocked-edges/4.12.0-rc.0-AWSOldBootImage.yaml, blocked-edges/4.12.0-rc.1-AWSOldBootImage.yaml, blocked-edges/4.12.0-rc.2-AWSOldBootImage.yaml, blocked-edges/4.12.0-rc.3-AWSOldBootImage.yaml, blocked-edges/4.12.0-rc.4-AWSOldBootImage.yaml, blocked-edges/4.12.0-rc.5-AWSOldBootImage.yaml
This one is sticky, because we don't have PromQL access to boot-image age, so we cannot automatically distinguish between "born in 4.(<=2) and still uses the old boot images" and "born in 4.(<=2), but has subsequently updated boot images".  And because of a cluster-version operator bug, we don't necessarily have access to the cluster's born-in release anyway.  The CVO bug fix went back via:
* [4.11.0](https://bugzilla.redhat.com/show_bug.cgi?id=2097067#c12)
* [4.10.24](https://bugzilla.redhat.com/show_bug.cgi?id=2108292#c6)
* [4.9.45](https://bugzilla.redhat.com/show_bug.cgi?id=2108619#c6)
* [4.8.47](https://bugzilla.redhat.com/show_bug.cgi?id=2109962#c6)
* [4.7.59](https://bugzilla.redhat.com/show_bug.cgi?id=2117347#c8)
* [4.6.61](https://bugzilla.redhat.com/show_bug.cgi?id=2118489#c6) …
=> COS-1942: blocked-edges/4.12.*: Declare AWSOldBootImages

blocked-edges/4.11.21-arm64-seccomp-error-524.yaml
As it does not contain the fix for https://issues.redhat.com/browse/RUN-1668
[1] is tracking the fix, and it's still Assigned:
The fix is starting to percolate into RHEL 9 [2], but apparently not yet back to RHEL 8.6 releases [3].
[1] https://issues.redhat.com/browse/OCPBUGS-2637 
[2] https://bugzilla.redhat.com/show_bug.cgi?id=2140163#c28 
[3] https://bugzilla.redhat.com/show_bug.cgi?id=2152139
=> Extending the conditional update to 4.11.21

blocked-edges/4.11.22-arm64-seccomp-error-524.yaml
[OCPBUGS-2637](https://issues.redhat.com/browse/OCPBUGS-2637) is tracking the fix, and it's still `Assigned`.  Generated with:
```console
$ V=4.11.22; sed "s/4[.]11[.]0/${V}/g" blocked-edges/4.11.0-arm64-seccomp-error-524.yaml > "blocked-edges/${V}-arm64-seccomp-error-524.yaml"
```
The fix is [starting to percolate into RHEL 9][2], but apparently [not yet back to RHEL 8.6 releases][3].
[2]: https://bugzilla.redhat.com/show_bug.cgi?id=2140163#c28
[3]: https://bugzilla.redhat.com/show_bug.cgi?id=2152139
=> blocked-edges/4.11.22-arm64-seccomp-error-524: 4.11.22 does not contain a fix

blocked-edges/4.12.0-rc.7-AWSOldBootImage.yaml
The fix landed in 4.12 after rc.7 was cut
https://issues.redhat.com/browse/OCPBUGS-5384
=> blocked-edges/4.12.0-rc.7-AWSOldBootImage: rc.7 does not contain a fix

channels/eus-4.8.yaml, channels/stable-4.8.yaml
This minimizes the impact of 4.8.56 and 4.8.57 shipping before an upgrade path to 4.9 is available. This delay is on top of the normal P1W delay for the internal channel promotion from fast to stable. There's no need to adjust delays into 4.9 channels because the existing upgradability checks will ensure that 4.8.z doesn't go into those channels before an upgrade path is available.
=> Add an additional 1w delay when adding 4.8.z to stable-4.8 and eus-4.8

blocked-edges/4.11.25-arm64-seccomp-error-524.yaml
[OCPBUGS-2637](https://issues.redhat.com/browse/OCPBUGS-2637) is tracking the fix, and it's still Assigned:
```console
$ V=4.11.25; sed "s/4[.]11[.]0/${V}/g" blocked-edges/4.11.0-arm64-seccomp-error-524.yaml > "blocked-edges/${V}-arm64-seccomp-error-524.yaml"
````
The fix is [starting to percolate into RHEL 9][2], but apparently [not yet back to RHEL 8.6 releases][3].
[2]: https://bugzilla.redhat.com/show_bug.cgi?id=2140163#c28
[3]: https://bugzilla.redhat.com/show_bug.cgi?id=2152139
=> blocked-edges/4.11.25-arm64-seccomp-error-524: 4.11.25 does not contain a fix

hack/stabilization-changes.py
Fix a bug where we'd treated a release as connected when it was linked to the target 4.y via conditional updates in the candidate-4.y channel.  With this commit, conditional updates only increase connectivity when the releases are (or will be after promotion) in the target channel.
For example:
* 4.11.24 is in 'fast' and 'candidate-4.12'.
* 4.12.1 is in 'candidate-4.12', with a conditional update from 4.11.24.
* Considering 4.11.24 for promotion into 'fast-4.12':
* The outgoing logic said "candidate-4.12 has a conditional update to 4.12.1, which is in 4.12, so promote!"
* The incoming logic says, "candidate-4.12 has a conditional update to 4.12.1, but 4.12.1 is not in fast-4.12, so don't promote yet.
=> hack/stabilization-changes: Conditional edges vs. connectivity

build-suggestions/4.13.yaml
With 4.12 generally available, we no longer need to recomment 4.12.0-pre-release to 4.13.0-pre-release updates.  By not recommending them, we reduce the recommended updates to transitions that users are more likely to be interested in.
Like 7b5f37a767 (#3075), but for the 4.13 build suggestions.
=> build-suggestions/4.13: Raise minor_min to 4.12.0

blocked-edges/4.11.26-arm64-seccomp-error-524.yaml
[OCPBUGS-2637](https://issues.redhat.com/browse/OCPBUGS-2637) is tracking the fix, and it's still Assigned:
```console
$ V=4.11.26; sed "s/4[.]11[.]0/${V}/g" blocked-edges/4.11.0-arm64-seccomp-error-524.yaml > "blocked-edges/${V}-arm64-seccomp-error-524.yaml"
```
The fix is starting to percolate [into RHEL 9][2], but apparently [not yet back to RHEL 8.6 releases][3].
[2]: https://bugzilla.redhat.com/show_bug.cgi?id=2140163#c28
[3]: https://bugzilla.redhat.com/show_bug.cgi?id=2152139
=> blocked-edges/4.11.26-arm64-seccomp-error-524: 4.11.26 does not contain a fix

README.md, blocked-edges/4.11.23-duplicate-release.yaml, blocked-edges/4.11.25-MachineConfigRenderingChurn.yaml, hack/stabilization-changes.py
With this change, the script will complain like:
```
* Recommend waiting to promote 4.11.24 to fast-4.12; it was promoted the feeder fast by f5a8c3b3ef (Merge pull request #3024 from openshift-ota-bot/promote-4.11.24-to-fast, 2023-01-19, 4 days, 3:10:10.409875)  DuplicateRelease affects 4.11.23.  Either declare a fix version or extend the risk to 4.11.24.  No paths from 4.11.24 to 4.12 in https://api.openshift.com/api/upgrades_info/v1/graph?channel=candidate-4.12&arch=amd64
```
as it wonders if `DuplicateRelease` (which affects updates into 4.11.23) affects 4.11.24 or not.  Graph administrators can either:
* declare `fixedIn` (like I'm doing in this commit) or
* extend the risk to the new release (like we'd done in d44b7a4710 (#3032) and similar.
But the guard should keep us from …
=> OTA-858: hack/stabilization-changes: Add risk-extension guards with fixedIn

blocked-edges/4.12.1-ConsoleAvailableUpdatesNull.yaml
From https://amd64.ocp.releases.ci.openshift.org/releasestream/4-stable/release/4.12.2:
> OCPBUGS-6678: fix run-time error on Cluster Settings when available...
=> `ConsoleAvailableUpdatesNull`: OCPBUGS-6678 is fixed in 4.12.2

hack/stabilization-changes.py
0a4013aed4 (#3064) flipped the `source`/`target` `from`/`to` sense when porting this logic from the unconditional-edge block a few lines up.  Fix that, so:
```console
$ hack/show-edges.py --cincinnati https://api.openshift.com/api/upgrades_info/graph --root-version 4.11.24 candidate-4.12
4.11.24 -> 4.11.25
4.11.24 -(blocked: ConsoleAvailableUpdatesNull)-> 4.12.1
4.11.25 -(blocked: ConsoleAvailableUpdatesNull)-> 4.12.1
```
will result in:
```console
$ hack/stabilization-changes.py
...
* channels/fast-4.12: Promote 4.11.24. It was promoted to the feeder fast by f5a8c3b3ef (Merge pull request #3024 from openshift-ota-bot/promote-4.11.24-to-fast, 2023-01-19) 11 days, 15:25:56.493972 ago. data://no-token-so-no-pull
* channels/fast-4.12: Promote 4.11.25. It was promoted to the feeder fast by …
```
=> hack/stabilization-changes: Conditional edges vs. connectivity v2

blocked-edges/4.13.0-ec.2-ConsoleAvailableUpdatesNull.yaml
[OCPBUGS-6053](https://issues.redhat.com/browse/OCPBUGS-6053)'s openshift/console#12450 is  included in [the new release][3].
[3]: https://multi.ocp.releases.ci.openshift.org/releasestream/4-dev-preview-multi/release/4.13.0-ec.3
=> blocked-edges: ConsoleAvailableUpdatesNull fixed in 4.13.0-ec.3

hack/stabilization-changes.py
Avoid redundancies like:
```
Cincinnati stabilization:
* FAILED ARM64SecCompError524 affects 4.11.26.  Either declare a fix version or extend the risk to 4.11.27.
* FAILED ARM64SecCompError524 affects 4.11.26.  Either declare a fix version or extend the risk to 4.11.27.
* FAILED ARM64SecCompError524 affects 4.11.26.  Either declare a fix version or extend the risk to 4.11.27.
* channels/fast-4.10: Promote 4.10.51. It was promoted...
```
when a release fails promotion into several channels for the same reason (and we don't currently include the target channel in the notification message, because it doesn't seem helpful).
With this change, we'll only get each message once.  And we'll preserve the previous ordering, so specific channels are still grouped together, regardless of the message …
=> hack/stabilization-changes: Dedup notifications

build-suggestions/4.13.yaml
Tracking bug is https://issues.redhat.com/browse/OCPBUGS-7275
=> Raise minimum for upgrades into 4.13 to 4.12.5 to pick up rpmdb compat

build-suggestions/4.14.yaml, channels/candidate-4.14.yaml
Like 3eb8e55eb2 (#2758). but for 4.14.  Run well before feature-freeze, because for 4.14 we plan on cutting sprintly 4.14.0-ec.# and including them in `candidate-4.14`.  Generated with:
```console
$ hack/release-open.sh 4.14
$ git add build-suggestions/4.14.yaml channels/*4.14.yaml
```
=> *: Prepare for 4.14 development

blocked-edges/4.11.26-leaked-machineconfig.yaml, blocked-edges/4.11.27-leaked-machineconfig.yaml, blocked-edges/4.11.28-leaked-machineconfig.yaml, blocked-edges/4.11.29-leaked-machineconfig.yaml, blocked-edges/4.11.30-leaked-machineconfig.yaml, blocked-edges/4.11.31-leaked-machineconfig.yaml, blocked-edges/4.12.2-leaked-machineconfig.yaml, blocked-edges/4.12.3-leaked-machineconfig.yaml, blocked-edges/4.12.4-leaked-machineconfig.yaml, blocked-edges/4.12.5-leaked-machineconfig.yaml, blocked-edges/4.12.6-leaked-machineconfig.yaml, blocked-edges/4.12.7-leaked-machineconfig.yaml, blocked-edges/4.13.0-ec.3-leaked-machineconfig.yaml, blocked-edges/4.13.0-ec.4-leaked-machineconfig.yaml
According to [OCPNODE-1502](https://issues.redhat.com//browse/OCPNODE-1502):
> Any 4.y cluster has kubeletconfig objects upgrades to cluster 4.11.0-fc.0+
> Any 4.y cluster has containerruntimeconfig objects upgrades to cluster 4.12.0-ec.1+
-> These upgrades could result in orphaning a machineconfig resource
> **Is this a regression?**
> Yes, 4.10.52+, 4.11.26+, 4.12.2+, and 4.13.0-ec.3 landed code that
> pivoted the machine-config components treatment of leaked MachineConfig
> from "ignore" to "block on".
-> Upgrades to these versions could wedge MCO when it encounters an
orphaned machineconfig resource.
Hence, upgrades to 4.10 should not be affected by `LeakedMachineConfigBlocksMCO`, because it should never have an orphaned resource. Upgrades to newer versions are only affected if they …
=> OCPNODE-1502: Declare `LeakedMachineConfigBlocksMCO` on 4.11.26+ | 4.12.2+ | 4.13.0-ec.3+

blocked-edges/4.11.31-AWSOldBootImageLackAfterburn.yaml
[OCPBUGS-7559](https://issues.redhat.com/browse/OCPBUGS-7559) is still POST for 4.14, and once it gets fixed there, it will need to go through the backport process before we get a fixed 4.11.z.
=> blocked-edges/4.11.31: Extend AWSOldBootImageLackAfterburn

blocked-edges/4.13.0-ec.3-leaked-machineconfig.yaml, blocked-edges/4.13.0-ec.4-leaked-machineconfig.yaml
Following up on 472ed90abc (#3243).
=> blocked-edges/4.13.0-ec.*-leaked-machineconfig: Drop whitespace from 'ContainerRuntimeConfi  g'

blocked-edges/4.12.0-OldBootImagesPodmanMissingAuthFlag.yaml, blocked-edges/4.12.0-rc.8-OldBootImagesPodmanMissingAuthFlag.yaml, blocked-edges/4.12.1-OldBootImagesPodmanMissingAuthFlag.yaml, blocked-edges/4.12.2-OldBootImagesPodmanMissingAuthFlag.yaml, blocked-edges/4.12.3-OldBootImagesPodmanMissingAuthFlag.yaml, blocked-edges/4.12.4-OldBootImagesPodmanMissingAuthFlag.yaml, blocked-edges/4.12.5-OldBootImagesPodmanMissingAuthFlag.yaml, blocked-edges/4.12.6-OldBootImagesPodmanMissingAuthFlag.yaml, blocked-edges/4.12.7-OldBootImagesPodmanMissingAuthFlag.yaml
Like 034fa0182a (blocked-edges/4.12.*: Declare AWSOldBootImages,
2022-12-14, #2909) and 957626a4ec , this conditional risk is sticky,
because we don't have PromQL access to boot-image age, so we cannot automatically distinguish
between "born in 4.1 and still uses the old boot images" and "born
in 4.1, but has subsequently updated boot images".  And because of
a cluster-version operator bug, we don't necessarily have access to
the cluster's born-in release anyway.
The CVO bug fix went back via:
* 4.11.0 https://bugzilla.redhat.com/show_bug.cgi?id=2097067#c12
* 4.10.24 https://bugzilla.redhat.com/show_bug.cgi?id=2108292#c6
* 4.9.45 https://bugzilla.redhat.com/show_bug.cgi?id=2108619#c6
* 4.8.47 https://bugzilla.redhat.com/show_bug.cgi?id=2109962#c6
* 4.7.59 …
=> Adding conditional update "PodmanMissingAuthFlag" for 4.11.* to 4.12.*

build-suggestions/4.13.yaml
As the admin_ack[1] for updating to 4.13 will be available with 4.12.8 version
[1] https://issues.redhat.com//browse/OCPBUGS-8304
=> Updating the minor_min for 4.13 to 4.12.8

blocked-edges/4.12.7-leaked-machineconfig.yaml
[OCPBUGS-8261](https://issues.redhat.com/browse/OCPBUGS-8261) is in [4.12.8][2].
[2]: https://multi.ocp.releases.ci.openshift.org/releasestream/4-stable-multi/release/4.12.8
=> blocked-edges/4.12.7-leaked-machineconfig: Fixed in 4.12.8

blocked-edges/4.12.8-OldBootImagesPodmanMissingAuthFlag.yaml
[OCPBUGS-9969](https://issues.redhat.com/browse/OCPBUGS-9969) is tracking the fix, and it's still Post for 4.14.0.
=> blocked-edges/4.12.8-OldBootImagesPodmanMissingAuthFlag: 4.12.8 does not contain a fix

blocked-edges/4.11.32-AWSOldBootImageLackAfterburn.yaml, blocked-edges/4.11.32-leaked-machineconfig.yaml
[OCPBUGS-10425](https://issues.redhat.com/browse/OCPBUGS-10425) is Post for 4.11.z for `AWSOldBootImageLackAfterburn`.  [OCPBUGS-8260](https://issues.redhat.com/browse/OCPBUGS-8260) in ON_QA for 4.11.z for `LeakedMachineConfigBlocksMCO`, but [it landed after 4.11.32][3].
[3]: https://amd64.ocp.releases.ci.openshift.org/releasestream/4.11.0-0.nightly/release/4.11.0-0.nightly-2023-03-17-003301?from=4.11.32
=> blocked-edges/4.11.32-*: AWSOldBootImageLackAfterburn and LeakedMachineConfigBlocksMCO are unfixed

blocked-edges/4.13.0-ec.4-leaked-machineconfig.yaml
[OCPBUGS-7719](https://issues.redhat.com/browse/OCPBUGS-7719) is in [4.13.0-rc.0][2].
[2]: https://multi.ocp.releases.ci.openshift.org/releasestream/4-stable-multi/release/4.13.0-rc.0?from=4.13.0-ec.4
=> blocked-edges/4.13.0-ec.4-leaked-machineconfig: Fixed in 4.13.0-rc.0

blocked-edges/4.13.0-ec.1-StrictPodSecurityViolation.yaml, blocked-edges/4.13.0-ec.2-StrictPodSecurityViolation.yaml, blocked-edges/4.13.0-ec.3-StrictPodSecurityViolation.yaml, blocked-edges/4.13.0-ec.4-StrictPodSecurityViolation.yaml, blocked-edges/4.13.0-rc.0-StrictPodSecurityViolation.yaml
Generated by writing the rc.0 declaration by hand, and then copying out to other 4.13 prereleases with:
```console
$ curl -s 'https://api.openshift.com/api/upgrades_info/graph?channel=candidate-4.13' | jq -r '.nodes[].version' | grep '^4[.]13[.]' | grep -v '^4[.]13[.]0-rc[.]0$' | while read V; do sed "s/4[.]13[.]0-rc[.]0/${V}/g" blocked-edges/4.13.0-rc.0-StrictPodSecurityViolation.yaml > "blocked-edges/${V}-StrictPodSecurityViolation.yaml"; done
```
=> AUTH-351: blocked-edges/4.13.0-*: Declare StrictPodSecurityViolation

blocked-edges/4.11.32-AWSOldBootImageLackAfterburn.yaml, blocked-edges/4.11.32-leaked-machineconfig.yaml
[4.11.33][1] includes both [OCPBUGS-10425](https://issues.redhat.com/browse/OCPBUGS-10425) and [OCPBUGS-8260](https://issues.redhat.com/browse/OCPBUGS-8260).
[1]: https://amd64.ocp.releases.ci.openshift.org/releasestream/4-stable/release/4.11.33
=> blocked-edges/4.11.32-*: 4.11.33 fixes AWSOldBootImageLackAfterburn and LeakedMachineConfigBlocksMCO

blocked-edges/4.12.8-OldBootImagesPodmanMissingAuthFlag.yaml
[4.12.9][1] includes [OCPBUGS-10505](https://issues.redhat.com/browse/OCPBUGS-10505).
[1]: https://multi.ocp.releases.ci.openshift.org/releasestream/4-stable-multi/release/4.12.9
=> blocked-edges/4.12.8-OldBootImagesPodmanMissingAuthFlag: Fixed in 4.12.9

blocked-edges/4.12.7-OldBootImagesPodmanMissingAuthFlag.yaml
We carry the `fixedIn` in the 4.12.8 file already since https://github.com/openshift/cincinnati-graph-data/pull/3313, but 4.12.8 is not in stable yet:
```
Recommend waiting to promote 4.12.8 to stable; it was promoted the feeder fast by 480ee3c1d7 (Merge pull request #3296 from openshift-ota-bot/promote-4.12.8-to-fast, 2023-03-21, 5 days, 17:05:39.155584)
```
So the stabilization bot considers 4.12.9 for stable and errors out because the version with `fixedIn` is not in the same channel yet:
```
FAILED OldBootImagesPodmanMissingAuthFlag affects 4.12.7.  Either declare a fix version or extend the risk to 4.12.9.
```
=> blocked-edges/4.12.7-OldBootImagesPodmanMissingAuthFlag: Fixed in 4.12.9

blocked-edges/4.13.0-rc.0-StrictPodSecurityViolation.yaml
rc.2 is the next release after rc.0; not sure why we burned rc.1, but it doesn't matter.  [OCPBUGS-8710](https://issues.redhat.com/browse/OCPBUGS-8710) is verified and [landed in rc.2][2].
[2]: https://multi.ocp.releases.ci.openshift.org/releasestream/4-stable-multi/release/4.13.0-rc.2
=> blocked-edges/4.13.0-rc.0-StrictPodSecurityViolation: Fixed in 4.13.0-rc.2

blocked-edges/4.12.0-OldBootImagesPodmanMissingAuthFlag.yaml, blocked-edges/4.12.0-rc.8-OldBootImagesPodmanMissingAuthFlag.yaml, blocked-edges/4.12.1-OldBootImagesPodmanMissingAuthFlag.yaml, blocked-edges/4.12.2-OldBootImagesPodmanMissingAuthFlag.yaml, blocked-edges/4.12.3-OldBootImagesPodmanMissingAuthFlag.yaml, blocked-edges/4.12.4-OldBootImagesPodmanMissingAuthFlag.yaml, blocked-edges/4.12.5-OldBootImagesPodmanMissingAuthFlag.yaml, blocked-edges/4.12.6-OldBootImagesPodmanMissingAuthFlag.yaml, blocked-edges/4.12.7-OldBootImagesPodmanMissingAuthFlag.yaml, blocked-edges/4.12.8-OldBootImagesPodmanMissingAuthFlag.yaml, blocked-edges/4.7.4-vsphere-hw-17-cross-node-networking.yaml, blocked-edges/4.7.4-zz-vsphere-hostnames-changing.yaml
The `cluster_infrastructure_provider` metric has a zero value when its
type is `None`, so in that case we need to check the metric's presence,
rather than value.
Change prepared with (fish shell, sorry):
```
$ sed -r -i -e 's|(cluster_infrastructure_provider\{.*None.*\})|group(\1)|g' blocked-edges/*.yaml
$ git add blocked-edges
$ for file in (git diff --name-only --staged)
sed -r -i -e 's|0 \* cluster_infrastructure_provider|0 * group(cluster_infrastructure_provider)|g' $file
end
```
I have tested the new `OldBootImagesPodmanMissingAuthFlag` PromQL on appci which is a matching AWS cluster, and it works. Hideshi tested the same change on a baremetal cluster (with `"type":"None"`) and it also worked for him.
/cc @wking @LalatenduMohanty
=> blocked-edges: handle cluster_infrastructure_provider zero values

blocked-edges/4.12.12-PatchesOlderRelease.yaml
And also 4.11.35, which was built the same week as 4.12.11 and has a newer RHCOS ([411.86.202304042133-0][1]) and possibly other components compared to 4.12.10 and its almost-clone 4.12.12
([412.86.202303241612-0][2]).
Testing with both #3447 and this change and a local patch extending `candidate-4.12`:
```console
$ git --no-pager diff -U1
diff --git a/channels/candidate-4.12.yaml b/channels/candidate-4.12.yaml
index c2f5e6cd..c97923ea 100644
--- a/channels/candidate-4.12.yaml
+++ b/channels/candidate-4.12.yaml
@@ -72 +72,3 @@ versions:
- 4.12.11
+- 4.11.36
+- 4.12.12
```
Checking for the effect we want:
```console
$ hack/show-edges.py --root-version 4.11.34 candidate-4.12
WARNING: walked all tag pages, but did not find releases for: 4.12.12
4.11.34 -> 4.11.35
4.11.34 -> 4.11.36
4.11.34 …
```
=> blocked-edges/4.12.12-PatchesOlderRelease: Explain intentional regressions vs. 4.12.11

blocked-edges/4.11.36-PatchesOlderRelease.yaml
Tested with a local tweak:
```console
$ git --no-pager log --oneline -1
0ec85ddf (HEAD -> 4.11.36-pins-4.11.34, wking/4.11.36-pins-4.11.34) blocked-edges/4.11.36-PatchesOlderRelease: Explain intentional regressions vs. 4.11.35
$ git --no-pager diff -U1
diff --git a/channels/candidate-4.11.yaml b/channels/candidate-4.11.yaml
index 95b47d3a..f8289ad7 100644
--- a/channels/candidate-4.11.yaml
+++ b/channels/candidate-4.11.yaml
@@ -116 +116,2 @@ versions:
- 4.11.35
+- 4.11.36
$ hack/show-edges.py --root-version 4.11.34 candidate-4.11
4.11.34 -> 4.11.35
4.11.34 -> 4.11.36
4.11.35 -(blocked: PatchesOlderRelease)-> 4.11.36
```
So it should do what we want once [4.11.36][1] makes its way to `candidate-4.11` for real.
[1]: https://amd64.ocp.releases.ci.openshift.org/releasestream/4-stable/release/4 …
=> blocked-edges/4.11.36-PatchesOlderRelease: Explain intentional regressions vs. 4.11.35

README.md
I'm not actually consuming this new structure in Git, so the `version` file remains at 1.1.0.  But we're defining it here because:
* We want a versioned schema for passing signature data from `oc-mirror` and other graph-data image producers through to Cincinnati ([for locally run update services](https://issues.redhat.com/browse/OTA-949)),
* We might decide to version-control signatures in the future, and
* We wanted to avoid the overhead of having one versioned filesystem API for Git-to-Cincinnati and another for oc-mirror-graph-data-images-to-Cincinnati.
=> OTA-949: README: Define a 1.2.0 filesystem schema for release signatures

channels/eus-4.12.yaml, channels/stable-4.11.yaml, channels/stable-4.12.yaml
4.11.36 and 4.12.12 were built atop 4.11.34 and 4.12.10 respectively and
are older than 4.11.35 and 4.12.11 therefore we're not recommending updates
to those. These builds were produced to address install time only bugs and
as such there's no real value in getting them into the stable channel,
installers downloads pull from the latest available in customer portal.
Revert this next week and add 4.11.37 and 4.12.13 into stable channel at
the same time.
=> Stall updates into stable channel

build-suggestions/4.13.yaml
This ensures that preconditions for pre-upgrade validation added in https://issues.redhat.com/browse/OCPBUGS-7898 is present.
=> Bump minimum for minor upgrades into 4.13 to 4.12.14

blocked-edges/4.11.36-PatchesOlderRelease.yaml, blocked-edges/4.12.12-PatchesOlderRelease.yaml
4.11.36 and 4.12.12 only address an install time issue and as such
there's no real reason to upgrade to those versions. However, someone
running 4.11.0 may reasonable conclude that 4.11.36 or 4.12.12 are
better than 4.11.35 and 4.12.11, however they're not as they lack the
same set of fixes present in those versions. So lets stop recommending
any updates into these versions.
In retrospect we perhaps should've tried releasing these fixes as
4.11.34.1 and 4.12.10.1 or something. However I wasn't sure that would
work entirely up and down the stack.
=> Expand PatchesOlderRelease to not recommend any updates

build-suggestions/4.13.yaml
Avoid OCPBUGS-11409:
> The minimally viable upgrade path to 4.13 would have to be 4.12.15 or later.
=> OCPNODE-1619: Bump 4.13 `minor_min` to 4.12.15

build-suggestions/4.13.yaml
[4.12.16][1] includes [OCPBUGS-12159](https://issues.redhat.com//browse/OCPBUGS-12159).  Require clusters to pick up this fix before heading to supported 4.13 releases, so single-node OpenShift clusters will not hit an `Available=False` `node-tuning` ClusterOperator.  I'm fuzzy on the detailed mechanism, or whether other flavors besides single-node are exposed, but raising minor_min doesn't have much downside, so I don't think we need to bottom out specific exposure.
[1]: https://multi.ocp.releases.ci.openshift.org/releasestream/4-stable-multi/release/4.12.16
=> build-suggestions/4.13: Raise minor_min to 4.12.16

blocked-edges/4.10.38-node-creation-fails.yaml
The typo snuck in when the risk was declared in 825b543287 (#2661).
=> blocked-edges/4.10.38-node-creation-fails: Fix "exsiting" typo

blocked-edges/4.11.40-KeepalivedMulticastSkew.yaml
[OCPBUGS-13405][1] (openshift/baremetal-runtimecfg#249) is open with a candidate fix for 4.12.z, but the fix needs to land in 4.11.z to help with 4.10-to-4.11 updates.
[1]: https://issues.redhat.com//browse/OCPBUGS-13405
=> blocked-edges/4.11.40-KeepalivedMulticastSkew: 4.11.40 doesn't fix this issue

hack/release-ga.sh
Automate https://github.com/openshift/cincinnati-graph-data/pull/3639 / https://github.com/openshift/cincinnati-graph-data/pull/3075 / https://github.com/openshift/cincinnati-graph-data/pull/2369
`sed`ing YAML is a bit ugly but this YAML is simple enough to avoid relying on the user having a pyyaml or something similar installed
=> release-ga.sh: bump z_min to GA version

hack/stabilization-changes.py
I think this script is now "production" enough to be treated as production code, I'd like to start refactoring it slowly for readability, starting with code cleanups:
- stabilization-changes: fix mixed indentation
- stabilization-changes: populate line number for error output
- stabilization-changes: use set literals
- stabilization-changes: avoid setting some names only conditionally
- stabilization-changes: extract entrypoint to main() to avoid setting globals
- stabilization-changes: use triple quotes for docstrings
- stabilization-changes: remove unncessary parentheses
- stabilization-changes: avoid shadowing `error` names
=> stabilization-changes.py: code cleanups

hack/exposure-length.sh
Timeline for an update-risk bug:
1. Releases named with vulnerable code.
2. Someone notices the issue.
3. Update risk declared.
4. Release with the fix named.
5. `fixedIn` added so that release can enter `candidate-*`.
The duration `T2 - T1` can be long, because many of these risks are rare corner cases.  `T3 - T2` can be short, or it can be long if it takes us some time to understand the severity of the issue.  This script measures `T5 - T3`, so we have a convenient handle on that phase.
=> hack/exposure-length: Add a script showing known-exposure length

blocked-edges/4.13.0-PerformanceProfilesCPUQuota.yaml, blocked-edges/4.13.0-ec.1-PerformanceProfilesCPUQuota.yaml, blocked-edges/4.13.0-ec.2-PerformanceProfilesCPUQuota.yaml, blocked-edges/4.13.0-ec.3-PerformanceProfilesCPUQuota.yaml, blocked-edges/4.13.0-ec.4-PerformanceProfilesCPUQuota.yaml, blocked-edges/4.13.0-rc.0-PerformanceProfilesCPUQuota.yaml, blocked-edges/4.13.0-rc.2-PerformanceProfilesCPUQuota.yaml, blocked-edges/4.13.0-rc.3-PerformanceProfilesCPUQuota.yaml, blocked-edges/4.13.0-rc.4-PerformanceProfilesCPUQuota.yaml, blocked-edges/4.13.0-rc.5-PerformanceProfilesCPUQuota.yaml, blocked-edges/4.13.0-rc.6-PerformanceProfilesCPUQuota.yaml, blocked-edges/4.13.0-rc.7-PerformanceProfilesCPUQuota.yaml, blocked-edges/4.13.0-rc.8-PerformanceProfilesCPUQuota.yaml, blocked-edges/4.13.1-PerformanceProfilesCPUQuota.yaml, blocked-edges/4.13.2-PerformanceProfilesCPUQuota.yaml, blocked-edges/4.13.3-PerformanceProfilesCPUQuota.yaml, blocked-edges/4.13.4-PerformanceProfilesCPUQuota.yaml
The PromQL approach is similar to what we used in c641333f4a (#2552), except:
* I'm using the PerformanceProfiles resource.
* I'm using `apiserver_storage_objects` instead of `cluster:usage:resources:sum`, to cut out [one lossy layer of indirection][1].
Generated by writing the 4.13.0 declaration by hand, and then copying out to other 4.13 releases with:
```console
$ curl -s 'https://api.openshift.com/api/upgrades_info/graph?channel=candidate-4.13' | jq -r '.nodes[].version' | grep '^4[.]13[.]' | grep -v '^4[.]13[.]0$' | while read V; do sed "s/4[.]13[.]0/${V}/g" blocked-edges/4.13.0-PerformanceProfilesCPUQuota.yaml > "blocked-edges/${V}-PerformanceProfilesCPUQuota.yaml"; done
$ git add blocked-edges/4.13.*PerformanceProfilesCPUQuota.yaml
```
[1]: …
=> OCPNODE-1705: blocked-edges/4.13.*-PerformanceProfilesCPUQuota: Declare new risk

blocked-edges/4.12.18-MultiNetworkAttachmentsWhereaboutsVersion.yaml, blocked-edges/4.12.19-MultiNetworkAttachmentsWhereaboutsVersion.yaml, blocked-edges/4.12.20-MultiNetworkAttachmentsWhereaboutsVersion.yaml, blocked-edges/4.12.21-MultiNetworkAttachmentsWhereaboutsVersion.yaml, blocked-edges/4.12.22-MultiNetworkAttachmentsWhereaboutsVersion.yaml, blocked-edges/4.13.0-MultiNetworkAttachmentsWhereaboutsVersion.yaml, blocked-edges/4.13.0-ec.1-MultiNetworkAttachmentsWhereaboutsVersion.yaml, blocked-edges/4.13.0-ec.2-MultiNetworkAttachmentsWhereaboutsVersion.yaml, blocked-edges/4.13.0-ec.3-MultiNetworkAttachmentsWhereaboutsVersion.yaml, blocked-edges/4.13.0-ec.4-MultiNetworkAttachmentsWhereaboutsVersion.yaml, blocked-edges/4.13.0-rc.0-MultiNetworkAttachmentsWhereaboutsVersion.yaml, blocked-edges/4.13.0-rc.2-MultiNetworkAttachmentsWhereaboutsVersion.yaml, blocked-edges/4.13.0-rc.3-MultiNetworkAttachmentsWhereaboutsVersion.yaml, blocked-edges/4.13.0-rc.4-MultiNetworkAttachmentsWhereaboutsVersion.yaml, blocked-edges/4.13.0-rc.5-MultiNetworkAttachmentsWhereaboutsVersion.yaml, blocked-edges/4.13.0-rc.6-MultiNetworkAttachmentsWhereaboutsVersion.yaml, blocked-edges/4.13.0-rc.7-MultiNetworkAttachmentsWhereaboutsVersion.yaml, blocked-edges/4.13.0-rc.8-MultiNetworkAttachmentsWhereaboutsVersion.yaml, blocked-edges/4.13.1-MultiNetworkAttachmentsWhereaboutsVersion.yaml, blocked-edges/4.13.2-MultiNetworkAttachmentsWhereaboutsVersion.yaml, blocked-edges/4.13.3-MultiNetworkAttachmentsWhereaboutsVersion.yaml, blocked-edges/4.13.4-MultiNetworkAttachmentsWhereaboutsVersion.yaml
Generated by writing the 4.12.18 risk by hand, and copying it out with:
```console
$ for Z in 19 20 21 22; do sed "s/4[.]12[.]18/4.12.${Z}/g" blocked-edges/4.12.18-MultiNetworkAttachmentsWhereaboutsVersion.yaml > "blocked-edges/4.12.${Z}-MultiNetworkAttachmentsWhereaboutsVersion.yaml"; done
$ curl -s 'https://api.openshift.com/api/upgrades_info/graph?channel=candidate-4.13' | jq -r '.nodes[].version' | grep '^4[.]13[.]' | while read V; do sed "s/4[.]12[.]18/${V}/g" blocked-edges/4.12.18-MultiNetworkAttachmentsWhereaboutsVersion.yaml > "blocked-edges/${V}-MultiNetworkAttachmentsWhereaboutsVersion.yaml"; done
```
=> SDN-4019: blocked-edges: Declare MultiNetworkAttachmentsWhereaboutsVersion for 4.12.18+ and 4.13

blocked-edges/4.12.23-MultiNetworkAttachmentsWhereaboutsVersion.yaml
[OCPBUGS-15588](https://issues.redhat.com/browse/OCPBUGS-15588) is still Assigned with the 4.12.z backport.  Generated by extending the 4.12 `sed` from a129a714b2 (#3794):
```console
$ Z=23; sed "s/4[.]12[.]18/4.12.${Z}/g" blocked-edges/4.12.18-MultiNetworkAttachmentsWhereaboutsVersion.yaml > "blocked-edges/4.12.${Z}-MultiNetworkAttachmentsWhereaboutsVersion.yaml"
```
=> blocked-edges/4.12.23-MultiNetworkAttachmentsWhereaboutsVersion: 4.12.23 doesn't have the fix

blocked-edges/4.12.25-MultiNetworkAttachmentsWhereaboutsVersion.yaml
- https://issues.redhat.com/browse/OCPBUGS-15476 VERIFIED (4.13) and
present in 4.13.5 (https://amd64.ocp.releases.ci.openshift.org/releasestream/4-stable/release/4.13.5)
- https://issues.redhat.com/browse/OCPBUGS-15588 still in ON_QA (4.12)
=> `MultiNetworkAttachmentsWhereaboutsVersion`: extend 4.12 | fix in 4.13

blocked-edges/4.13.4-PerformanceProfilesCPUQuota.yaml
[4.13.5](https://amd64.ocp.releases.ci.openshift.org/releasestream/4-stable/release/4.13.5) has RHCOS [413.92.202307140015-0](https://releases-rhcos-art.apps.ocp-virt.prod.psi.redhat.com/diff.html?arch=x86_64&first_release=413.92.202306141213-0&first_stream=prod%2Fstreams%2F4.13-9.2&second_release=413.92.202307140015-0&second_stream=prod%2Fstreams%2F4.13-9.2) which has `cri-o-0-1.26.3-11.rhaos4.13.git78941bf.el9-x86_64` and `git78941bf` is the merge of https://github.com/cri-o/cri-o/pull/7013 which is the fix for OCPBUGS-14021
=> `PerformanceProfilesCPUQuota`: fixed in 4.13.5

blocked-edges/4.12.25-MultiNetworkAttachmentsWhereaboutsVersion.yaml
[4.12.26][1] includes a verified [OCPBUGS-15588][2].
[1]: https://multi.ocp.releases.ci.openshift.org/releasestream/4-stable-multi/release/4.12.26
[2]: https://issues.redhat.com/browse/OCPBUGS-15588
=> blocked-edges/4.12.25-MultiNetworkAttachmentsWhereaboutsVersion: Fixed in 4.12.26

build-suggestions/4.14.yaml
- Following PR includes changes to save the cgroups context in the node config object https://github.com/openshift/machine-config-operator/pull/3793 
- OCP 4.14+ releases default the cgroups version to "v2" 
- The above changes help in restoring the cgroups context during the upgrade of the clusters 
- Hence, it is required for the clusters to upgrade to 4.13.6 before upgrading to 4.14
=> Bump 4.14 minor min version to 4.13.6

blocked-edges/4.12.25-MultiNetworkAttachmentsWhereaboutsVersion.yaml
Not in 4.11.26.  Fixing a typo from f6ab39b22e (#3883).
=> blocked-edges/4.12.25-MultiNetworkAttachmentsWhereaboutsVersion: Fixed in 4.12.26 v2

build-suggestions/4.14.yaml
[4.13.7][1] contains [OCPBUGS-16613][2], openshift/cluster-version-operator#948.
[1]: https://multi.ocp.releases.ci.openshift.org/releasestream/4-stable-multi/release/4.13.7
[2]: https://issues.redhat.com/browse/OCPBUGS-16613
=> OTA-1004: build-suggestions/4.14: minor-min 4.13.7 for Kube-API removal ack

internal-channels/candidate.yaml
4.13.7 had a regression, see https://issues.redhat.com//browse/OCPBUGS-17120
Related erratas were dropped.
=> Tombstone 4.13.7

blocked-edges/4.13.7-RHSB2023001.yaml
[OCPBUGS-17163][1] [landed in 4.13.8][2], so 4.13.7 was also exposed to FIPS issues.  And with [1] in place, 4.13.8 has (as far as I'm aware) completed the pivot to FIPS libraries, so setting fixedIn 4.13.8.
[1]: https://issues.redhat.com/browse/OCPBUGS-17163
[2]: https://multi.ocp.releases.ci.openshift.org/releasestream/4-stable-multi/release/4.13.8
=> blocked-edges/4.13.7-RHSB2023001: 4.13.8 has the final fixes

blocked-edges/4.13.6-RHSB2023001.yaml
I haven't dug too far in, but likely because 4.13.7 was tombstoned (cd37f29018, Tombstone 4.13.7, 2023-08-04, #3944), the stabilization script is currently complaining about not realizing when the issue was fixed:
```console
$ hack/stabilization-changes.py
...
ERROR:   failed to promote 4.13.8 to stable: RHSB2023001 affects 4.13.6.  Either declare a fix version or extend the risk to 4.13.8.
...
```
By also declaring fixedIn in the 4.13.6 risk file, we avoid that failure mode.
=> blocked-edges/4.13.6-RHSB2023001: Declare fixedIn 4.13.8 here too

blocked-edges/4.13.0-PersistentVolumeDiskIDSymlinks.yaml, blocked-edges/4.13.0-ec.1-PersistentVolumeDiskIDSymlinks.yaml, blocked-edges/4.13.0-ec.2-PersistentVolumeDiskIDSymlinks.yaml, blocked-edges/4.13.0-ec.3-PersistentVolumeDiskIDSymlinks.yaml, blocked-edges/4.13.0-ec.4-PersistentVolumeDiskIDSymlinks.yaml, blocked-edges/4.13.0-rc.0-PersistentVolumeDiskIDSymlinks.yaml, blocked-edges/4.13.0-rc.2-PersistentVolumeDiskIDSymlinks.yaml, blocked-edges/4.13.0-rc.3-PersistentVolumeDiskIDSymlinks.yaml, blocked-edges/4.13.0-rc.4-PersistentVolumeDiskIDSymlinks.yaml, blocked-edges/4.13.0-rc.5-PersistentVolumeDiskIDSymlinks.yaml, blocked-edges/4.13.0-rc.6-PersistentVolumeDiskIDSymlinks.yaml, blocked-edges/4.13.0-rc.7-PersistentVolumeDiskIDSymlinks.yaml, blocked-edges/4.13.0-rc.8-PersistentVolumeDiskIDSymlinks.yaml, blocked-edges/4.13.1-PersistentVolumeDiskIDSymlinks.yaml, blocked-edges/4.13.2-PersistentVolumeDiskIDSymlinks.yaml, blocked-edges/4.13.3-PersistentVolumeDiskIDSymlinks.yaml
To mitigate [slow cache warming][1], like 99161903ac (#3590).  The `fixedIn` 4.13.4 entered `stable-4.13` back in June:
```console
$ git --no-pager blame channels/stable-4.13.yaml | grep ' 4[.]13[.]4$'
90eca13b2 (Automated Stabilization Robot 2023-06-29 08:03:38 +0000 40) - 4.13.4
```
so it's unlikely that there are all that many folks still interested in updating to it, instead of a more recent 4.13.z.  And anyone who is interested can still read the message and ticket, decide whether they're exposed, and update if they feel they aren't exposed (or if they feel they are exposed but can handle being bit).
```console
$ for X in blocked-edges/*PersistentVolumeDiskIDSymlinks*; do CONTENT="$(grep -B100 matchingRules: "${X}"; printf -- '- type: %s\n' Always)"; echo "${CONTENT}" …
```
=> blocked-edges/4.13.*-PersistentVolumeDiskIDSymlinks: Convert to Always

blocked-edges/4.13.9-AWSMintModeWithoutCredentials.yaml
[4.13.10][1] includes [OCPBUGS-17733](https://issues.redhat.com/browse/OCPBUGS-17733).
[1]: https://multi.ocp.releases.ci.openshift.org/releasestream/4-stable-multi/release/4.13.10
=> blocked-edges/4.13.9-AWSMintModeWithoutCredentials: Fixed in 4.13.10

hack/validate-blocked-edges.py
When testing https://github.com/openshift/cluster-version-operator/pull/961 I have seen CVO choking on incorrect mocked data because we [assign](https://github.com/openshift/cluster-version-operator/blob/53a5d57c2bd3c92c145dac005fab6e4cdcf8f43b/pkg/cvo/availableupdates.go#L363C8-L364C35) the name of the risk to a `condition.Reason` directly:
```
- lastTransitionTime: "2023-08-30T10:19:05Z"
message: 'ClusterVersion.config.openshift.io "version" is invalid: status.conditionalUpdates[1].conditions[0].reason:
Invalid value: "OCBBUGS-13308-01": status.conditionalUpdates[1].conditions[0].reason
in body should match ''^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$'''
status: "True"
type: Failing
```
It seems we never actually tripped this in the past but there is no reason why our checks should not …
=> validate-blocked-edges.py: enforce CamelCase names

graph-data.rs/Dockerfile
UBI9 is likely to receive Rust version updates, reducing the friction with our dependency updates ([example](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cincinnati-graph-data/4042/pull-ci-openshift-cincinnati-graph-data-master-images/1701283949705170944#1:build-log.txt%3A586))
=> Use UBI9 in image builds

blocked-edges/4.13.0-SeccompFilterErrno524.yaml, blocked-edges/4.13.1-SeccompFilterErrno524.yaml, blocked-edges/4.13.2-SeccompFilterErrno524.yaml, blocked-edges/4.13.3-SeccompFilterErrno524.yaml, blocked-edges/4.13.4-SeccompFilterErrno524.yaml, blocked-edges/4.13.5-SeccompFilterErrno524.yaml, blocked-edges/4.13.6-SeccompFilterErrno524.yaml, blocked-edges/4.13.7-SeccompFilterErrno524.yaml, blocked-edges/4.13.8-SeccompFilterErrno524.yaml, blocked-edges/4.13.9-SeccompFilterErrno524.yaml
Created manually the `4.13.0` file and copied the rest with this fish snippet: 
```
$ for x in (seq 9)
set z 4.13.$x;
cp 4.13.0-SeccompFilterErrno524.yaml $z-SeccompFilterErrno524.yaml
sed -i "s/4.13.0/4.13.$x/g" $z-SeccompFilterErrno524.yaml
end
```
=> COS-2437: blocked-edges: set up `SeccompFilterErrno524` for 4.13.[0-9]

build-suggestions/4.14.yaml
This picks up two prerequisites
OCPBUGS-18132: Block 4.14 upgrades with admin ack [on vsphere]
OCPBUGS-19351: Keep Profile status.bootcmdline around
the latter prevents dual reboots on upgrades
=> Bump the minimum to 4.13.14 to upgrade into 4.14

blocked-edges/4.14.0-rc.3-OVNWebhookUserConflict.yaml, blocked-edges/4.14.0-rc.4-OVNWebhookUserConflict.yaml, blocked-edges/4.15.0-ec.0-OVNWebhookUserConflict.yaml
The risk is for updating out of the impacted releases to hypothetical future releases with the user change, e.g. from 4.14.0-rc.3 to 4.14.0. But we're warning on * -> 4.14.0-rc.3 (and similar) to help folks dodge the sticky updates entirely, because 4.14.0-rc.2 -> 4.14.0 are not expected to ever have running-as-root webhook listeners.
Pattern-matching `apiserver_storage_objects` from b573872208 (#3786) and `egressips.k8s.ovn.org` from 894fab7974 (#2628).
The risk is only for standalone (non-HyperShift) clusters, but we haven't worked up PromQL for "I'm (not) HyperShift" yet, and it's just prerelease versions, so I'm skipping over that detail for now and declaring the risk for all OVN clusters (standalone and HyperShift) thinking about updating into impacted releases.
Generated by manually …
=> SDN-4160: blocked-edges: Declare OVNWebhookUserConflict for 4.14.0-rc.3, rc.4, and 4.15.0-ec.0

blocked-edges/4.14.0-rc.4-OVNWebhookUserConflict.yaml
[4.14.0-rc.5][1] includes [OCPBUGS-20184](https://issues.redhat.com/browse/OCPBUGS-20184).
[1]: https://multi.ocp.releases.ci.openshift.org/releasestream/4-stable-multi/release/4.14.0-rc.5
=> blocked-edges/4.14.0-rc.4-OVNWebhookUserConflict: Fixed in 4.14.0-rc.5

build-suggestions/4.14.yaml
To pick up [the DeploymentConfig perservation fix][1] which is [new in 4.13.17][2].  This also pull in [the update-risk cache-warming fix][3], which will be useful for quickly evaluating any 4.13-to-4.14 risks when folks on 4.13.z switch to fast-4.14 or other channels with updates to 4.14.z.
[1]: https://issues.redhat.com/browse/OCPBUGS-20321
[2]: https://multi.ocp.releases.ci.openshift.org/releasestream/4-stable-multi/release/4.13.17
[3]: https://issues.redhat.com/browse/OCPBUGS-19828
=> build-suggestions/4.14: Bump minor_min to 4.13.17

blocked-edges/4.11.52-incomptiable-python-update-breaking-baremetal-provisioning.yaml
[4.11.52][1] does not include a fix for [OCPBUGS-20486](https://issues.redhat.com/browse/OCPBUGS-20486).
[1]: https://amd64.ocp.releases.ci.openshift.org/releasestream/4-stable/release/4.11.52
=> blocked-edges/4.11.52-incompatible-python-update-breaking-baremetal-provisioning: Not fixed yet

internal-channels/candidate.yaml
Additional fixes were brought in and promoted as 4.11.52, 4.12.39, and 4.13.17 respectively
=> Tombstone 4.11.51, 4.12.38, and 4.13.16

blocked-edges/4.15.0-ec.0-NetworkNodeIdentityWebhookUserConflict.yaml
[4.15.0-ec.1][1] has the fix for [OCPBUGS-20104](https://issues.redhat.com/browse/OCPBUGS-20104).
[1]: https://multi.ocp.releases.ci.openshift.org/releasestream/4-dev-preview-multi/release/4.15.0-ec.1
=> blocked-edges/4.15.0-ec.0-NetworkNodeIdentityWebhookUserConflict: Fixed in 4.15.0-ec.1

build-suggestions/4.14.yaml
Yet-nonexistent 4.13.19 is likely to be the 4.13 patch release picking up https://github.com/openshift/cluster-version-operator/pull/969 which adds the `Upgradeable=False` gate when modified SCC resources are detected in the cluster. We will want everyone to go through the CVO with this change, to prevent workloads from breaking if they depend on modified system SCC resources.
=> 4.14: Bump `minor_min` to 4.13.19 to pickup the SCC gate

blocked-edges/4.14.0.yaml
No need to drop the older 4.13.z from updates into 4.14.1, because they were not included in its metadata at build time:
```console
$ oc adm release info -o json quay.io/openshift-release-dev/ocp-release:4.14.1-x86_64 | jq -r '.metadata.previous[]' | grep '^4[.]13[.]'
4.13.19
```
=> blocked-edges/4.14.0: Fixed in 4.14.1

blocked-edges/4.14.0-ConsoleImplicitlyEnabled.yaml, blocked-edges/4.14.0-rc.2-ConsoleImplicitlyEnabled.yaml, blocked-edges/4.14.0-rc.3-ConsoleImplicitlyEnabled.yaml, blocked-edges/4.14.0-rc.4-ConsoleImplicitlyEnabled.yaml, blocked-edges/4.14.0-rc.5-ConsoleImplicitlyEnabled.yaml, blocked-edges/4.14.0-rc.6-ConsoleImplicitlyEnabled.yaml, blocked-edges/4.14.0-rc.7-ConsoleImplicitlyEnabled.yaml, blocked-edges/4.14.1-ConsoleImplicitlyEnabled.yaml
Generated by writing the rc.2 risk by hand, and then running:
```console
$ curl -s 'https://api.openshift.com/api/upgrades_info/graph?channel=candidate-4.14&arch=amd64' | jq -r '.nodes[] | .version' | grep '^4[.]14[.]0-rc[.][3-9]' | while read VERSION; do sed "s/4.14.0-rc.2/${VERSION}/" blocked-edges/4.14.0-rc.2-ConsoleImplicitlyEnabled.yaml > "blocked-edges/${VERSION}-ConsoleImplicitlyEnabled.yaml"; done
```
=> OTA-1031: blocked-edges/4.14.0*: Declare ConsoleImplicitlyEnabled

blocked-edges/4.14.0-ConsoleImplicitlyEnabled.yaml, blocked-edges/4.14.0-rc.2-ConsoleImplicitlyEnabled.yaml, blocked-edges/4.14.0-rc.3-ConsoleImplicitlyEnabled.yaml, blocked-edges/4.14.0-rc.5-ConsoleImplicitlyEnabled.yaml, blocked-edges/4.14.0-rc.6-ConsoleImplicitlyEnabled.yaml, blocked-edges/4.14.0-rc.7-ConsoleImplicitlyEnabled.yaml, blocked-edges/4.14.1-ConsoleImplicitlyEnabled.yaml, hack/show-edges.py
[The regression occured in 4.14.0-rc.2][1], so updates like 4.14.0 to 4.14.1 are not exposed.  The new regular expression covers:
* Updates from `4.14.0-ec.*`, since these predate the rc.2 regression.
* Updates from `4.14.0-rc.[01]`, since these predate the rc.2 regression.
* Updates from `4.13.*`, since these predate the 4.14 regression.
4.14.0 is coming back, after 897f57f57e
(#4326) had dropped it, with a special `from` regular expression that replaces the `4.13.*` with `4.13.19`, to avoid having 4.13.17 -> 4.14.0 and 4.13.18 -> 4.14.0 sneak back in, as discussed in 897f57f57e.  The history of the updates from 4.13 to 4.14.0 is now:
* f0dc7e86d1 (#4301) dropped 4.13.17 and 18 from 4.14.0 update sources completely, and merged 2023-10-27, before 4.14.0 entered `candidate-4.*` channels.
* …
=> blocked-edges/4.14.*-ConsoleImplicitlyEnabled: Tune from versions

blocked-edges/4.11.52-incomptiable-python-update-breaking-baremetal-provisioning.yaml
[4.11.53][1] includes [OCPBUGS-20486](https://issues.redhat.com/browse/OCPBUGS-20486).
[1]: https://amd64.ocp.releases.ci.openshift.org/releasestream/4-stable/release/4.11.53
=> blocked-edges/4.11.52-incomptiable-python-update-breaking-baremetal-provisioning: Fixed in 4.11.53

blocked-edges/4.14.1-ConsoleImplicitlyEnabled.yaml
[4.14.2][1] contains [OCPBUGS-22718](https://issues.redhat.com/browse/OCPBUGS-22718).
[1]: https://multi.ocp.releases.ci.openshift.org/releasestream/4-stable-multi/release/4.14.2
=> blocked-edges/4.14.1-ConsoleImplicitlyEnabled: Fixed in 4.14.2

blocked-edges/4.12.41-OVNKubeMasterDSPrestop.yaml, blocked-edges/4.12.42-OVNKubeMasterDSPrestop.yaml, blocked-edges/4.12.43-OVNKubeMasterDSPrestop.yaml, blocked-edges/4.13.16-OVNKubeMasterDSPrestop.yaml, blocked-edges/4.13.17-OVNKubeMasterDSPrestop.yaml, blocked-edges/4.13.18-OVNKubeMasterDSPrestop.yaml, blocked-edges/4.13.19-OVNKubeMasterDSPrestop.yaml, blocked-edges/4.13.21-OVNKubeMasterDSPrestop.yaml, blocked-edges/4.13.22-OVNKubeMasterDSPrestop.yaml, blocked-edges/4.14.0-OVNKubeMasterDSPrestop.yaml, blocked-edges/4.14.1-OVNKubeMasterDSPrestop.yaml, blocked-edges/4.14.2-OVNKubeMasterDSPrestop.yaml
Set up risk on updates to 4.12.41+, 4.13.16+ or 4.14+, on OVN clusters
installed before 4.10.
> clusters that have upgraded from 4.10->4.11 will be vulnerable and
> will be affected by this issue when/if they eventually upgrade to
> 4.12.41+, 4.13.16+ or 4.14+
> ...
> - clusters using the OVNKubernetes CNI and that have previously been upgraded from 4.10
>   to 4.11
> - clusters that were initially installed with 4.11 or newer are not affected.
I created the 4.12.41 file manually and copied it around:
```
$ for ocp12 in (seq 42 43)
sed -e "s/4.12.41/4.12.$ocp12/" blocked-edges/4.12.41-OVNKubeMasterDSPrestop.yaml > blocked-edges/4.12.$ocp12-OVNKubeMasterDSPrestop.yaml
end
$ for ocp13 in (seq 16 22)
sed -e "s/4.12.41/4.13.$ocp13/" blocked-edges/4.12.41-OVNKubeMasterDSPrestop.yaml > …
```
=> SDN-4196: Set `OVNKubeMasterDNPrestop` on OVN clusters installed before 4.11

blocked-edges/4.14.0-ec.0-PreRelease.yaml, blocked-edges/4.14.0-ec.1-PreRelease.yaml, blocked-edges/4.14.0-ec.2-PreRelease.yaml, blocked-edges/4.14.0-ec.3-PreRelease.yaml, blocked-edges/4.14.0-ec.4-PreRelease.yaml, blocked-edges/4.14.0-rc.0-PreRelease.yaml, blocked-edges/4.14.0-rc.1-PreRelease.yaml, blocked-edges/4.14.0-rc.2-PreRelease.yaml, blocked-edges/4.14.0-rc.3-PreRelease.yaml, blocked-edges/4.14.0-rc.4-PreRelease.yaml, blocked-edges/4.14.0-rc.5-PreRelease.yaml, blocked-edges/4.14.0-rc.6-PreRelease.yaml, blocked-edges/4.14.0-rc.7-PreRelease.yaml
Before this commit, folks on 4.13.9 and other older 4.13.z might think they should update to 4.14.0-rc.2 as their largest recommended hop in candidate-4.14:
```console
$ hack/show-edges.py --cincinnati https://api.openshift.com/api/upgrades_info/graph --root-version 4.13.9 candidate-4.14 | grep '^4[.]13[.]9 '
4.13.9 -> 4.13.10
4.13.9 -> 4.13.11
4.13.9 -> 4.13.12
4.13.9 -> 4.13.13
4.13.9 -> 4.13.14
4.13.9 -> 4.13.15
4.13.9 -(risks: OVNKubeMasterDSPrestop)-> 4.13.16
4.13.9 -(risks: OVNKubeMasterDSPrestop)-> 4.13.17
4.13.9 -(risks: OVNKubeMasterDSPrestop)-> 4.13.18
4.13.9 -(risks: OVNKubeMasterDSPrestop)-> 4.13.19
4.13.9 -(risks: OVNKubeMasterDSPrestop)-> 4.13.21
4.13.9 -(risks: OVNKubeMasterDSPrestop)-> 4.13.22
4.13.9 -> 4.14.0-rc.0
4.13.9 -> 4.14.0-rc.1
4.13.9 -(risks: …
```
=> blocked-edges/4.14.0-*-PreRelease: Point out that 4.14 is GA

blocked-edges/4.12.44-OVNKubeMasterDSPrestop.yaml
[OCPBUGS-22293](https://issues.redhat.com/browse/OCPBUGS-22293) is still ASSIGNED, so 4.12.44 is affected.
=> Extend `OVNKubeMasterDNPrestop` to 4.12.44

blocked-edges/4.13.23-OVNKubeMasterDSPrestop.yaml
[OCPBUGS-22293](https://issues.redhat.com/browse/OCPBUGS-22293) is still `Assigned` for 4.15, so not fixed in 4.13.z yet.
=> blocked-edges/4.13.23-OVNKubeMasterDSPrestop: Extend unfixed risk

hack/release-ga.sh
They don't need to have updates from the early prereleases once 4.y goes generally available, and a reduced update set makes it easier to spend our update-testing effort on edges that are more likely to have traffic on them.
=> OTA-874: hack/release-ga: Set minor_min in build-suggestions/4.(y+1).yaml

blocked-edges/4.13.24-OVNKubeMasterDSPrestop.yaml
[1] is still Assigned for 4.15, so not fixed in 4.13.z yet.
[1]: https://issues.redhat.com/browse/OCPBUGS-22293
=> blocked-edges/4.13.24-OVNKubeMasterDSPrestop: Extend unfixed risk

blocked-edges/4.13.25-OVNKubeMasterDSPrestop.yaml
[OCPBUGS-22293](https://issues.redhat.com/browse/OCPBUGS-22293) is still `Assigned` (although it now aims at 4.13.z), so not fixed in 4.13.z yet.
=> blocked-edges/4.13.25-OVNKubeMasterDSPrestop: Extend unfixed risk

blocked-edges/4.12.45-OVNKubeMasterDSPrestop.yaml
[OCPBUGS-24039](https://issues.redhat.com/browse/OCPBUGS-24039) is still `New`, so not fixed in 4.12.z yet.
=> blocked-edges/4.12.45-OVNKubeMasterDSPrestop: Extend unfixed risk

blocked-edges/4.13.26-OVNKubeMasterDSPrestop.yaml
[OCPBUGS-22293](https://issues.redhat.com/browse/OCPBUGS-22293) is still Assigned, so not fixed in 4.13.z yet.
=> blocked-edges/4.13.26-OVNKubeMasterDSPrestop: Extend unfixed risk

channels/stable-4.11.yaml
Currently, 4.11 and 4.12 are on an alternating weekly schedule. This means that 4.11.z will go in one week but won't have an update path to 4.12 for another roughly 7 days while the following 4.12 release cooks in fast channels. By delaying things for another 4 days we're splitting the difference and the maximum delay for those who aren't able to use channels directly, aka ROSA clusters.
=> Add 4 days to the stable-4.11 channel delay

blocked-edges/4.13.25-AROBrokenDNSMasq.yaml, blocked-edges/4.13.26-AROBrokenDNSMasq.yaml, blocked-edges/4.13.27-AROBrokenDNSMasq.yaml, blocked-edges/4.14.2-AROBrokenDNSMasq.yaml, blocked-edges/4.14.4-AROBrokenDNSMasq.yaml, blocked-edges/4.14.5-AROBrokenDNSMasq.yaml, blocked-edges/4.14.6-AROBrokenDNSMasq.yaml, blocked-edges/4.14.7-AROBrokenDNSMasq.yaml
On non ARO clusters the query was emitting multiple zero values. Also the ARO operator will only exist on ARO clusters so no need to pay attention to whether or not the cluster is on Azure.
Also extend to 4.13.27 and 4.14.7
=> Fix AROBrokenDNSMasq

blocked-edges/4.14.0-ec.0-AzureDefaultVMType.yaml, blocked-edges/4.14.0-ec.1-AzureDefaultVMType.yaml, blocked-edges/4.14.0-ec.2-AzureDefaultVMType.yaml, blocked-edges/4.14.0-ec.3-AzureDefaultVMType.yaml, blocked-edges/4.14.0-ec.4-AzureDefaultVMType.yaml, blocked-edges/4.14.0-rc.0-AzureDefaultVMType.yaml, blocked-edges/4.14.0-rc.1-AzureDefaultVMType.yaml, blocked-edges/4.14.0-rc.2-AzureDefaultVMType.yaml, blocked-edges/4.14.0-rc.3-AzureDefaultVMType.yaml, blocked-edges/4.14.0-rc.4-AzureDefaultVMType.yaml, blocked-edges/4.14.0-rc.5-AzureDefaultVMType.yaml, blocked-edges/4.14.0-rc.6-AzureDefaultVMType.yaml, blocked-edges/4.14.0-rc.7-AzureDefaultVMType.yaml, blocked-edges/4.14.0.yaml, blocked-edges/4.14.1-AzureDefaultVMType.yaml, blocked-edges/4.14.2-AzureDefaultVMType.yaml, blocked-edges/4.14.3-AzureDefaultVMType.yaml, blocked-edges/4.14.4-AzureDefaultVMType.yaml, blocked-edges/4.14.5-AzureDefaultVMType.yaml, blocked-edges/4.14.6-AzureDefaultVMType.yaml, blocked-edges/4.14.7-AzureDefaultVMType.yaml
Generated by writing the 4.14.1 risk by hand, and then running:
```console
$ (curl -s 'https://api.openshift.com/api/upgrades_info/graph?channel=candidate-4.14&arch=amd64' | jq -r '.nodes[] | .version' | grep '^4[.]14[.]' | grep -v '^4[.]14[.][01]$') | while read VERSION; do sed "s/4.14.1/${VERSION}/" blocked-edges/4.14.1-AzureDefaultVMType.yaml > "blocked-edges/${VERSION}-AzureDefaultVMType.yaml"; done
```
I also manually added the silent-drop to 4.14.0.  We have almost entirely avoided silent drops since growing the ability to declare conditional risks in 4.10.  But f0dc7e86d1 (#4301) decided to use silent drops for 4.13.17 and 4.13.18 to 4.14.0.  As described in that commit message, there are trade-offs between silent-drops and an Always risk for those updates.  With this commit, we …
=> OCPCLOUD-2409: blocked-edges/4.14*: Declare AzureDefaultVMType

blocked-edges/4.14.0-ec.0-AzureDefaultVMType.yaml, blocked-edges/4.14.0-ec.1-AzureDefaultVMType.yaml, blocked-edges/4.14.0-ec.2-AzureDefaultVMType.yaml, blocked-edges/4.14.0-ec.3-AzureDefaultVMType.yaml, blocked-edges/4.14.0-ec.4-AzureDefaultVMType.yaml, blocked-edges/4.14.0-rc.0-AzureDefaultVMType.yaml, blocked-edges/4.14.0-rc.1-AzureDefaultVMType.yaml, blocked-edges/4.14.0-rc.2-AzureDefaultVMType.yaml, blocked-edges/4.14.0-rc.3-AzureDefaultVMType.yaml, blocked-edges/4.14.0-rc.4-AzureDefaultVMType.yaml, blocked-edges/4.14.0-rc.5-AzureDefaultVMType.yaml, blocked-edges/4.14.0-rc.6-AzureDefaultVMType.yaml, blocked-edges/4.14.0-rc.7-AzureDefaultVMType.yaml, blocked-edges/4.14.1-AzureDefaultVMType.yaml, blocked-edges/4.14.2-AzureDefaultVMType.yaml, blocked-edges/4.14.3-AzureDefaultVMType.yaml, blocked-edges/4.14.4-AzureDefaultVMType.yaml, blocked-edges/4.14.5-AzureDefaultVMType.yaml, blocked-edges/4.14.6-AzureDefaultVMType.yaml, blocked-edges/4.14.7-AzureDefaultVMType.yaml
Miguel points out that the exposure set [is more complicated][1] than what I'd done in 45eb9ea7c8 (#4541).  It's:
* Azure born in 4.8 or earlier are exposed.  Both ARO (which creates clusters with Hive?) and clusters created via openshift-installer.
* ARO clusters created in 4.13 and earlier are exposed.
Generated by updating the 4.14.1 risk by hand, and then running:
```console
$ curl -s 'https://api.openshift.com/api/upgrades_info/graph?channel=candidate-4.14&arch=amd64' | jq -r '.nodes[] | .version' | grep '^4[.]14[.]' | grep -v '^4[.]14[.][01]$' | while read VERSION; do sed "s/4.14.1/${VERSION}/" blocked-edges/4.14.1-AzureDefaultVMType.yaml > "blocked-edges/${VERSION}-AzureDefaultVMType.yaml"; done
```
I break down the new PromQL logic in the commit message.
[1]: …
=> OCPCLOUD-2409: blocked-edges/*-AzureDefaultVMType: Born in 4.13 ARO all exposed

blocked-edges/4.13.28-AROBrokenDNSMasq.yaml, blocked-edges/4.13.28-OVNKubeMasterDSPrestop.yaml, blocked-edges/4.14.8-AROBrokenDNSMasq.yaml, blocked-edges/4.14.8-AzureDefaultVMType.yaml
None of these have been fixed in relevant streams
=> Carry AROBrokenDNSMasq, OVNKubeMasteRDSPrsetop, and AzureDefaultVMType

blocked-edges/4.14.0-ec.0-AWSECRLegacyCredProvider.yaml, blocked-edges/4.14.0-ec.1-AWSECRLegacyCredProvider.yaml, blocked-edges/4.14.0-ec.2-AWSECRLegacyCredProvider.yaml, blocked-edges/4.14.0-ec.3-AWSECRLegacyCredProvider.yaml, blocked-edges/4.14.0-ec.4-AWSECRLegacyCredProvider.yaml, blocked-edges/4.14.0-rc.0-AWSECRLegacyCredProvider.yaml, blocked-edges/4.14.0-rc.1-AWSECRLegacyCredProvider.yaml, blocked-edges/4.14.0-rc.2-AWSECRLegacyCredProvider.yaml, blocked-edges/4.14.0-rc.3-AWSECRLegacyCredProvider.yaml, blocked-edges/4.14.0-rc.4-AWSECRLegacyCredProvider.yaml, blocked-edges/4.14.0-rc.5-AWSECRLegacyCredProvider.yaml, blocked-edges/4.14.0-rc.6-AWSECRLegacyCredProvider.yaml, blocked-edges/4.14.0-rc.7-AWSECRLegacyCredProvider.yaml, blocked-edges/4.14.0.yaml, blocked-edges/4.14.1-AWSECRLegacyCredProvider.yaml, blocked-edges/4.14.2-AWSECRLegacyCredProvider.yaml, blocked-edges/4.14.3-AWSECRLegacyCredProvider.yaml, blocked-edges/4.14.4-AWSECRLegacyCredProvider.yaml, blocked-edges/4.14.5-AWSECRLegacyCredProvider.yaml, blocked-edges/4.14.6-AWSECRLegacyCredProvider.yaml, blocked-edges/4.14.7-AWSECRLegacyCredProvider.yaml, blocked-edges/4.14.8-AWSECRLegacyCredProvider.yaml
We don't know what PromQL looks like for "I'm using (or not) ECR" looks like, so this will go out to all AWS clusters, not just the exposed ones.  Hopefully the content of the linked URI allows them to determine whether or not they're actually exposed.  If/when we figure out how to tighten the PromQL, we can file a follow-up pull request to adjust here.
Generated the 4.14.0 and 4.14.1 content by hand and copied out with:
```console
$ curl -s 'https://api.openshift.com/api/upgrades_info/graph?channel=candidate-4.14&arch=amd64' | jq -r '.nodes[] | .version' | grep '^4[.]14[.]' | grep -v '^4[.]14[.][01]$' | while read VERSION; do sed "s/4.14.1/${VERSION}/" blocked-edges/4.14.1-AWSECRLegacyCredProvider.yaml > "blocked-edges/${VERSION}-AWSECRLegacyCredProvider.yaml"; done
```
=> OCPCLOUD-2434: blocked-edges/4.14*: Declare AWSECRLegacyCredProvider

blocked-edges/4.15.0-rc.0-EarlyAPICertRotation.yaml
We could write PromQL that would try and identify older clusters, but with rc.1 already cut, I've just gone with Always for simplicity, and to avoid folks updating to rc.0 while young, forgetting to update further, and then aging into the early, broken CA rotation.
=> blocked-edges/4.15.0-rc.0: Declare EarlyAPICertRotation

blocked-edges/4.14.0-ec.0-AWSECRLegacyCredProvider.yaml, blocked-edges/4.14.0-ec.1-AWSECRLegacyCredProvider.yaml, blocked-edges/4.14.0-ec.2-AWSECRLegacyCredProvider.yaml, blocked-edges/4.14.0-ec.3-AWSECRLegacyCredProvider.yaml, blocked-edges/4.14.0-ec.4-AWSECRLegacyCredProvider.yaml, blocked-edges/4.14.0-rc.0-AWSECRLegacyCredProvider.yaml, blocked-edges/4.14.0-rc.1-AWSECRLegacyCredProvider.yaml, blocked-edges/4.14.0-rc.2-AWSECRLegacyCredProvider.yaml, blocked-edges/4.14.0-rc.3-AWSECRLegacyCredProvider.yaml, blocked-edges/4.14.0-rc.4-AWSECRLegacyCredProvider.yaml, blocked-edges/4.14.0-rc.5-AWSECRLegacyCredProvider.yaml, blocked-edges/4.14.0-rc.6-AWSECRLegacyCredProvider.yaml, blocked-edges/4.14.0-rc.7-AWSECRLegacyCredProvider.yaml, blocked-edges/4.14.1-AWSECRLegacyCredProvider.yaml, blocked-edges/4.14.2-AWSECRLegacyCredProvider.yaml, blocked-edges/4.14.3-AWSECRLegacyCredProvider.yaml, blocked-edges/4.14.4-AWSECRLegacyCredProvider.yaml, blocked-edges/4.14.5-AWSECRLegacyCredProvider.yaml, blocked-edges/4.14.6-AWSECRLegacyCredProvider.yaml, blocked-edges/4.14.7-AWSECRLegacyCredProvider.yaml, blocked-edges/4.14.8-AWSECRLegacyCredProvider.yaml
Joel Speed says:
> Looking into the fix for this, I found sources saying that ECR creds should be used for any image matching the following globs
> `"*.dkr.ecr.*.amazonaws.com"`
> `"*.dkr.ecr.*.amazonaws.com.cn"`
> `"*.dkr.ecr-fips.*.amazonaws.com"`
> `"*.dkr.ecr.us-iso-east-1.c2s.ic.gov"`
> `"*.dkr.ecr.us-isob-east-1.sc2s.sgov.gov"`
We can use the `kube_pod_container_info` metric that is labeled with an `image` label that contains pullspec, so we can regex-match over these and detect that a cluster is actually using ECR from the presence of a pod containing a container using an image from ECR.
The regex is a bit hairy so I added a comment. [PromQL is using RE2 syntax](https://prometheus.io/docs/prometheus/latest/querying/basics/):
> All regular expressions in Prometheus use [RE2 …
=> OCPCLOUD-2434: EWSECRLegacyCredProvider: Detect actual ECR usage from pullspecs

blocked-edges/4.15.0-rc.0-EtcdBackupMountPointStuck.yaml, blocked-edges/4.15.0-rc.1-EtcdBackupMountPointStuck.yaml
- Affects upgrades from 4.14.[3-8] to 4.15
- May not affect all platforms but given 4.15 is not GA yet setting up `Always` seems like an acceptable big hammer
=> ETCD-511: Set up EtcdBackupMountPointStuck for 4.14.[3-8]->5.15.0 RC0+ edges

blocked-edges/4.12.47-OVNKubeMasterDSPrestop.yaml, blocked-edges/4.13.29-AROBrokenDNSMasq.yaml, blocked-edges/4.13.29-OVNKubeMasterDSPrestop.yaml
`AROBrokenDNSMasq`:
- [OCPBUGS-26559](https://issues.redhat.com/browse/OCPBUGS-26559) for 4.14 is in `MODIFIED` so 4.13.29 is affected
`OVNKubeMasterDSPrestop`:
- [OCPBUGS-22293](https://issues.redhat.com/browse/OCPBUGS-22293) for 4.13 is in `MODIFIED` so 4.13.29 and 4.12.47 are still affected
=> Carry `AROBrokenDNSMasq` and `OVNKubeMasterDSPrestop`

blocked-edges/4.14.9-AROBrokenDNSMasq.yaml, blocked-edges/4.14.9-AWSECRLegacyCredProvider.yaml, blocked-edges/4.14.9-AzureDefaultVMType.yaml
`AROBrokenDNSMasq`:
- [OCPBUGS-26559](https://issues.redhat.com/browse/OCPBUGS-26559) for 4.14 got `VERIFIED` today but is not yet present in https://amd64.ocp.releases.ci.openshift.org/releasestream/4-stable/release/4.14.9 so 4.14.9 is still affected
`AWSECRLegacyCredProvider`:
- [OCPBUGS-25662](https://issues.redhat.com/browse/OCPBUGS-25662) for 4.16 is still in `POST`, so 4.14.9 is still affected
`AzureDefaultVMType`:
- [OCPBUGS-26548](https://issues.redhat.com/browse/OCPBUGS-26548) for 4.14 is still in `POST`, so 4.14.9 is still affected
=> Carry `AROBrokenDNSMasq`, `AWSECRLegacyCredProvider` and `AzureDefaultVMType` to 4.14.9

blocked-edges/4.15.0-rc.2-EtcdBackupMountPointStuck.yaml
The problem is fixed in 4.14.9 but affects all ->4.15 edges from previous versions
=> EtcdBackupMountPointStuck: extend to 4.15.0-rc.2

build-suggestions/4.15.yaml
ref: https://issues.redhat.com/browse/ETCD-511
=> Bump 4.15 min minor version to 4.14.9 for EtcdBackupMountPointStuck

build-suggestions/4.16.yaml, channels/candidate-4.16.yaml
Like 3eb8e55eb2 (#2758) and 8a890f6859 (#4167), but for 4.16.  Run well before feature-freeze, but ideally we'd have run this before we'd cut 4.16.0-ec.0, to make it easy for folks to test updated into that Engineering Candidate.  Generated with:
```console
$ hack/release-open.sh 4.16
$ git add build-suggestions/4.16.yaml channels/*4.16.yaml
```
=> *: Prepare for 4.16 development

blocked-edges/4.13.29-AROBrokenDNSMasq.yaml
[4.13.30][1] contains [OCPBUGS-27096](https://issues.redhat.com/browse/OCPBUGS-27096).
[1]: https://multi.ocp.releases.ci.openshift.org/releasestream/4-stable-multi/release/4.13.30
=> blocked-edges/4.13.29-AROBrokenDNSMasq: Fixed in 4.13.30

blocked-edges/4.13.29-OVNKubeMasterDSPrestop.yaml
[4.13.30][1] contains [OCPBUGS-22293](https://issues.redhat.com/browse/OCPBUGS-22293).
[1]: https://multi.ocp.releases.ci.openshift.org/releasestream/4-stable-multi/release/4.13.30
=> blocked-edges/4.13.29-OVNKubeMasterDSPrestop: Fixed in 4.13.30

blocked-edges/4.14.9-AzureDefaultVMType.yaml
[4.14.10][1] contains [OCPBUGS-26548](https://issues.redhat.com/browse/OCPBUGS-26548).
[1]: https://multi.ocp.releases.ci.openshift.org/releasestream/4-stable-multi/release/4.14.10
=> blocked-edges/4.14.9-AzureDefaultVMType: Fixed in 4.14.10

blocked-edges/4.14.10-AWSECRLegacyCredProvider.yaml
[OCPBUGS-25662](https://issues.redhat.com/browse/OCPBUGS-25662) is still `Post` for 4.16.
=> blocked-edges/4.14.10-AWSECRLegacyCredProvider: Still exposed

blocked-edges/4.14.9-AROBrokenDNSMasq.yaml
[4.14.10][1] contains [OCPBUGS-26559](https://issues.redhat.com/browse/OCPBUGS-26559).
[1]: https://multi.ocp.releases.ci.openshift.org/releasestream/4-stable-multi/release/4.14.10
=> blocked-edges/4.14.9-AROBrokenDNSMasq: Fixed in 4.14.10

blocked-edges/4.15.0-rc.0-EtcdBackupMountPointStuck.yaml, blocked-edges/4.15.0-rc.1-EtcdBackupMountPointStuck.yaml, blocked-edges/4.15.0-rc.2-EtcdBackupMountPointStuck.yaml
The extra period snuck in with 7520d171e6 (#4581), and kept the single-patch-digit source releases from matching.  With this commit, they start matching:
```console
$ hack/show-edges.py --root-version 4.14.8 candidate-4.15 | grep '^4[.]14[.]8 '
4.14.8 -> 4.14.10
4.14.8 -(risks: AROBrokenDNSMasq)-> 4.14.9
4.14.8 -(risks: EtcdBackupMountPointStuck)-> 4.15.0-rc.1
4.14.8 -(risks: EtcdBackupMountPointStuck)-> 4.15.0-rc.2
```
=> blocked-edges/4.15.0-*-EtcdBackupMountPointStuck: Drop . from 'from' regexp

blocked-edges/4.15.0-rc.2-EtcdBackupMountPointStuck.yaml
This is fixed by way of increasing the miniumum minor version upgrade to 4.14.9 which contains the fix for
https://issues.redhat.com/browse/OCPBUGS-26214
=> EtcdBackupMountPointStuck fixed in 4.15.0-rc.3

blocked-edges/4.15.0-ec.0-GCPMintModeRoleAdmin.yaml, blocked-edges/4.15.0-ec.1-GCPMintModeRoleAdmin.yaml, blocked-edges/4.15.0-ec.2-GCPMintModeRoleAdmin.yaml, blocked-edges/4.15.0-ec.3-GCPMintModeRoleAdmin.yaml, blocked-edges/4.15.0-rc.0-GCPMintModeRoleAdmin.yaml, blocked-edges/4.15.0-rc.1-GCPMintModeRoleAdmin.yaml, blocked-edges/4.15.0-rc.2-GCPMintModeRoleAdmin.yaml, blocked-edges/4.15.0-rc.3-GCPMintModeRoleAdmin.yaml
The PromQL logic is pretty similar to 4.13.9-AWSMintModeWithoutCredentials.yaml
The exposure is probably somewhere in the 4.15 ECs or RCs, but I'm naively opening with a blanket 4.14 -> 4.15 to get this out the door. We can refine the threshold later as we pin down exactly when in 4.15 the creds started using custom roles.
Generated by manually writing the 4.15.0-rc.0 risk, and copying out to other 4.15 with:
```console
$ curl -s 'https://api.openshift.com/api/upgrades_info/graph?channel=candidate-4.15&arch=amd64' | jq -r '.nodes[] | .version' | grep '^4[.]15[.]' | grep -v '^4[.]15[.]0-rc[.]0$' | while read VERSION; do sed "s/4.15.0-rc.0/${VERSION}/" blocked-edges/4.15.0-rc.0-GCPMintModeRoleAdmin.yaml > "blocked-edges/${VERSION}-GCPMintModeRoleAdmin.yaml"; done
```
=> CCO-522: blocked-edges/4.15.0-rc.0-GCPMintModeRoleAdmin: Declare risk

blocked-edges/4.12.47-OVNKubeMasterDSPrestop.yaml
https://amd64.ocp.releases.ci.openshift.org/releasestream/4-stable/release/4.12.48:
> [cluster-network-operator](https://github.com/openshift/cluster-network-operator/tree/d74dddd8a429363054fb7d0a17c34f7c19484296)
> ...
> [OCPBUGS-24039](https://issues.redhat.com/browse/OCPBUGS-24039): remove all managed fields used by old manager [#2099](https://github.com/openshift/cluster-network-operator/pull/2099)
> ...
=> `OVNKubeMasterDSPrestop`: Fixed in 4.12.48

blocked-edges/4.15.0-rc.4-GCPMintModeRoleAdmin.yaml
[OCPBUGS-28231](https://issues.redhat.com/browse/OCPBUGS-28231) is not yet resolved => extending the risk to 4.15.0-rc.4
=> `GCPMintModeRoleAdmin`: Extend to 4.15.0-rc.4

OWNERS_ALIASES, README.md, build-suggestions/OWNERS, channels/OWNERS, deploy/OWNERS, graph-data.rs/OWNERS, hack/OWNERS, internal-channels/OWNERS, raw/OWNERS
`cincinnati-graph-data-approvers` are not on-call, and update risks that impact the SRE-managed fleet may be discovered while no `cincinnati-graph-data-approvers` are available to declare them.  This pull request creates a new `sre-approvers` alias (populated with @openshift/openshift-team-sd-sre-team-leads) and grants root approval powers so they can:
* Update the `sre-approvers` alias in `OWNERS_ALIASES`, as described in 9982225f97.
* Manage update risks in `blocked-edges/`.
* Use `/override ...` comments in pull requests (which require root-directly approval powers) if needed to bypass any flaking CI and land emergency update risk declarations.
I'm not including `sre-approvers` as reviewers, because when `cincinnati-graph-data-approvers` are available, they'll handle review.  And when …
=> OTA-1179: OWNERS: Grant sre-approvers root approval status

hack/show-edges.py
My Python 3.12.1 gives me SyntaxWarnings:
```console
$ ./hack/show-edges.py --cincinnati https://api.openshift.com/api/upgrades_info/graph --root-version 4.13.28 eus-4.14
/home/pmuller/Projects/RH/github.com/openshift/cincinnati-graph-data/hack/show-edges.py:23: SyntaxWarning: invalid escape sequence '\d'
_VERSION_REGEXP = re.compile('^(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)(?:-(?P<prerelease>(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+(?P<buildmetadata>[0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$')
/home/pmuller/Projects/RH/github.com/openshift/cincinnati-graph-data/hack/show-edges.py:24: SyntaxWarning: invalid escape sequence '\d'
_CHANNEL_REGEXP =
re.compile('^(?P<stream>.*)-(?P<major_minor>[1-9]\d*[.][1-9]\d*)$') …
```
=> show-edges.py: use raw strings for regexes

blocked-edges/4.14.10-AWSECRLegacyCredProvider.yaml
[4.14.11][1] contains [OCPBUGS-27759](https://issues.redhat.com/browse/OCPBUGS-27759).
[1]: https://multi.ocp.releases.ci.openshift.org/releasestream/4-stable-multi/release/4.14.11
=> blocked-edges/4.14.10-AWSECRLegacyCredProvider: fixedIn 4.14.11

blocked-edges/4.15.0-rc.5-GCPMintModeRoleAdmin.yaml
[OCPBUGS-28231](https://issues.redhat.com/browse/OCPBUGS-28231) hasn't landed yet, and we need a new 4.15 release built that only includes 4.14.z with that fix before we can drop this risk.
=> blocked-edges/4.15.0-rc.5-GCPMintModeRoleAdmin: Not fixed yet

blocked-edges/4.14.0-ec.0-ARORegistryImagePreservation.yaml, blocked-edges/4.14.0-ec.1-ARORegistryImagePreservation.yaml, blocked-edges/4.14.0-ec.2-ARORegistryImagePreservation.yaml, blocked-edges/4.14.0-ec.3-ARORegistryImagePreservation.yaml, blocked-edges/4.14.0-ec.4-ARORegistryImagePreservation.yaml, blocked-edges/4.14.0-rc.0-ARORegistryImagePreservation.yaml, blocked-edges/4.14.0-rc.1-ARORegistryImagePreservation.yaml, blocked-edges/4.14.0-rc.2-ARORegistryImagePreservation.yaml, blocked-edges/4.14.0-rc.3-ARORegistryImagePreservation.yaml, blocked-edges/4.14.0-rc.4-ARORegistryImagePreservation.yaml, blocked-edges/4.14.0-rc.5-ARORegistryImagePreservation.yaml, blocked-edges/4.14.0-rc.6-ARORegistryImagePreservation.yaml, blocked-edges/4.14.0-rc.7-ARORegistryImagePreservation.yaml, blocked-edges/4.14.1-ARORegistryImagePreservation.yaml, blocked-edges/4.14.10-ARORegistryImagePreservation.yaml, blocked-edges/4.14.11-ARORegistryImagePreservation.yaml, blocked-edges/4.14.2-ARORegistryImagePreservation.yaml, blocked-edges/4.14.3-ARORegistryImagePreservation.yaml, blocked-edges/4.14.4-ARORegistryImagePreservation.yaml, blocked-edges/4.14.5-ARORegistryImagePreservation.yaml, blocked-edges/4.14.6-ARORegistryImagePreservation.yaml, blocked-edges/4.14.7-ARORegistryImagePreservation.yaml, blocked-edges/4.14.8-ARORegistryImagePreservation.yaml, blocked-edges/4.14.9-ARORegistryImagePreservation.yaml
Generated by hand-writing the 4.14.1 risk and then copying it out to the rest of 4.14:
```console
$ curl -s 'https://api.openshift.com/api/upgrades_info/graph?channel=candidate-4.14&arch=amd64' | jq -r '.nodes[] | .version' | grep '^4[.]14[.]' | grep -v '^4[.]14[.][01]$' | while read VERSION; do sed "s/4.14.1/${VERSION}/" blocked-edges/4.14.1-AzureRegistryImagePreservation.yaml > "blocked-edges/${VERSION}-AzureRegistryImagePreservation.yaml"; done
```
=> IR-461: blocked-edges/4.14.*: Declare ARORegistryImagePreservation

blocked-edges/4.14.12-AzureRegistryImagePreservation.yaml
[OCPBUGS-29003](https://issues.redhat.com/browse/OCPBUGS-29003) is still POST for 4.16, and once it's verified there we'll still need backports through 4.14.
=> blocked-edges/4.14.12-AzureRegistryImagePreservation: Not yet fixed

blocked-edges/4.12.48-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml, blocked-edges/4.12.49-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml, blocked-edges/4.13.30-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml, blocked-edges/4.13.31-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml, blocked-edges/4.13.32-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml, blocked-edges/4.13.33-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml, blocked-edges/4.14.10-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml, blocked-edges/4.14.11-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml, blocked-edges/4.14.12-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml, blocked-edges/4.14.9-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml, blocked-edges/4.15.0-rc.1-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml, blocked-edges/4.15.0-rc.2-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml, blocked-edges/4.15.0-rc.3-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml, blocked-edges/4.15.0-rc.4-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml, blocked-edges/4.15.0-rc.5-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml
- `NetPolicyTimeoutsHostNetworkedPodTraffic`: Add `_id==""` placeholders
- `NetPolicyTimeoutsHostNetworkedPodTraffic`: Limit exposure to baremetal-ish platforms
=> `NetPolicyTimeoutsHostNetworkedPodTraffic`: Exclude cloud platforms from exposure

blocked-edges/4.14.0-ec.0-AzureRegistryImagePreservation.yaml, blocked-edges/4.14.0-ec.1-AzureRegistryImagePreservation.yaml, blocked-edges/4.14.0-ec.2-AzureRegistryImagePreservation.yaml, blocked-edges/4.14.0-ec.3-AzureRegistryImagePreservation.yaml, blocked-edges/4.14.0-ec.4-AzureRegistryImagePreservation.yaml, blocked-edges/4.14.0-rc.0-AzureRegistryImagePreservation.yaml, blocked-edges/4.14.0-rc.1-AzureRegistryImagePreservation.yaml, blocked-edges/4.14.0-rc.2-AzureRegistryImagePreservation.yaml, blocked-edges/4.14.0-rc.3-AzureRegistryImagePreservation.yaml, blocked-edges/4.14.0-rc.4-AzureRegistryImagePreservation.yaml, blocked-edges/4.14.0-rc.5-AzureRegistryImagePreservation.yaml, blocked-edges/4.14.0-rc.6-AzureRegistryImagePreservation.yaml, blocked-edges/4.14.0-rc.7-AzureRegistryImagePreservation.yaml, blocked-edges/4.14.1-AzureRegistryImagePreservation.yaml, blocked-edges/4.14.10-AzureRegistryImagePreservation.yaml, blocked-edges/4.14.11-AzureRegistryImagePreservation.yaml, blocked-edges/4.14.12-AzureRegistryImagePreservation.yaml, blocked-edges/4.14.2-AzureRegistryImagePreservation.yaml, blocked-edges/4.14.3-AzureRegistryImagePreservation.yaml, blocked-edges/4.14.4-AzureRegistryImagePreservation.yaml, blocked-edges/4.14.5-AzureRegistryImagePreservation.yaml, blocked-edges/4.14.6-AzureRegistryImagePreservation.yaml, blocked-edges/4.14.7-AzureRegistryImagePreservation.yaml, blocked-edges/4.14.8-AzureRegistryImagePreservation.yaml, blocked-edges/4.14.9-AzureRegistryImagePreservation.yaml
Some clusters do not excercise the internal image registry, and we do not want to bother those admins about this risk.  Look at `imageregistry_request_duration_seconds_count` (which only records registry activity like `BlobStore.Create`) as a sign that the registry is actively used to handle images.  Compare with
`imageregistry_http_request_duration_seconds_count`, which the registry serves even when it is not actively being used to manage images, as a sign that registry metrics are working, to distinguish between "we know the registry is not being used" and "registry metrics collection is broken, and we're blind to registry use".
[In 4.14, the registry component became an optional component][1], but it is not optional in 4.13.  And it's 4.13 clusters evaluating this PromQL because of the …
=> IR-461: blocked-edges/4.14.*-AzureRegistryImagePreservation: Look for active registry use

blocked-edges/4.14.13-AzureRegistryImagePreservation.yaml
As the fix is not available in 4.14.13
=> Extending AzureRegistryImagePreservation

blocked-edges/4.14.10-AWSCustomDomainNodesNotReady.yaml
`hack/stabilization-changes.py` doesn't need this, because 4.14.11 has been through all its promotions, but it's nice to have around for consistency with our other recent risks, which explicitly declare a fixedIn.
[OCPBUGS-27362][1]:
> Since the problem described in this issue should be resolved in a recent advisory, it has been closed.
>
> For information on the advisory (Critical: OpenShift Container Platform 4.14.11 bug fix and security update), and where to find the updated files, follow the link below.
>
> If the solution does not work for you, open a new bug report.
> https://access.redhat.com/errata/RHSA-2024:0642
[1]: https://issues.redhat.com/browse/OCPBUGS-27362?focusedId=24096730&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-24096730
=> blocked-edges/4.14.10-AWSCustomDomainNodesNotReady: Explicit fixedIn: 4.14.11

blocked-edges/4.13.33-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml
Extending the risk for 4.13.34 as the bug is not available in the release.
=> Extending NetPolicyTimeoutsHostNetworkedPodTraffic

blocked-edges/4.12.49-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml
[4.12.50][1] contains [OCPBUGS-29302](https://issues.redhat.com/browse/OCPBUGS-29302).
[1]: https://amd64.ocp.releases.ci.openshift.org/releasestream/4-stable/release/4.12.50
=> blocked-edges/4.12.49-NetPolicyTimeoutsHostNetworkedPodTraffic: Fixed in 4.12.50

blocked-edges/4.15.0-rc.8-GCPMintModeRoleAdmin.yaml, build-suggestions/4.15.yaml
[4.14.14][1] contains [OCPBUGS-28231](https://issues.redhat.com/browse/OCPBUGS-28231).  Raising `minor_min` ensures the next 4.15 release built from that advice will not include update recommendations from any unguarded 4.14, and we can declare that 4.15.z as the fixedIn version and stop carrying the risk.  But rc.8 was built before we had the updated advice in place, and still includes the older 4.14.z as update sources:
```console
$ oc adm release info -o json quay.io/openshift-release-dev/ocp-release:4.15.0-rc.8-x86_64 | jq -c .metadata.previous
["4.14.10","4.14.11","4.14.12","4.14.13","4.14.14","4.14.9","4.15.0-ec.0",...
```
So extend the risk declaration to rc.8 as well.
[1]: https://amd64.ocp.releases.ci.openshift.org/releasestream/4-stable/release/4.14.14
=> *: 4.14.14 guards against GCPMintModeRoleAdmin

blocked-edges/4.14.14-AzureRegistryImagePreservation.yaml
[4.14.14][1] does not contain [OCPBUGS-29604](https://issues.redhat.com/browse/OCPBUGS-29604) or [OCPBUGS-29755](https://issues.redhat.com/browse/OCPBUGS-29755), although later accepted nightlies do and both bugs are `Verified` for 4.14.z.  Hopefully the next 4.14.z will have both fixes.
[1]: https://amd64.ocp.releases.ci.openshift.org/releasestream/4-stable/release/4.14.14
=> blocked-edges/4.14.13-AzureRegistryImagePreservation: Not fixed in 4.14.14

blocked-edges/4.15.0-rc.1-EarlyAPICertRotation.yaml, blocked-edges/4.15.0-rc.2-EarlyAPICertRotation.yaml, blocked-edges/4.15.0-rc.3-EarlyAPICertRotation.yaml, blocked-edges/4.15.0-rc.4-EarlyAPICertRotation.yaml, blocked-edges/4.15.0-rc.5-EarlyAPICertRotation.yaml, blocked-edges/4.15.0-rc.7-EarlyAPICertRotation.yaml, blocked-edges/4.15.0-rc.8-EarlyAPICertRotation.yaml
1228defeba53 (#4578) thought this was fixed in rc.1, but [apparently not][1].
```console
$ sed -i '/fixedIn/d' blocked-edges/4.15.0-rc.0-EarlyAPICertRotation.yaml
$ curl -s 'https://api.openshift.com/api/upgrades_info/graph?channel=candidate-4.15&arch=amd64' | jq -r '.nodes[] | .version' | grep '^4[.]15[.]' | grep -v '^4[.]15[.]0-\(ec\|rc[.]0\)' | while read VERSION; do sed "s/4.15.0-rc.0/${VERSION}/" blocked-edges/4.15.0-rc.0-EarlyAPICertRotation.yaml > "blocked-edges/${VERSION}-EarlyAPICertRotation.yaml"; done
```
[1]: https://issues.redhat.com/browse/API-1687?focusedId=24231419&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-24231419
=> API-1687: blocked-edges/4.15.0*-EarlyAPICertRotation: Extend to more recent RCs

blocked-edges/4.14.11-AWSCustomDomainNodesNotReady.yaml, blocked-edges/4.14.12-AWSCustomDomainNodesNotReady.yaml, blocked-edges/4.14.13-AWSCustomDomainNodesNotReady.yaml, blocked-edges/4.14.14-AWSCustomDomainNodesNotReady.yaml
/etc/kuberenetes/node.env is overwritten after node reboot.
=> extend AWSCustomDomainNodesNotReady for latest 4.14 versions

blocked-edges/4.15.0-ec.0-PreRelease.yaml, blocked-edges/4.15.0-ec.1-PreRelease.yaml, blocked-edges/4.15.0-ec.2-PreRelease.yaml, blocked-edges/4.15.0-ec.3-PreRelease.yaml, blocked-edges/4.15.0-rc.0-PreRelease.yaml, blocked-edges/4.15.0-rc.1-PreRelease.yaml, blocked-edges/4.15.0-rc.2-PreRelease.yaml, blocked-edges/4.15.0-rc.3-PreRelease.yaml, blocked-edges/4.15.0-rc.4-PreRelease.yaml, blocked-edges/4.15.0-rc.5-PreRelease.yaml, blocked-edges/4.15.0-rc.7-PreRelease.yaml, blocked-edges/4.15.0-rc.8-PreRelease.yaml, hack/release-ga.sh
Updating `release-ga.sh` to automate the process from 5592c462a9 (#4378), so we don't need to remember to declare these at GA-time, and running the new script on 4.15 to declare those risks.
=> blocked-edges/4.15.0-*-PreRelease: Declare prerelease risks and automate

blocked-edges/4.15.0-EarlyAPICertRotation.yaml, blocked-edges/4.15.0-rc.0-EarlyAPICertRotation.yaml, blocked-edges/4.15.0-rc.1-EarlyAPICertRotation.yaml, blocked-edges/4.15.0-rc.2-EarlyAPICertRotation.yaml, blocked-edges/4.15.0-rc.3-EarlyAPICertRotation.yaml, blocked-edges/4.15.0-rc.4-EarlyAPICertRotation.yaml, blocked-edges/4.15.0-rc.5-EarlyAPICertRotation.yaml, blocked-edges/4.15.0-rc.7-EarlyAPICertRotation.yaml, blocked-edges/4.15.0-rc.8-EarlyAPICertRotation.yaml
All clusters originally installed on OpenShift Container Platform (OCP) version 4.7 or earlier. Clusters installed on 4.8 or later and new 4.15 installs are unaffected.
due to history pruning in the CVO we cannot reliably detect born in versions less than 4.9.
Therefore the conditional update rule will be updated to omit update recommendations in all clusters born in 4.9 or earlier
=> modify EarlyAPICertRotation risk to include promql

blocked-edges/4.11.58-RHELKernelHighLoadIOWait.yaml, blocked-edges/4.12.48-RHELKernelHighLoadIOWait.yaml, blocked-edges/4.12.49-RHELKernelHighLoadIOWait.yaml, blocked-edges/4.12.50-RHELKernelHighLoadIOWait.yaml, blocked-edges/4.12.51-RHELKernelHighLoadIOWait.yaml
After rebooting into kernel-4.18.0-372.88.1.el8_6 or later kernel nodes experience high load average and io_wait times 
Nodes may fail to start or stop pods, probes may fail 
Workload and host processes may become unresponsive and workload may be disrupted
=> COS-2705: block edges for versions with 4.18.0-372.88.1.el8_6 or later kernel

blocked-edges/4.14.14-AzureRegistryImagePreservation.yaml
From  https://amd64.ocp.releases.ci.openshift.org/releasestream/4-stable/release/4.14.15
> [CLUSTER-IMAGE-REGISTRY-OPERATOR](https://github.com/openshift/cluster-image-registry-operator/tree/ecff6866688449079d2768c21081070cd7840fda)
> [OCPBUGS-28989](https://issues.redhat.com/browse/OCPBUGS-28989): pkg/storage/s3: enable bucket key on encryption settings [#995](https://github.com/openshift/cluster-image-registry-operator/pull/995)
> [OCPBUGS-29755](https://issues.redhat.com/browse/OCPBUGS-29755): azurepathfix: fix stack hub, government and workload identity setup [#1005](https://github.com/openshift/cluster-image-registry-operator/pull/1005)
> [OCPBUGS-29604](https://issues.redhat.com/browse/OCPBUGS-29604): move azure storage blobs from docker back into /docker …
=> AzureRegistryImagePreservation fixed in 4.14.15

blocked-edges/4.15.0-EarlyAPICertRotation.yaml
[4,15.2][1] contains [OCPBUGS-30304](https://issues.redhat.com/browse/OCPBUGS-30304), which addresses the CA-rotation trigger for clusters born in 4.7 or earlier.  We are still working on getting 4.15.z systems to respond gracefully when the rotation happens, e.g. backporting the changes in [OCPBUGS-25821](https://issues.redhat.com//browse/OCPBUGS-25821) to 4.15.z, but as far as we can tell, 4.15.2 clusters will no longer try and roll the `api-int` Certificate Authority, so we're no worse off there than in the 4.14 releases users would be updating from.
[1]: https://amd64.ocp.releases.ci.openshift.org/releasestream/4-stable/release/4.15.2
=> blocked-edges/4.15.0-EarlyAPICertRotation: Fixed in 4.15.2

blocked-edges/4.14.15-AWSCustomDomainNodesNotReady.yaml
[4.14.16][1] includes [OCPBUGS-29290](https://issues.redhat.com/browse/OCPBUGS-29290).
[1]: https://amd64.ocp.releases.ci.openshift.org/releasestream/4-stable/release/4.14.16
=> blocked-edges/4.14.15-AWSCustomDomainNodesNotReady: Fixed in 4.14.16

blocked-edges/4.12.51-RHELKernelHighLoadIOWait.yaml
The 4.12.52 name was burned without adding a release to candidate channels.  4.12.53 addresses this issue, [showing][1]:
> Red Hat Enterprise Linux CoreOS upgraded from 412.86.202402272018-0 to 412.86.202403120448-0 ([diff][2])
And [that diff][2] (internal only, sorry!):
> Package (NEVR)	412.86.202402272018-0	412.86.202403120448-0
> ...
> kernel	kernel-0-4.18.0-372.93.1.el8_6-x86_64	kernel-0-4.18.0-372.96.1.el8_6-x86_64
> ...
which aligns with [Scott's][3]:
> The kernel-4.18.0-372.96.1.el8_6...
so the bug is fixed in 4.12.53.
[1]: https://amd64.ocp.releases.ci.openshift.org/releasestream/4-stable/release/4.12.53?from=4.12.51
[2]: https://releases-rhcos-art.apps.ocp-virt.prod.psi.redhat.com/diff.html?arch=x86_64&first_release=412.86.202402272018-0&first_stream=prod%2Fstreams%2F4.12&second_r …
=> blocked-edges/4.12.51-RHELKernelHighLoadIOWait: Fixed in 4.12.53

build-suggestions/4.16.yaml
[4.16.0-ec.1][1] includes [OCPBUGS-26067](https://issues.redhat.com/browse/OCPBUGS-26067), making it compatible with the coming openshift/api#1817 that will bring the [Common Expression Language (CEL)][4] `isIP` and similar into the Infrastucture CRD.  The Infrastructure CRD using `isIP` comes at run level 10, before the Kubernetes API server, which comes at run level 20:
```console
$ oc adm release extract --to manifests quay.io/openshift-release-dev/ocp-release:4.16.0-ec.4-x86_64
Extracted release payload from digest sha256:1d715a60966e3c3215c046ac2c70efbe81dcb288d0b0223597cdae35c0c89d61 created at 2024-03-12T20:22:54Z
$ grep -rl infrastructures manifests | grep crd
manifests/0000_10_config-operator_01_infrastructure-CustomNoUpgrade.crd.yaml …
```
=> API-1793: build-suggestions/4.16: Raise z_min to ec.1

blocked-edges/4.12.51-HighNodeStatusReportFrequency.yaml, blocked-edges/4.13.33-HighNodeStatusReportFrequency.yaml, blocked-edges/4.13.34-HighNodeStatusReportFrequency.yaml, blocked-edges/4.13.35-HighNodeStatusReportFrequency.yaml, blocked-edges/4.13.36-HighNodeStatusReportFrequency.yaml, blocked-edges/4.14.12-HighNodeStatusReportFrequency.yaml, blocked-edges/4.14.13-HighNodeStatusReportFrequency.yaml, blocked-edges/4.14.14-HighNodeStatusReportFrequency.yaml, blocked-edges/4.14.15-HighNodeStatusReportFrequency.yaml
Regressions to 10s occured in:
OCPBUGS-15583, 4.15.0
OCPBUGS-28379, 4.14.12
OCPBUGS-29151, 4.13.33
OCPBUGS-29366, 4.12.51
Recovery to 5m occured in:
OCPBUGS-29713, 4.16
OCPBUGS-29797, 4.15.2
OCPBUGS-30225, 4.14.16
OCPBUGS-30285, 4.13.37
OCPBUGS-30329, 4.12.53
=> MCO-1094: blocked-edges: Declare HighNodeStatusReportFrequency

blocked-edges/4.11.58-RHELKernelHighLoadIOWait.yaml
[Scott][1]:
> I've verified that 4.11.59 has the desired kernel, editted for clarity
>
> ```console
> $ oc get clusterversion
> NAME      VERSION   AVAILABLE   PROGRESSING   SINCE   STATUS
> version   4.11.59   True        False         114s    Cluster version is 4.11.59
>
> $ oc get nodes -o wide
> NAME                                     OS-IMAGE               KERNEL-VERSION
> ci-ln-impy1ik-72292-72vz9-master-0       411.86.202403120448-0  4.18.0-372.96.1.el8_6.x86_64
> ci-ln-impy1ik-72292-72vz9-master-1       411.86.202403120448-0  4.18.0-372.96.1.el8_6.x86_64
> ci-ln-impy1ik-72292-72vz9-master-2       411.86.202403120448-0  4.18.0-372.96.1.el8_6.x86_64
> ci-ln-impy1ik-72292-72vz9-worker-a-hl79v 411.86.202403120448-0  4.18.0-372.96.1.el8_6.x86_64
> …
```
=> blocked-edges/4.11.58-RHELKernelHighLoadIOWait: Fixed in 4.11.59

blocked-edges/4.13.38-AcceleratedNetworkingRace.yaml
[OCPBUGS-30256](https://issues.redhat.com/browse/OCPBUGS-30256) is still `Assigned`, although nmstate/nmstate#2573 did merge a few days ago.
=> blocked-edges/4.13.38-AcceleratedNetworkingRace: Not fixed in 4.13.38

blocked-edges/4.15.2-EarlyAPICertRotation.yaml, blocked-edges/4.15.3-EarlyAPICertRotation.yaml
21684f75cc (#4898) thought this was fixed, but apparently not [OCPBUGS-31384](https://issues.redhat.com/browse/OCPBUGS-31384).
=> API-1687: blocked-edges/4.15.3-EarlyAPICertRotation: Extend to 4.15.2 and .3

blocked-edges/4.15.5-EarlyAPICertRotation.yaml
[OCPBUGS-31384](https://issues.redhat.com/browse/OCPBUGS-31384) is still `New`.
=> blocked-edges/4.15.5-EarlyAPICertRotation: Not fixed in 4.15.5

blocked-edges/4.15.6-EarlyAPICertRotation.yaml
https://issues.redhat.com/browse/OCPBUGS-31384 is still in new
=> blocked-edges/4.15.6-EarlyAPICertRotation: Not fixed in 4.15.6

blocked-edges/4.15.7-EarlyAPICertRotation.yaml
https://issues.redhat.com/browse/OCPBUGS-31384 still in `POST`, no backports yet
=> blocked-edges: `EarlyAPICertRotation` not fixed in 4.15.7

blocked-edges/4.15.8-EarlyAPICertRotation.yaml
https://issues.redhat.com/browse/OCPBUGS-31384 still in `POST`, no
backports yet
=>   blocked-edges: `EarlyAPICertRotation` not fixed in 4.15.8

blocked-edges/4.13.39-AcceleratedNetworkingRace.yaml
4.13.39 does not contain the fix. Details available [internally](https://redhat-internal.slack.com/archives/C02MX20TV24/p1712324587997789?thread_ts=1712322104.197949&cid=C02MX20TV24).
=> blocked-edges: extend `AcceleratedNetworkingRace` to 4.13.39

blocked-edges/4.16.0-ec.4-CSRNotApprovedBadCerts.yaml
Limit the exposed clusters to ones installed as 4.13 or lower, as described in [MCO-1091](https://issues.redhat.com//browse/MCO-1091).
=> MCO-1091: blocked-edge: set up `CSRNotApprovedBadCerts` on 4.16.0-ec.4

blocked-edges/4.16.0-ec.4-CSRNotApprovedBadCerts.yaml
As OCPBUGS-31067  is fixed in 4.16.0-ec.5
=> Adding the fixedIn to CSRNotApprovedBadCerts

blocked-edges/4.15.8-AWSCustomDomainNodesNotReady.yaml, blocked-edges/4.15.9-EarlyAPICertRotation.yaml
As the bugfix of OCPBUGS-31807 is not in a 4.15.z version
=> Extending the risk to 4.15.9 and adding fixedIn for 4.15.8

blocked-edges/4.15.0-OLMOperatorsInFailedState.yaml, blocked-edges/4.15.2-OLMOperatorsInFailedState.yaml, blocked-edges/4.15.3-OLMOperatorsInFailedState.yaml, blocked-edges/4.15.5-OLMOperatorsInFailedState.yaml, blocked-edges/4.15.6-OLMOperatorsInFailedState.yaml, blocked-edges/4.15.7-OLMOperatorsInFailedState.yaml, blocked-edges/4.15.8-OLMOperatorsInFailedState.yaml, blocked-edges/4.15.9-OLMOperatorsInFailedState.yaml
Both OCPBUGS-31080 and OCPBUGS-24009 has same symptoms and mostlikely related. We are adding a single risk for both of these bugs. However if we come to know if these bugs are separate then we will add separate risks.
Used below script to generate the files
$ curl -s 'https://api.openshift.com/api/upgrades_info/graph?channel=candidate-4.15&arch=amd64' | jq -r '.nodes[] | .version' | grep '^4[.]15[.]' | grep -v '^4[.]15[.]0' | grep -v '0-[er]c[.]'| while read VERSION; do sed "s/4.15.0/${VERSION}/" blocked-edges/4.15.0-OLMOperatorsInFailedState.yaml > "blocked-edges/${VERSION}-OLMOperatorsInFailedState.yaml"; done
=> OPRUN-3267: Adding OLMOperatorsInFailedState risk

blocked-edges/4.12.45-AMD19hFirmware.yaml, blocked-edges/4.12.46-AMD19hFirmware.yaml, blocked-edges/4.12.47-AMD19hFirmware.yaml, blocked-edges/4.12.48-AMD19hFirmware.yaml, blocked-edges/4.12.49-AMD19hFirmware.yaml, blocked-edges/4.12.50-AMD19hFirmware.yaml, blocked-edges/4.12.51-AMD19hFirmware.yaml
The `h` suffix in `19h` stands for "hexadecimal", so `19h` is decimal 25. The first `group by` matches CPUs exposed to the firmware bug with a value of one.  The second `group by` shows that the `node_cpu_info` metric is working on at least some nodes.
I'm preserving `vendor` and `family` in the groupings, because it's nice to be able to say "we aren't matching this risk for your cluster, because we see..." and then point out an Intel CPU, or an AMD CPU with a different family, or some other example of why we don't think the risk applies to that cluster.  The `topk` ensures that if we have both risk-matching CPUs and non-matching CPUs, we prefer the matching result (value 1) over the non-matching result(s) (value 0).
The `_id=""` portion is a pattern to support HyperShift and other …
=> COS-2747: blocked-edges/4.12.*: Declare AMD19hFirmware

blocked-edges/4.14.15-AzureRegistryImageMigrationUserProvisioned.yaml, blocked-edges/4.14.16-AzureRegistryImageMigrationUserProvisioned.yaml, blocked-edges/4.14.17-AzureRegistryImageMigrationUserProvisioned.yaml, blocked-edges/4.14.18-AzureRegistryImageMigrationUserProvisioned.yaml, blocked-edges/4.14.19-AzureRegistryImageMigrationUserProvisioned.yaml, blocked-edges/4.14.20-AzureRegistryImageMigrationUserProvisioned.yaml, blocked-edges/4.14.21-AzureRegistryImageMigrationUserProvisioned.yaml
Generated by writing the 4.14.15 risk, and then copying out to later 4.14.z through the most recent 4.14.21:
```console
$ tail -n2  channels/candidate-4.14.yaml
- 4.14.20
- 4.14.21
```
with:
```console
$ for Z in $(seq 16 21); do sed "s/4.14.15/4.14.${Z}/" blocked-edges/4.14.15-AzureRegistryImageMigrationUserProvisioned.yaml > "blocked-edges/4.14.${Z}-AzureRegistryImageMigrationUserProvisioned.yaml"; done
```
I'm not currently clear on whether updates from `4.14.(<15)` are also exposed; if they are, we can follow up with a bump to the `from` regular expression.
=> IR-468: blocked-edges/4.14.*: Declare AzureRegistryImageMigrationUserProvisioned

blocked-edges/4.15.0-AzureRegistryImageMigrationUserProvisioned.yaml, blocked-edges/4.15.2-AzureRegistryImageMigrationUserProvisioned.yaml, blocked-edges/4.15.3-AzureRegistryImageMigrationUserProvisioned.yaml, blocked-edges/4.15.5-AzureRegistryImageMigrationUserProvisioned.yaml, blocked-edges/4.15.6-AzureRegistryImageMigrationUserProvisioned.yaml, blocked-edges/4.15.7-AzureRegistryImageMigrationUserProvisioned.yaml, blocked-edges/4.15.8-AzureRegistryImageMigrationUserProvisioned.yaml, blocked-edges/4.15.9-AzureRegistryImageMigrationUserProvisioned.yaml
[Flavian pointed out][1] that [OCPBUGS-29525](https://issues.redhat.com/browse/OCPBUGS-29525) took the regression into 4.15.0, so 4.14.(<15) updates into all existing 4.15.z are also exposed, until a fix gets back to a future 4.15.z.
[1]: https://issues.redhat.com/browse/IR-468?focusedId=24553962&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-24553962
=> IR-468: blocked-edges/4.15.*: Declare AzureRegistryImageMigrationUserProvisioned

hack/stabilization-changes.py
0f20360dc0 (#5119) pivoted this script to warning about patch update concerns regardless of whether a channel had pending candidates.  But warning every hourly poll for every channel with patch update concerns is too much noise.  This commit uses the already-existing `waiting_notifications` to batch these up in the daily status update instead.
=> hack/stabilization-changes: Daily get_concerns_about_patch_updates

hack/stabilization-changes.py
0b160190cb (#5128) moved `waiting_notifications` from `kwargs` into an explicitly handled argument in `stabilize_channel`.  That means we need to explicitly pass it down into `stabilize_version` to keep those version notifications in the daily batch message.
=> hack/stabilization-changes: Restore waiting_notifications in stabilize_version

blocked-edges/4.15.10-OLMOperatorsInFailedState.yaml
I'm a bit confused by the current state of [OPRUN-3267](https://issues.redhat.com/browse/OPRUN-3267).  I see:
* openshift/operator-framework-olm#736, although [that seems to have just-missed 4.15.10][3].
* openshift/operator-framework-olm#738, which is still in flight.
I'm not sure if we're waiting for both or not, but either way, 4.15.10 doesn't have what we need, so I'm extending that risk here.
[3]: https://amd64.ocp.releases.ci.openshift.org/releasestream/4.15.0-0.nightly/release/4.15.0-0.nightly-2024-04-19-015656?from=4.15.10
=> OPRUN-3267: blocked-edges/4.15.10-OLMOperatorsInFailedState: Not fixed yet

blocked-edges/4.15.9-EarlyAPICertRotation.yaml
We thought this was fixed in rc.1, but it wasn't, c74c248daf (#4841).
Then we thought it was fixed in 4.15.2, but it wasn't, b474a45779 (#4981).
Now we think it's fixed in [4.15.10][1], wihch contains all three of:
* openshift/cluster-kube-apiserver-operator#1662: OCPBUGS-31807: Use RotatedSigningCASecret in update only mode
* openshift/cluster-kube-controller-manager-operator#801: OCPBUGS-31807: use RotatedSigningCASecret and RotatedSelfSignedCertKeySecret only in update mode
* openshift/kubernetes#1939: OCPBUGS-31807: UPSTREAM: <carry>: allow type mutation for specific secrets
[1]: https://amd64.ocp.releases.ci.openshift.org/releasestream/4-stable/release/4.15.10
=> API-1687: blocked-edges/4.15.9-EarlyAPICertRotation: Fixed in 4.15.10

blocked-edges/4.16.0-ec.0-CRIAuthPluginRHEL.yaml, blocked-edges/4.16.0-ec.1-CRIAuthPluginRHEL.yaml, blocked-edges/4.16.0-ec.2-CRIAuthPluginRHEL.yaml, blocked-edges/4.16.0-ec.3-CRIAuthPluginRHEL.yaml, blocked-edges/4.16.0-ec.4-CRIAuthPluginRHEL.yaml, blocked-edges/4.16.0-ec.5-CRIAuthPluginRHEL.yaml
Generated by writing the ec.0 risk manually, and copying out to the other candidate 4.16 with:
```console
$ curl -s 'https://api.openshift.com/api/upgrades_info/graph?channel=candidate-4.16&arch=amd64' | jq -r '.nodes[] | .version' | grep '^4[.]16[.]' | grep -v '^4[.]16[.]0-ec[.]0' | while read VERSION; do sed "s/4.16.0-ec.0/${VERSION}/" blocked-edges/4.16.0-ec.0-CRIAuthPluginRHEL.yaml > "blocked-edges/${VERSION}-CRIAuthPluginRHEL.yaml"; done
```
=> OCPCLOUD-2582: blocked-edges/4.16.*: Declare CRIAuthPluginRHEL

blocked-edges/4.14.15-AzureRegistryImageMigrationUserProvisioned.yaml, blocked-edges/4.14.16-AzureRegistryImageMigrationUserProvisioned.yaml, blocked-edges/4.14.17-AzureRegistryImageMigrationUserProvisioned.yaml, blocked-edges/4.14.18-AzureRegistryImageMigrationUserProvisioned.yaml, blocked-edges/4.14.19-AzureRegistryImageMigrationUserProvisioned.yaml, blocked-edges/4.14.20-AzureRegistryImageMigrationUserProvisioned.yaml, blocked-edges/4.14.21-AzureRegistryImageMigrationUserProvisioned.yaml, blocked-edges/4.15.0-AzureRegistryImageMigrationUserProvisioned.yaml, blocked-edges/4.15.2-AzureRegistryImageMigrationUserProvisioned.yaml, blocked-edges/4.15.3-AzureRegistryImageMigrationUserProvisioned.yaml, blocked-edges/4.15.5-AzureRegistryImageMigrationUserProvisioned.yaml, blocked-edges/4.15.6-AzureRegistryImageMigrationUserProvisioned.yaml, blocked-edges/4.15.7-AzureRegistryImageMigrationUserProvisioned.yaml, blocked-edges/4.15.8-AzureRegistryImageMigrationUserProvisioned.yaml
`kube_secret_info` metric should be using `secret=` not `name=`.
=> IR-468: blocked-edges/: Fix PromQL Metric on AzureRegistryImageMigrationUserProvisioned

blocked-edges/4.14.22-AzureRegistryImageMigrationUserProvisioned.yaml
[OCPBUGS-32450](https://issues.redhat.com/browse/OCPBUGS-32450) is still `POST` for 4.14.
Self-LGTM, because it's late for everyone else.
=> IR-468: blocked-edges/4.14.22-AzureRegistryImageMigrationUserProvisioned: Not fixed yet

blocked-edges/4.14.22-AzureRegistryImageMigrationUserProvisioned.yaml
Tracked via https://issues.redhat.com/browse/OCPBUGS-32450
=> AzureRegistryImageMigrationUserProvisioned fixed in 4.14.23

blocked-edges/4.15.10-OLMOperatorsInFailedState.yaml
[4.15.11][1] includes [OCPBUGS-32311][2].  In cb0259d7e7 (#5132), I'd also thought [OCPBUGS-32439][3] might be relevant, but [it turns out it isn't][4].
[1]: https://amd64.ocp.releases.ci.openshift.org/releasestream/4-stable/release/4.15.11
[2]: https://issues.redhat.com/browse/OCPBUGS-32311
[3]: https://issues.redhat.com/browse/OCPBUGS-32439
[4]: https://issues.redhat.com/browse/OCPBUGS-32439?focusedId=24599986&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-24599986
=> OPRUN-3267: blocked-edges/4.15.10-OLMOperatorsInFailedState: Fixed in 4.15.11

blocked-edges/4.16.0-ec.6-CRIAuthPluginRHEL.yaml, build-suggestions/4.16.yaml
[CRIAuthPluginRHEL: Extend to 4.16.0-ec.6](https://github.com/openshift/cincinnati-graph-data/commit/b4c086ffd7cbd84672e57f6be9982817dfd6f661)
`CRIAuthPluginRHEL` is a risk that needs to be fixed in the outbound version. OCPBUGS-30970 is fixed in 4.15.11 so extend the risk only for edges from 4.15.10 and lower.
---
[Bump minor_min to 4.15.11 to avoid CRIAuthPluginRHEL](https://github.com/openshift/cincinnati-graph-data/commit/14aaacebc197c62230eaa8187cb8e5c7857f1f8c)
=> `CRIAuthPluginRHEL`: Extend to 4.16.0-ec.6 and bump `minor_min` to 4.15.11

blocked-edges/4.16.0-ec.0-CRIAuthPluginRHEL.yaml, blocked-edges/4.16.0-ec.1-CRIAuthPluginRHEL.yaml, blocked-edges/4.16.0-ec.2-CRIAuthPluginRHEL.yaml, blocked-edges/4.16.0-ec.3-CRIAuthPluginRHEL.yaml, blocked-edges/4.16.0-ec.4-CRIAuthPluginRHEL.yaml, blocked-edges/4.16.0-ec.5-CRIAuthPluginRHEL.yaml, blocked-edges/4.16.0-ec.6-CRIAuthPluginRHEL.yaml, blocked-edges/4.16.0-rc.0-CRIAuthPluginRHEL.yaml
Recent `minor_min` bump to 4.15.11 for some reason did not propagate to 4.16.0-rc.0 ([Slack convo with ART](https://redhat-internal.slack.com/archives/CB95J6R4N/p1715163952815869) so we need to extend, but we can limit the risks to edges from <=4.15.10
=> `CRIAuthPluginRHEL`: Extend to 4.16.0-rc.0 but limit outgoing to <=4.15.11

blocked-edges/4.14.0-IngressDegradedOnRouterReloads.yaml, blocked-edges/4.14.1-IngressDegradedOnRouterReloads.yaml, blocked-edges/4.14.10-IngressDegradedOnRouterReloads.yaml, blocked-edges/4.14.11-IngressDegradedOnRouterReloads.yaml, blocked-edges/4.14.12-IngressDegradedOnRouterReloads.yaml, blocked-edges/4.14.13-IngressDegradedOnRouterReloads.yaml, blocked-edges/4.14.14-IngressDegradedOnRouterReloads.yaml, blocked-edges/4.14.15-IngressDegradedOnRouterReloads.yaml, blocked-edges/4.14.16-IngressDegradedOnRouterReloads.yaml, blocked-edges/4.14.17-IngressDegradedOnRouterReloads.yaml, blocked-edges/4.14.18-IngressDegradedOnRouterReloads.yaml, blocked-edges/4.14.19-IngressDegradedOnRouterReloads.yaml, blocked-edges/4.14.2-IngressDegradedOnRouterReloads.yaml, blocked-edges/4.14.20-IngressDegradedOnRouterReloads.yaml, blocked-edges/4.14.21-IngressDegradedOnRouterReloads.yaml, blocked-edges/4.14.22-IngressDegradedOnRouterReloads.yaml, blocked-edges/4.14.3-IngressDegradedOnRouterReloads.yaml, blocked-edges/4.14.4-IngressDegradedOnRouterReloads.yaml, blocked-edges/4.14.5-IngressDegradedOnRouterReloads.yaml, blocked-edges/4.14.6-IngressDegradedOnRouterReloads.yaml, blocked-edges/4.14.7-IngressDegradedOnRouterReloads.yaml, blocked-edges/4.14.8-IngressDegradedOnRouterReloads.yaml, blocked-edges/4.14.9-IngressDegradedOnRouterReloads.yaml
OTA consensus was to declare this risk once a fixed version in present in the stable channel, which was expedited for 4.14.23 and it went to stable via https://github.com/openshift/cincinnati-graph-data/pull/5214
I was thinking of maybe making this a conditional risk based on the count of Routes in the cluster, but without knowing a good threshold I would be just speculating. We have a fixed 4.14.23, lets steer folks towards it.
=> NE-1689: Declare `IngressDegradedOnRouterReloads` for <4.14.23

blocked-edges/4.14.0-ReconciledPlatformSCC.yaml
4.14.0 is the only 4.14 with updates from 4.13 versions without a CVO gate that sets `Upgradeable=False` when it detect user-modified platform SCCs (OCPBUGS-19465). We want to steer 4.13 clusters to pass this gate, so lets set up an `Always` risk to discourage folks from taking these two exposed edges.
```console
$ oc adm release info quay.io/openshift-release-dev/ocp-release:4.14.1-x86_64 | grep Upgrades
Upgrades: 4.13.19, 4.14.0-ec.0, 4.14.0-ec.1, 4.14.0-ec.2, 4.14.0-ec.3, 4.14.0-ec.4, 4.14.0-rc.0, 4.14.0-rc.1, 4.14.0-rc.2, 4.14.0-rc.3, 4.14.0-rc.4, 4.14.0-rc.5, 4.14.0-rc.6, 4.14.0-rc.7, 4.14.0
$ oc adm release info quay.io/openshift-release-dev/ocp-release:4.14.0-x86_64 | grep Upgrades
Upgrades: 4.13.17, 4.13.18, 4.13.19, 4.14.0-ec.0, 4.14.0-ec.1, 4.14.0-ec.2, 4.14.0-ec.3, 4.14.0-ec.4, …
```
=> Declare `ReconciledPlatformSCC` for 4.13.{17,18} -> 4.14.0

blocked-edges/4.14.0-AWSECRLegacyCredProvider.yaml, blocked-edges/4.14.0-AzureDefaultVMType.yaml, blocked-edges/4.14.0-AzureRegistryImagePreservation.yaml, blocked-edges/4.14.0-ConsoleImplicitlyEnabled.yaml, blocked-edges/4.14.0.yaml
Generated with https://github.com/petr-muller/ota/tree/main/cmd/graph-extend-or-fix by basically extending backwards:
```console
for risk in AWSCustomDomainNodesNotReady AWSECRLegacyCredProvider AzureDefaultVMType AzureRegistryImagePreservation ConsoleImplicitlyEnabled IngressDegradedOnRouterReloads
go run ./cmd/graph-extend-or-fix/... --jira-endpoint=https://issues.redhat.com/ --jira-bearer-token-file=$HOME/Temporary/jira-upgradeblocker-token --graph-repository-path=/home/pmuller/Projects/RH/github.com/openshift/cincinnati-graph-data --risk=$risk --last=4.14.1 --new=4.14.0 --do=extend
end
```
I have not included the formatting changes in AWSCustomDomainNodesNotReady and IngressDegradedOnRouterReloads that already existed on 4.14.0
Initially we wanted to silently drop the 4.14.0 release …
=> Backfill 4.14.0 risks from 4.14.1 and remove 4.14.0 drop

blocked-edges/4.15.0-ServiceAccountsOAuth.yaml, blocked-edges/4.15.10-ServiceAccountsOAuth.yaml, blocked-edges/4.15.11-ServiceAccountsOAuth.yaml, blocked-edges/4.15.12-ServiceAccountsOAuth.yaml, blocked-edges/4.15.2-ServiceAccountsOAuth.yaml, blocked-edges/4.15.3-ServiceAccountsOAuth.yaml, blocked-edges/4.15.5-ServiceAccountsOAuth.yaml, blocked-edges/4.15.6-ServiceAccountsOAuth.yaml, blocked-edges/4.15.7-ServiceAccountsOAuth.yaml, blocked-edges/4.15.8-ServiceAccountsOAuth.yaml, blocked-edges/4.15.9-ServiceAccountsOAuth.yaml
~~PromQL works as expected on enabled capability, disabled capability, and defensively, on clusters that are somehow not aware a capability:~~
Trevor suggested we pivot to checking the presence of scaled-up image registry deployment:
cluster runs 2 replicas of registry
first is "no such deployment" -> 1
second is "scaled beyond threshold" -> 0
third is "scaled below threshold" -> 1
For production PromQL we just check the threshold is 0, not 2
=> AUTH-517: Declare `ServiceAccountsOAuth` for cluster with disabled registry

blocked-edges/4.14.24-CephCapDropPanic.yaml, blocked-edges/4.15.12-CephCapDropPanic.yaml
Refs:
https://issues.redhat.com/browse/OCPBUGS-33250
https://issues.redhat.com/browse/OCPBUGS-33251
=> CephCapDropPanic fixedIn 4.14.25 and 4.15.13

blocked-edges/4.12.56-CephCapDropPanic.yaml
Ref: https://issues.redhat.com/browse/OCPBUGS-33253
=> CephCapDropPanic fixed in 4.12.57

blocked-edges/4.16.0-rc.0-CRIAuthPluginRHEL.yaml
rc.1 is built with the updated update sources:
```console
$ oc adm release info quay.io/openshift-release-dev/ocp-release:4.16.0-rc.1-x86_64 | grep Upgrade
Upgrades: 4.15.11, 4.15.12, 4.15.13, 4.16.0-ec.1, 4.16.0-ec.2, 4.16.0-ec.3, 4.16.0-ec.4, 4.16.0-ec.5, 4.16.0-ec.6, 4.16.0-rc.0
```
=> OCPCLOUD-2582: blocked-edges/4.16.0-rc.0-CRIAuthPluginRHEL: Fixed in rc.1

blocked-edges/4.13.41-CephCapDropPanic.yaml
[4.13.42][1] has:
> Red Hat Enterprise Linux CoreOS upgraded from 413.92.202404232117-0 to 413.92.202405132113-0 ([diff][2])
[that diff][2] (internal only, sorry external folks) has:
> Package (NEVR)	413.92.202404232117-0	413.92.202405132113-0
> ...
> kernel	kernel-0-5.14.0-284.64.1.el9_2-x86_64	kernel-0-5.14.0-284.66.1.el9_2-x86_64
66 is [RHSA-2024:2845][4], which is linked from [RHEL-33001][3] tracking the Ceph fix.
[1]: https://amd64.ocp.releases.ci.openshift.org/releasestream/4-stable/release/4.13.42
[2]: https://releases-rhcos-art.apps.ocp-virt.prod.psi.redhat.com/diff.html?arch=x86_64&first_release=413.92.202404232117-0&first_stream=prod%2Fstreams%2F4.13-9.2&second_release=413.92.202405132113-0&second_stream=prod%2Fstreams%2F4.13-9.2
[3]: …
=> blocked-edges/4.13.41-CephCapDropPanic: Fixed in 4.13.42

blocked-edges/4.15.14-ServiceAccountsOAuth.yaml
[OCPBUGS-33210][1] is still POST.
```console
$ sed 's/4[.]15[.]13/4.15.14/' blocked-edges/4.15.13-ServiceAccountsOAuth.yaml
```
[1]: https://issues.redhat.com/browse/OCPBUGS-33210
=> AUTH-517: blocked-edges/4.15.14-ServiceAccountsOAuth: Not fixed

blocked-edges/4.15.14-ServiceAccountsOAuth.yaml
[4.15.15][1] contains both non-library [OCPBUGS-33210][2] pulls, and OCPBUGS-33210 is `Verified` to show that's sufficient.
[1]: https://amd64.ocp.releases.ci.openshift.org/releasestream/4-stable/release/4.15.15
[2]: https://issues.redhat.com/browse/OCPBUGS-33210
=> AUTH-517: blocked-edges/4.15.14-ServiceAccountsOAuth: Fixed in 4.15.15

build-suggestions/4.16.yaml
[4.15.17][1] has [OCPBUGS-33984][2], and we want that in front of every admin taking a 4.15 cluster to a supported 4.16 release.
[1]: https://amd64.ocp.releases.ci.openshift.org/releasestream/4-stable/release/4.15.17
[2]: https://issues.redhat.com/browse/OCPBUGS-33984
=> OCPBUGS-33984: build-suggestions/4.16: Set minor_min to 4.15.17

blocked-edges/4.14.29-OVNInterConnectTransitionIPsec.yaml
[OCPBUGS-34885][1] is still POST for 4.14.z.
[1]: https://issues.redhat.com/browse/OCPBUGS-34885
=> SDN-4871: blocked-edges/4.14.29-OVNInterConnectTransitionIPsec: Not fixed yet

blocked-edges/4.17.0-ec.0-TechPreviewSignatureStoresInDefault.yaml
Extending 05fd35c534 (#5370)'s risk to 4.17.0-ec.0, now that da71109551 (#5374) showed that was a signed release.
=> OTA-1297: blocked-edges/4.17.0-ec.0-TechPreviewSignatureStoresInDefault: Not fixed yet

blocked-edges/4.14.0-ARODNSWrongBootSequence.yaml, blocked-edges/4.14.1-ARODNSWrongBootSequence.yaml, blocked-edges/4.14.10-ARODNSWrongBootSequence.yaml, blocked-edges/4.14.11-ARODNSWrongBootSequence.yaml, blocked-edges/4.14.12-ARODNSWrongBootSequence.yaml, blocked-edges/4.14.13-ARODNSWrongBootSequence.yaml, blocked-edges/4.14.14-ARODNSWrongBootSequence.yaml, blocked-edges/4.14.15-ARODNSWrongBootSequence.yaml, blocked-edges/4.14.16-ARODNSWrongBootSequence.yaml, blocked-edges/4.14.17-ARODNSWrongBootSequence.yaml, blocked-edges/4.14.18-ARODNSWrongBootSequence.yaml, blocked-edges/4.14.19-ARODNSWrongBootSequence.yaml, blocked-edges/4.14.2-ARODNSWrongBootSequence.yaml, blocked-edges/4.14.20-ARODNSWrongBootSequence.yaml, blocked-edges/4.14.21-ARODNSWrongBootSequence.yaml, blocked-edges/4.14.22-ARODNSWrongBootSequence.yaml, blocked-edges/4.14.23-ARODNSWrongBootSequence.yaml, blocked-edges/4.14.24-ARODNSWrongBootSequence.yaml, blocked-edges/4.14.25-ARODNSWrongBootSequence.yaml, blocked-edges/4.14.26-ARODNSWrongBootSequence.yaml, blocked-edges/4.14.27-ARODNSWrongBootSequence.yaml, blocked-edges/4.14.28-ARODNSWrongBootSequence.yaml.yaml, blocked-edges/4.14.29-ARODNSWrongBootSequence.yaml.yaml, blocked-edges/4.14.3-ARODNSWrongBootSequence.yaml, blocked-edges/4.14.4-ARODNSWrongBootSequence.yaml, blocked-edges/4.14.5-ARODNSWrongBootSequence.yaml, blocked-edges/4.14.6-ARODNSWrongBootSequence.yaml, blocked-edges/4.14.7-ARODNSWrongBootSequence.yaml, blocked-edges/4.14.8-ARODNSWrongBootSequence.yaml, blocked-edges/4.14.9-ARODNSWrongBootSequence.yaml
Adds conditional edges to the ARO Service for 4.14 versions. Because Systemd Boot Order puts ARO DNSMasq too late.
=> Block 4.14 due to bad boot order

README.md
The typo snuck in with d272cd694c (#3955).
=> README: Fix "sentance" -> "sentence" typo

blocked-edges/4.14.29-OpenStackAvailabilityZoneOutOfRange.yaml, blocked-edges/4.14.30-OpenStackAvailabilityZoneOutOfRange.yaml, blocked-edges/4.15.15-OpenStackAvailabilityZoneOutOfRange.yaml, blocked-edges/4.15.16-OpenStackAvailabilityZoneOutOfRange.yaml, blocked-edges/4.15.17-OpenStackAvailabilityZoneOutOfRange.yaml, blocked-edges/4.15.18-OpenStackAvailabilityZoneOutOfRange.yaml, blocked-edges/4.16.0-ec.6-OpenStackAvailabilityZoneOutOfRange.yaml, blocked-edges/4.16.0-rc.0-OpenStackAvailabilityZoneOutOfRange.yaml, blocked-edges/4.16.0-rc.1-OpenStackAvailabilityZoneOutOfRange.yaml, blocked-edges/4.16.0-rc.2-OpenStackAvailabilityZoneOutOfRange.yaml, blocked-edges/4.16.0-rc.3-OpenStackAvailabilityZoneOutOfRange.yaml, blocked-edges/4.16.0-rc.4-OpenStackAvailabilityZoneOutOfRange.yaml
Regressions [landed][1] [in 4.16.0-ec.6][2], [4.15.15][3] and [4.14.29][3]. Generated by creating the 4.14.29 risk and copying it around with:
```console
$ for V in 4.14.30 4.15.{15,16,17,18} 4.16.0-{ec.6,rc.{0,1,2,3,4}}; do sed 's/4.14.29/${V}/' blocked-edges/4.14.29-OpenStackAvailabilityZoneOutOfRange.yaml > "blocked-edges/${V}-OpenStackAvailabilityZoneOutOfRange.yaml"; done
```
I've gone with `from: .*`, because I expect a fix to move back quickly, but we can revise to allow updates within affected releases (e.g. 4.15.15 -> 5.15.16) in follow up work, if we want those flowing while we wait for the fix.
[1]: https://amd64.ocp.releases.ci.openshift.org/releasestream/4-dev-preview/release/4.16.0-ec.6
[2]: https://issues.redhat.com/browse/OCPBUGS-30951
[3]: …
=> OSASINFRA-3500: blocked-edges: Declare OpenStackAvailabilityZoneOutOfRange

blocked-edges/4.14.30-OVNInterConnectTransitionIPsec.yaml
[OCPBUGS-34885][1] is still POST for 4.14.z.
[1]: https://issues.redhat.com/browse/OCPBUGS-34885
=> SDN-4871: blocked-edges/4.14.30-OVNInterConnectTransitionIPsec: Not fixed yet

build-suggestions/4.16.yaml
[4.15.18][1] has [OCPBUGS-28928][2], and we want that SHA-1 Route check in every 4.15 cluster with updates to a supported 4.16 release.
[1]: https://amd64.ocp.releases.ci.openshift.org/releasestream/4-stable/release/4.15.18
[2]: https://issues.redhat.com/browse/OCPBUGS-28928
=> build-suggestions/4.16: Set minor_min to 4.15.18

blocked-edges/4.16.0-rc.4-OpenStackAvailabilityZoneOutOfRange.yaml
https://amd64.ocp.releases.ci.openshift.org/releasestream/4-stable/release/4.16.0-rc.5 lists OCPBUGS-34882 as fixed.
=> `OpenStackAvailabilityZoneOutOfRange`: Fixed in 4.16.0-rc.5

blocked-edges/4.16.0-rc.4-TechPreviewSignatureStoresInDefault.yaml
https://amd64.ocp.releases.ci.openshift.org/releasestream/4-stable/release/4.16.0-rc.5 includes OCPBUGS-35249
=> `TechPreviewSignatureStoresInDefault`: Fixed in 4.16.0-rc.5

README.md
To reduce the chances that an OpenShift-cluster administrator reading the README jumps from "this API allows the graph-data admins to do things like dropping update edges" (which is true) to "so maybe tomorrow my 4.15.0 to 4.15.2 recommendation will be blocked in stable-4.15!" (which is not true).  That won't happen because [4.15 docs][1] say:
> Beginning in OpenShift Container Platform 4.10, when update risks are confirmed, they are declared as Conditional Update risks for the relevant updates.
which is a policy commitment constraining update service changes. Hopefully the new wording adds some clarity on the space between "how the tools could be used" and "how Red Hat will use the tools".
[1]: https://docs.openshift.com/container-platform/4.15/updating/understanding_updates/understanding …
=> README: Explain scoping vs. OCP policy and support

blocked-edges/4.16.0-rc.0-OVNMulticastPacketLoss.yaml, blocked-edges/4.16.0-rc.1-OVNMulticastPacketLoss.yaml, blocked-edges/4.16.0-rc.2-OVNMulticastPacketLoss.yaml, blocked-edges/4.16.0-rc.3-OVNMulticastPacketLoss.yaml, blocked-edges/4.16.0-rc.4-OVNMulticastPacketLoss.yaml, blocked-edges/4.16.0-rc.5-OVNMulticastPacketLoss.yaml, blocked-edges/4.16.0-rc.6-OVNMulticastPacketLoss.yaml
I have created rc0 manually and copied the rest with:
```
for rc in (seq 1 6)
cp 4.16.0-rc.0-OVNMulticastPacketLoss.yaml 4.16.0-rc.$rc-OVNMulticastPacketLoss.yaml
sed -i "s|4.16.0-rc.0|4.16.0-rc.$rc|" 4.16.0-rc.$rc-OVNMulticastPacketLoss.yaml
end
```
I have copied the OVN detection from some past OVN risks:
https://github.com/openshift/cincinnati-graph-data/blob/1d7976cc21c2ba338355d15a3afb1a35d5d0a252/blocked-edges/4.14.9-OVNInterConnectTransitionIPsec.yaml#L14C1-L16C70
But I'm not sure why the past risk are using a `-1` in that PromQL. I have tested the PromQL and it seems to behave as expected without the negative multiplication?
=> SDN-5055: Set up `OVNMulticastPacketLoss` for 4.16

blocked-edges/4.14.31-ARODNSWrongBootSequence.yaml
[OCPBUGS-35300][1] is still `New` for 4.17.
[1]: https://issues.redhat.com/browse/OCPBUGS-35300
=> blocked-edges/4.14.31-ARODNSWrongBootSequence: Not fixed yet

blocked-edges/4.14.31-OVNInterConnectTransitionIPsec.yaml
[OCPBUGS-34885][1] is still Post for 4.14.
[1]: https://issues.redhat.com/browse/OCPBUGS-34885
=> SDN-4871: blocked-edges/4.14.31-OVNInterConnectTransitionIPsec: Not fixed yet

blocked-edges/4.15.18-OpenStackAvailabilityZoneOutOfRange.yaml
[4.15.19][1] contains [OCPBUGS-34927][2].
[1]: https://amd64.ocp.releases.ci.openshift.org/releasestream/4-stable/release/4.15.19
[2]: https://issues.redhat.com/browse/OCPBUGS-34927
=> blocked-edges/4.15.18-OpenStackAvailabilityZoneOutOfRange: Fixed in 4.15.19

graph-data.rs/Cargo.lock, graph-data.rs/Cargo.toml
[Bump o/cincinnati to dc2abd15 to match production](https://github.com/openshift/cincinnati-graph-data/pull/5459/commits/486fa62b7b7e6916608d56765f92921fe9d5bf97)
e2e tests recently [fail](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_cincinnati-graph-data/5457/pull-ci-openshift-cincinnati-graph-data-master-e2e/1805576375088713728):
```
Error: Missing the following versions in scraped images: {Version { major: 4, minor: 6, patch: 13, pre: [], build: [] }
```
Tracing the tests I saw the code only scrapes 20 releases from Quay which suggests some kind of pagination issues. Production cincinnati does not show any similar symptoms so there's a good chance that simply bumping the tests to run the same code helps.
Production cincinnati runs …
=> Bump o/cincinnati to dc2abd15 to fix e2e tests

graph-data.rs/Cargo.lock, graph-data.rs/Cargo.toml, graph-data.rs/src/check_releases.rs
https://github.com/openshift/cincinnati/commit/17c9491557c19eaf2f0921aef9cfee7a95974787 changed `fetch_releases`, added a custom certificate option. It should handle running with empty custom certificates.
=> Bump cincinnati to 67fe062 to follow production

blocked-edges/4.14.32-ARODNSWrongBootSequence.yaml, blocked-edges/4.17.0-ec.0-TechPreviewSignatureStoresInDefault.yaml
1. **TechPreviewSignatureStoresInDefault** fixed in 4.17.0-ec.1
**OCPBUGS-35236**: Revert: Add support for Custom Certificate Authorities
for custom signature stores”
https://amd64.ocp.releases.ci.openshift.org/releasestream/4-dev-preview/release/4.17.0-ec.1
2. **ARODNSWrongBootSequence** 
OCPBUGS-35300 has merged in release 4.14 but missed 4.14.32
https://github.com/openshift/machine-config-operator/pull/4456
https://amd64.ocp.releases.ci.openshift.org/releasestream/4.14.0-0.nightly/release/4.14.0-0.nightly-2024-07-05-145251?from=4.14.32
=> extend ARODNSWrongBootSequence and mark TechPreviewSignatureStoresInDefault as fixed

blocked-edges/4.14.31-OVNInterConnectTransitionIPsec.yaml
CLUSTER-NETWORK-OPERATOR
OCPBUGS-34885: [release-4.14] Fix 4.13-&gt;4.14 upgrade with ipsec enabled
https://amd64.ocp.releases.ci.openshift.org/releasestream/4-stable/release/4.14.32
=> OVNInterConnectTransitionIPsec fixed in 4.14.32

blocked-edges/4.16.0-ServiceAccountContentionSecretLeak.yaml, blocked-edges/4.16.0-rc.3-ServiceAccountContentionSecretLeak.yaml, blocked-edges/4.16.0-rc.4-ServiceAccountContentionSecretLeak.yaml, blocked-edges/4.16.0-rc.5-ServiceAccountContentionSecretLeak.yaml, blocked-edges/4.16.0-rc.6-ServiceAccountContentionSecretLeak.yaml, blocked-edges/4.16.0-rc.9-ServiceAccountContentionSecretLeak.yaml, blocked-edges/4.16.1-ServiceAccountContentionSecretLeak.yaml, blocked-edges/4.16.2-ServiceAccountContentionSecretLeak.yaml
The regression came in via [OCPBUGS-33600][1], landing [in rc.3][2].  I wrote the 4.16.0 risk by hand, and copied it out to the other 4.16 (by excluding Engineering Candidates and the first few Release Candidates) with:
```console
$ curl -s 'https://api.openshift.com/api/upgrades_info/graph?channel=candidate-4.16&arch=amd64' | jq -r '.nodes[] | .version' | grep '^4[.]16[.]' | grep -v '^4[.]16[.]0$\|-ec[.]\|-rc[.][0-2]' | while read VERSION; do sed "s/4.16.0/${VERSION}/" blocked-edges/4.16.0-ServiceAccountContentionSecretLeak.yaml > "blocked-edges/${VERSION}-ServiceAccountContentionSecretLeak.yaml"; done
```
0cc6e3c475 (#5490)'s `PreRelease` risks mean we don't need to bother with "but what about clusters on rc.0 updating into 4.16.0?" unless we want to protect clusters that are already …
=> API-1819: blocked-edges/4.16.*-ServiceAccountContentionSecretLeak: Declare risk

blocked-edges/4.14.32-ARODNSWrongBootSequence.yaml
[4.14.33][1] contains [OCPBUGS-36593][2], which is `Verified` with that single pull.
[1]: https://amd64.ocp.releases.ci.openshift.org/releasestream/4-stable/release/4.14.33
[2]: https://issues.redhat.com/browse/OCPBUGS-36593
=> blocked-edges/4.14.32-ARODNSWrongBootSequence: Fixed in 4.14.33

blocked-edges/4.16.3-ServiceAccountContentionSecretCreation.yaml
[OCPBUGS-36862][1] is `POST` for 4.16.
[1]: https://issues.redhat.com/browse/OCPBUGS-36862
=> API-1819: blocked-edges/4.16.3-ServiceAccountContentionSecretCreation: Not fixed yet

blocked-edges/4.13.25-ARODNSWrongBootSequence.yaml, blocked-edges/4.13.26-ARODNSWrongBootSequence.yaml, blocked-edges/4.13.27-ARODNSWrongBootSequence.yaml, blocked-edges/4.13.28-ARODNSWrongBootSequence.yaml, blocked-edges/4.13.29-ARODNSWrongBootSequence.yaml, blocked-edges/4.13.30-ARODNSWrongBootSequence.yaml, blocked-edges/4.13.31-ARODNSWrongBootSequence.yaml, blocked-edges/4.13.32-ARODNSWrongBootSequence.yaml, blocked-edges/4.13.33-ARODNSWrongBootSequence.yaml, blocked-edges/4.13.34-ARODNSWrongBootSequence.yaml, blocked-edges/4.13.35-ARODNSWrongBootSequence.yaml, blocked-edges/4.13.36-ARODNSWrongBootSequence.yaml, blocked-edges/4.13.37-ARODNSWrongBootSequence.yaml, blocked-edges/4.13.38-ARODNSWrongBootSequence.yaml, blocked-edges/4.13.39-ARODNSWrongBootSequence.yaml, blocked-edges/4.13.40-ARODNSWrongBootSequence.yaml, blocked-edges/4.13.41-ARODNSWrongBootSequence.yaml, blocked-edges/4.13.42-ARODNSWrongBootSequence.yaml, blocked-edges/4.13.43-ARODNSWrongBootSequence.yaml, blocked-edges/4.13.44-ARODNSWrongBootSequence.yaml, blocked-edges/4.13.45-ARODNSWrongBootSequence.yaml
https://issues.redhat.com/browse/OCPBUGS-35300 remains an issue for clusters after 4.13.25.
=> blocked-edges/4.13.25+-ARODNSWrongBootSequence: Declare risk

blocked-edges/4.16.0-OldBootImagesMissingOSReleaseRHELVersion.yaml, blocked-edges/4.16.1-OldBootImagesMissingOSReleaseRHELVersion.yaml, blocked-edges/4.16.2-OldBootImagesMissingOSReleaseRHELVersion.yaml
Originally declared for 4.13.7+ in https://github.com/openshift/cincinnati-graph-data/pull/5528 and then reverted in https://github.com/openshift/cincinnati-graph-data/pull/5539 because we discovered the versions are not actually affected. We confirmed the exposure for 4.16.* and the fix went into 4.16.3 ([OCPBUGS-36330](https://issues.redhat.com/browse/OCPBUGS-36330)) so declaring just for the three earlier versions.
Copied one file from the original #5528, manually adjusted for 4.16.0, then copied with
```
for patch in 1 2
cp blocked-edges/4.16.0-OldBootImagesMissingOSReleaseRHELVersion.yaml blocked-edges/4.16.$patch-OldBootImagesMissingOSReleaseRHELVersion.yaml
sed -i "s|to: 4.16.0|to: 4.16.$patch|" blocked-edges/4.16.$patch-OldBootImagesMissingOSReleaseRHELVersion.yaml
end
```
Finally …
=> MCO-1212: blocked-edges/4.16.{0,1,2}: Re-declare `OldBootImagesMissingOSReleaseRHELVersion`

blocked-edges/4.15.0-OLMOperatorsInFailedState.yaml, blocked-edges/4.15.10-OLMOperatorsInFailedState.yaml, blocked-edges/4.15.2-OLMOperatorsInFailedState.yaml, blocked-edges/4.15.3-OLMOperatorsInFailedState.yaml, blocked-edges/4.15.5-OLMOperatorsInFailedState.yaml, blocked-edges/4.15.6-OLMOperatorsInFailedState.yaml, blocked-edges/4.15.7-OLMOperatorsInFailedState.yaml, blocked-edges/4.15.8-OLMOperatorsInFailedState.yaml, blocked-edges/4.15.9-OLMOperatorsInFailedState.yaml, blocked-edges/4.16.0-OldBootImagesMissingOSReleaseRHELVersion.yaml, blocked-edges/4.16.1-OldBootImagesMissingOSReleaseRHELVersion.yaml, blocked-edges/4.16.2-OldBootImagesMissingOSReleaseRHELVersion.yaml
Trevor noticed we sometimes have `4[.]X[.]*` instead of `4[.]X[.].*`. The former would capture multiple dots where our intent is to capture a single dot followed by anything (usually patch numbers). It happens to work because we match on substrings, but fixed regexes express our intent better and are more readable for everyone.
Edited with:
```
sed -E -i -e 's|4\[\.\]([0-9]*)\[\.\]\*|4[.]\1[.].*|' blocked-edges/*
```
=> blocked-edges: fix typos in regexes

blocked-edges/4.15.0-OVNIPsecPausedMCPConnectivity.yaml, blocked-edges/4.15.1-OVNIPsecPausedMCPConnectivity.yaml, blocked-edges/4.15.10-OVNIPsecPausedMCPConnectivity.yaml, blocked-edges/4.15.11-OVNIPsecPausedMCPConnectivity.yaml, blocked-edges/4.15.12-OVNIPsecPausedMCPConnectivity.yaml, blocked-edges/4.15.13-OVNIPsecPausedMCPConnectivity.yaml, blocked-edges/4.15.14-OVNIPsecPausedMCPConnectivity.yaml, blocked-edges/4.15.15-OVNIPsecPausedMCPConnectivity.yaml, blocked-edges/4.15.16-OVNIPsecPausedMCPConnectivity.yaml, blocked-edges/4.15.17-OVNIPsecPausedMCPConnectivity.yaml, blocked-edges/4.15.18-OVNIPsecPausedMCPConnectivity.yaml, blocked-edges/4.15.19-OVNIPsecPausedMCPConnectivity.yaml, blocked-edges/4.15.2-OVNIPsecPausedMCPConnectivity.yaml, blocked-edges/4.15.20-OVNIPsecPausedMCPConnectivity.yaml, blocked-edges/4.15.21-OVNIPsecPausedMCPConnectivity.yaml, blocked-edges/4.15.22-OVNIPsecPausedMCPConnectivity.yaml, blocked-edges/4.15.23-OVNIPsecPausedMCPConnectivity.yaml, blocked-edges/4.15.3-OVNIPsecPausedMCPConnectivity.yaml, blocked-edges/4.15.4-OVNIPsecPausedMCPConnectivity.yaml, blocked-edges/4.15.5-OVNIPsecPausedMCPConnectivity.yaml, blocked-edges/4.15.6-OVNIPsecPausedMCPConnectivity.yaml, blocked-edges/4.15.7-OVNIPsecPausedMCPConnectivity.yaml, blocked-edges/4.15.8-OVNIPsecPausedMCPConnectivity.yaml, blocked-edges/4.15.9-OVNIPsecPausedMCPConnectivity.yaml
**`OVNIPsecPausedMCPConnectivity`: Fix card name to [SDN-5146](https://issues.redhat.com//browse/SDN-5146)**
[SDN-5145](https://issues.redhat.com/browse/SDN-5145) is not the impact statement card, [SDN-5146](https://issues.redhat.com/browse/SDN-5146) is
---
**`OVNIPsecPausedMCPConnectivity`: Extend to 4.15.23**
[OCPBUGS-37205](https://issues.redhat.com/browse/OCPBUGS-37205) is still in POST
=> OVNIPsecPausedMCPConnectivity extend to 4.15.23

blocked-edges/4.13.45-ARODNSWrongBootSequence.yaml
[OCPBUGS-37160](https://issues.redhat.com/browse/OCPBUGS-37160) is fixed in https://amd64.ocp.releases.ci.openshift.org/releasestream/4-stable/release/4.13.46
=> `ARODNSWrongBootSequence`: Fix in 4.13.26

blocked-edges/4.15.24-OVNIPsecPausedMCPConnectivity.yaml
Release controller says [4.15.24](https://amd64.ocp.releases.ci.openshift.org/releasestream/4-stable/release/4.15.24) was created from 4.15.0-0.nightly-2024-07-24-150754, the [fix](https://github.com/openshift/cluster-network-operator/pull/2439) for [OCPBUGS-37205](https://issues.redhat.com/browse/OCPBUGS-37205) was included in 4.15.0-0.nightly-2024-07-25-041013
=> extending to 4.15.24
=> `OVNIPsecPausedMCPConnectivity`: Extend to 4.15.24

blocked-edges/4.15.24-OVNIPsecPausedMCPConnectivity.yaml
[4.15.25][1] includes [OCPBUGS-37205][2], which is Verified with that single pull request: openshift/cluster-network-operator#2439
[1]: https://multi.ocp.releases.ci.openshift.org/releasestream/4-stable-multi/release/4.15.25
[2]: https://issues.redhat.com/browse/OCPBUGS-37205
=> SDN-5146: blocked-edges/4.15.24-OVNIPsecPausedMCPConnectivity: Fixed in 4.15.25

blocked-edges/4.15.17-HyperShiftKubeAPIPort443.yaml, blocked-edges/4.15.18-HyperShiftKubeAPIPort443.yaml, blocked-edges/4.15.19-HyperShiftKubeAPIPort443.yaml, blocked-edges/4.15.20-HyperShiftKubeAPIPort443.yaml, blocked-edges/4.15.21-HyperShiftKubeAPIPort443.yaml, blocked-edges/4.15.22-HyperShiftKubeAPIPort443.yaml, blocked-edges/4.15.23-HyperShiftKubeAPIPort443.yaml, blocked-edges/4.15.24-HyperShiftKubeAPIPort443.yaml
Generated by writing the 4.15.17 risk by hand, and then copying it out to the other exposed releases with:
```console
$ curl -s 'https://api.openshift.com/api/upgrades_info/graph?channel=candidate-4.15&arch=amd64' | jq -r '.nodes[] | .version' | grep '^4[.]15[.]\(1[8-9]\|2[0-4]\)$' | while read VERSION; do sed "s/4.15.17/${VERSION}/" blocked-edges/4.15.17-HyperShiftKubeAPIPort443.yaml > "blocked-edges/${VERSION}-HyperShiftKubeAPIPort443.yaml"; done
```
After which I manually declared `fixedIn` for [4.15.25][3], which included [OCPBUGS-37695][4].
I did not need to declare 4.16 risks, because f8316da482f60 (2024-06-06, #5352) landed early enough that no exposed 4.16 bake in update-recommendations from unexposed 4.15.(z<17) releases.  For example:
```console
$ oc adm release info …
```
=> HOSTEDCP-1849: blocked-edges/4.15-HyperShiftKubeAPIPort443: Declare risk

blocked-edges/4.14.34-SRIOVFailedToConfigureVF.yaml, blocked-edges/4.15.25-SRIOVFailedToConfigureVF.yaml
The corresponding impact statement: https://issues.redhat.com/browse/NHE-1171
Versions affected at the moment:
- 4.14.34+
- 4.15.25+
Created `4.14.34-SRIOVFailedToConfigureVF.yaml` manually.
Then run the following command for the next versions:
```
curl -s 'https://api.openshift.com/api/upgrades_info/graph?channel=candidate-4.14&arch=amd64' | jq -r '.nodes[] | .version' | grep '^4[.]14[.]\(3[5-9]\|4[0-9]\)$' | while read VERSION; do sed "s/4.14.34/${VERSION}/" blocked-edges/4.14.34-SRIOVFailedToConfigureVF.yaml > "blocked-edges/${VERSION}-SRIOVFailedToConfigureVF.yaml"; done
```
Created `4.15.25-SRIOVFailedToConfigureVF.yaml` manually.
Then run the following command for the next versions:
```
curl -s 'https://api.openshift.com/api/upgrades_info/graph?channel=candidate-4.15&arch=amd64' | …
```
=> NHE-1171: Declare SRIOVFailedToConfigureVF risk

blocked-edges/4.13.46-AROSystemDLooping.yaml, blocked-edges/4.14.33-AROSystemDLooping.yaml, blocked-edges/4.14.34-AROSystemDLooping.yaml, blocked-edges/4.15.22-AROSystemDLooping.yaml, blocked-edges/4.15.23-AROSystemDLooping.yaml, blocked-edges/4.15.24-AROSystemDLooping.yaml, blocked-edges/4.15.25-AROSystemDLooping.yaml, blocked-edges/4.16.3-AROSystemDLooping.yaml, blocked-edges/4.16.4-AROSystemDLooping.yaml, blocked-edges/4.16.5-AROSystemDLooping.yaml, blocked-edges/4.16.6-AROSystemDLooping.yaml, blocked-edges/4.16.7-AROSystemDLooping.yaml
Related to https://issues.redhat.com/browse/OCPBUGS-37534
Investigation is still ongoing to determine full impact for born in versions. Currently, ARO SRE is seeing 100% failure rate into versions with this code change listed above.
=> Block edges for ARO clusters with systemd dependency loops

blocked-edges/4.13.46-AROSystemDLooping.yaml, blocked-edges/4.14.33-AROSystemDLooping.yaml, blocked-edges/4.14.34-AROSystemDLooping.yaml, blocked-edges/4.15.22-AROSystemDLooping.yaml, blocked-edges/4.15.23-AROSystemDLooping.yaml, blocked-edges/4.15.24-AROSystemDLooping.yaml, blocked-edges/4.15.25-AROSystemDLooping.yaml, blocked-edges/4.16.3-AROSystemDLooping.yaml, blocked-edges/4.16.4-AROSystemDLooping.yaml, blocked-edges/4.16.5-AROSystemDLooping.yaml, blocked-edges/4.16.6-AROSystemDLooping.yaml, blocked-edges/4.16.7-AROSystemDLooping.yaml
Fixes small error seen in the promql in #5683 
Cluster born in 4.12 matching
=> Update AROSystemDLooping promql to have no errors

blocked-edges/4.15.26-SRIOVFailedToConfigureVF.yaml
The [OCPBUGS-38090](https://issues.redhat.com/browse/OCPBUGS-38090) issue tracks the backport for the 4.15.z version.
The bug is in the state `NEW` as of the moment. Thus, I am extending the risk to 4.15.26.
=> NHE-1171: SRIOVFailedToConfigureVF: Extend to 4.15.26

blocked-edges/4.15.26-AROSystemDLooping.yaml
No machine-config changes [in 4.15.26][1].
[1]:https://amd64.ocp.releases.ci.openshift.org/releasestream/4-stable/release/4.15.26
=> blocked-edges/4.15.26-AROSystemDLooping: Not fixed yet

blocked-edges/4.16.7-SRIOVFailedToConfigureVF.yaml
Corresponding impact statement https://issues.redhat.com/browse/NHE-1171
[OCPBUGS-38089](https://issues.redhat.com/browse/OCPBUGS-38089) tracks the backport for the 4.16.z version.
The 4.16.7 payload is affected.
=> NHE-1171: SRIOVFailedToConfigureVF: Include 4.16.7

blocked-edges/4.15.27-AROSystemDLooping.yaml
Only metadata changes changes in [4.15.27][1].
[1]:https://amd64.ocp.releases.ci.openshift.org/releasestream/4-stable/release/4.15.27
=> blocked-edges/4.15.27-AROSystemDLooping: Not fixed yet

blocked-edges/4.15.27-SRIOVFailedToConfigureVF.yaml
Only metadata changes changes in [4.15.27][1].
[1]:https://amd64.ocp.releases.ci.openshift.org/releasestream/4-stable/release/4.15.27
=> blocked-edges/4.15.27-SRIOVFailedToConfigureVF: Not fixed yet

OWNERS_ALIASES
Add David Hurta (me) to the `cincinnati-graph-data-approvers` group.
=> NO-JIRA: Add dhurta to cincinnati-graph-data-approvers

blocked-edges/4.13.46-AzureSystemDLooping.yaml
There is already an ARO-scoped AROSystemDLooping risk which has been evolving:
* 2183f0c284 (#5683).
* 2ef3ccd02f (#5693).
* 25b37ba861 (#5721).
But we hadn't seen that impact in 4.12.recent to 4.13.recent non-ARO Azure CI.  As we continued to test, the 4.12.54 [OCPBUGS-30823][1] change seems to be what's protecting clusters installed with 4.12.recent.  And [OCPBUGS-38295][2] is taking a fix back to 4.13.z that will allow the machine-config daemon to update units without spooking systemd with dependency cycles while the units are being updated.
[1]: https://issues.redhat.com/browse/OCPBUGS-30823
[2]: https://issues.redhat.com/browse/OCPBUGS-38295
=> MCO-1257: blocked-edges/4.13.46-AzureSystemDLooping: Declare Azure-scoped risk

blocked-edges/4.13.46-AzureSystemDLooping.yaml, blocked-edges/4.14.34-SRIOVFailedToConfigureVF.yaml, blocked-edges/4.15.27-SRIOVFailedToConfigureVF.yaml, blocked-edges/4.16.7-SRIOVFailedToConfigureVF.yaml, build-suggestions/4.17.yaml
AzureSystemDLooping fixed in 4.13.48
SRIOVFailedToConfigureVF fixed in 4.14.35, 4.15.28, 4.16.8
Require 4.16.8 so that fixes for OCPBUGS-38182 are present before upgrading to 4.17.
=> Fixes shipped

blocked-edges/4.14.35-ARODNSWrongBootSequence.yaml
The [OCPBUGS-35300][1] series [patched 4.14.33][2].  But the [OCPBUGS-37534][3] series [recently reverted that in 4.14][4].  But [4.14.35][5] has:
> Release 4.14.35 was created from registry.ci.openshift.org/ocp/release:4.14.0-0.nightly-2024-08-13-170824
which is too old to have the revert.  And doesn't seem like the revert would be grounds for declaring this fixed anyway.  I'll extend to unblock `candidate-*` membership, and the ARO folks can adjust if I'm misunderstanding.
[1]: https://issues.redhat.com/browse/OCPBUGS-35300
[2]: https://issues.redhat.com/browse/OCPBUGS-36593?focusedId=25141472&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-25141472
[3]: https://issues.redhat.com/browse/OCPBUGS-37534
[4]: https://issues.redhat.com/browse/OCPBUGS-38371
[5]: …
=> blocked-edges/4.14.35-ARODNSWrongBootSequence: Not fixed yet

blocked-edges/4.13.48-ARODNSWrongBootSequence.yaml
Just like #5737 extend this for the time being, review later once it's clearer when this gets declared fixed.
=> blocked-edges/4.13.48-ARODNSWrongBootSequence: Not fixed yet

blocked-edges/4.13.46-AROSystemDLooping.yaml
[4.13.48][1] includes [OCPBUGS-38295][2], which avoids confusing systemd while multiple units are being adjusted.
[1]: https://amd64.ocp.releases.ci.openshift.org/releasestream/4-stable/release/4.13.48
[2]: https://issues.redhat.com/browse/OCPBUGS-38295
=> MCO-1257: blocked-edges/4.13.46-*SystemDLooping: 4.13.48 fixes the looping

blocked-edges/4.14.37-ARODNSWrongBootSequence.yaml
Pretty much blindly, and the ARO folks can update whenever they want to declare this fixed.
=> blocked-edges/4.14.37-ARODNSWrongBootSequence: Extend to 4.14.37

blocked-edges/4.13.50-ARODNSWrongBootSequence.yaml
Following https://github.com/openshift/cincinnati-graph-data/pull/5896:
> Pretty much blindly, and the ARO folks can update whenever they want to declare this fixed.
Generated with https://github.com/petr-muller/ota:
```
$ go run ./cmd/graph-extend-or-fix/... --risk ARODNSWrongBootSequence --last 4.13.49 --new 4.13.50 --graph-repository-path=../../openshift/cincinnati-graph-data --do=extend --skip-inspect
```
=> `ARODNSWrongBootSequence`: Extend to 4.13.50

blocked-edges/4.13.51-ARODNSWrongBootSequence.yaml
Following https://github.com/openshift/cincinnati-graph-data/pull/5896:
> Pretty much blindly, and the ARO folks can update whenever they want to declare this fixed.
=> `ARODNSWrongBootSequence`: Extend to 4.13.51

blocked-edges/4.14.38-ARODNSWrongBootSequence.yaml
ARO folks have [ARO-9234][1] tracking their declaring the fix.  They'll address the declared risk then.  Until then, we just blindly extend it for them.
[1]: https://issues.redhat.com/browse/ARO-9234
=> ARO-9234: blocked-edges/4.14.38-ARODNSWrongBootSequence: Extend to 4.14.38

graph-data.rs/Cargo.lock
This respects the version bounds specified in `Cargo.toml` so hypothetically this is just hygiene.
=> `cargo update --manifest-path graph-data.rs/Cargo.toml`

README.md, blocked-edges/4.14.38-ARODNSWrongBootSequence.yaml, hack/stabilization-changes.py
I'm not actually automatically extending risks yet, but that can come later.  For now, I'm just giving the graph-data administrator a clear message requesting the extension.
I've retroactively tucked this into version 1.1.0, because like `fixedIn`, it's between graph-data admins and the stabilization script, and not something that Cincinnati or later components are expected to care about.
For `ARODNSWrongBootSequence`, Lisa told us on 2024-09-26 that we could use that ARO ticket to delegate managing that particular risk to her.
=> NO-ISSUE: hack/stabilization-changes: Add support for autoExtend

blocked-edges/4.13.51-ARODNSWrongBootSequence.yaml
I'd missed 4.13.51 in ef681855340b (#6044).
=> blocked-edges/4.13.51-ARODNSWrongBootSequence: autoExtend on ARO-9234

blocked-edges/4.13.52-ARODNSWrongBootSequence.yaml
Management deferred to [ARO-9234](https://issues.redhat.com/browse/ARO-9234).
=> ARO-9234: blocked-edges/4.13.52-ARODNSWrongBootSequence: Auto-extend to 4.13.52

blocked-edges/4.14.39-ARODNSWrongBootSequence.yaml
Management deferred to https://issues.redhat.com/browse/ARO-9234
=> blocked-edges/4.14.39-ARODNSWrongBootSequence: Auto-extend to 4.14.39

blocked-edges/4.15.0-OVNIPsecConnectivity.yaml, blocked-edges/4.15.1-OVNIPsecConnectivity.yaml, blocked-edges/4.15.10-OVNIPsecConnectivity.yaml, blocked-edges/4.15.11-OVNIPsecConnectivity.yaml, blocked-edges/4.15.12-OVNIPsecConnectivity.yaml, blocked-edges/4.15.13-OVNIPsecConnectivity.yaml, blocked-edges/4.15.14-OVNIPsecConnectivity.yaml, blocked-edges/4.15.15-OVNIPsecConnectivity.yaml, blocked-edges/4.15.16-OVNIPsecConnectivity.yaml, blocked-edges/4.15.17-OVNIPsecConnectivity.yaml, blocked-edges/4.15.18-OVNIPsecConnectivity.yaml, blocked-edges/4.15.19-OVNIPsecConnectivity.yaml, blocked-edges/4.15.2-OVNIPsecConnectivity.yaml, blocked-edges/4.15.20-OVNIPsecConnectivity.yaml, blocked-edges/4.15.21-OVNIPsecConnectivity.yaml, blocked-edges/4.15.22-OVNIPsecConnectivity.yaml, blocked-edges/4.15.23-OVNIPsecConnectivity.yaml, blocked-edges/4.15.24-OVNIPsecConnectivity.yaml, blocked-edges/4.15.25-OVNIPsecConnectivity.yaml, blocked-edges/4.15.26-OVNIPsecConnectivity.yaml, blocked-edges/4.15.27-OVNIPsecConnectivity.yaml, blocked-edges/4.15.3-OVNIPsecConnectivity.yaml, blocked-edges/4.15.4-OVNIPsecConnectivity.yaml, blocked-edges/4.15.5-OVNIPsecConnectivity.yaml, blocked-edges/4.15.6-OVNIPsecConnectivity.yaml, blocked-edges/4.15.7-OVNIPsecConnectivity.yaml, blocked-edges/4.15.8-OVNIPsecConnectivity.yaml, blocked-edges/4.15.9-OVNIPsecConnectivity.yaml
Stole the query from https://github.com/openshift/cincinnati-graph-data/pull/5588 and removed the part for "multiple worker MachineConfigPools".
OVN clusters with enabled IPsec may lose pod to pod communication between a set of nodes which may impact overall functionality of the cluster and even cause production outage.
Created a 4.15.0 file manually then created the rest with:
```bash
for patch in $(seq 1 27); do
cp blocked-edges/4.15.0-OVNIPsecConnectivity.yaml blocked-edges/4.15.$patch-OVNIPsecConnectivity.yaml
gsed -i "s|to: 4.15.0|to: 4.15.$patch|" blocked-edges/4.15.$patch-OVNIPsecConnectivity.yaml
done
```
=> SDN-5422: Set up OVNIPsecConnectivity for 4.14 -> 4.15 paths

blocked-edges/4.13.52-ARODNSWrongBootSequence.yaml, blocked-edges/4.14.39-ARODNSWrongBootSequence.yaml
The bug has been fixed within the ARO service and no new risk edges are required going forward for this issue.
=> Ocpbugs 35300 aro fixed

blocked-edges/4.15.37-OVNIPsecConnectivity.yaml
The underlying bug https://issues.redhat.com/browse/OCPBUGS-41823 of https://issues.redhat.com/browse/SDN-5422 is currently not fixed (with the "ASSIGNED" state). Thus we extend the risk to 4.15.37.
Follow up https://redhat-internal.slack.com/archives/C02MX20TV24/p1730130810267269
```bash
$ go run ./cmd/graph-extend-or-fix --do extend --graph-repository-path ~/repo/openshift/cincinnati-graph-data --jira-bearer-token-file ~/.jira-token --last 4.15.36 --new 4.15.37 --risk OVNIPsecConnectivity
INFO[0000] Obtaining (likely) impact statement card SDN-5422 and process its linked bugs
SDN-5422 OCPBUGS-41823 OCPBUGS-43323 OCPBUGS-43498
INFO[0002] Found 3 bug cards
OCPBUGS-43323                   ON_QA           [Docs] IPsec upgrade from 4.14 to 4.15 pods losing connectivity
OCPBUGS-43498 …
```
=> Extend `OVNIPsecConnectivity` risk to 4.15.37

blocked-edges/4.17.0-OAuthServerDownIfSpaceInIDPName.yaml, blocked-edges/4.17.0-rc.0-OAuthServerDownIfSpaceInIDPName.yaml, blocked-edges/4.17.0-rc.1-OAuthServerDownIfSpaceInIDPName.yaml, blocked-edges/4.17.0-rc.2-OAuthServerDownIfSpaceInIDPName.yaml, blocked-edges/4.17.0-rc.3-OAuthServerDownIfSpaceInIDPName.yaml, blocked-edges/4.17.0-rc.5-OAuthServerDownIfSpaceInIDPName.yaml, blocked-edges/4.17.0-rc.6-OAuthServerDownIfSpaceInIDPName.yaml, blocked-edges/4.17.1-OAuthServerDownIfSpaceInIDPName.yaml, blocked-edges/4.17.2-OAuthServerDownIfSpaceInIDPName.yaml, blocked-edges/4.17.3-OAuthServerDownIfSpaceInIDPName.yaml
Manual edited `blocked-edges/4.17.0-OAuthServerDownIfSpaceInIDPName.yaml`
and generated others by
```bash
$ curl -s 'https://api.openshift.com/api/upgrades_info/graph?channel=candidate-4.17&arch=amd64' | jq -r '.nodes[] | .version' | grep '^4[.]17' | sort -V | grep -v '^4.17.0$' | grep -v '^4.17.0-ec' | while read VERSION; do sed "s/4.17.0/${VERSION}/" blocked-edges/4.17.0-OAuthServerDownIfSpaceInIDPName.yaml > "blocked-edges/${VERSION}-OAuthServerDownIfSpaceInIDPName.yaml"; done
```
=> AUTH-550: Set up OAuthServerDownIfSpaceInIDPName for 4.16 -> 4.17 paths

blocked-edges/4.17.0-OAuthServerDownIfSpaceInIDPName.yaml, blocked-edges/4.17.0-rc.0-OAuthServerDownIfSpaceInIDPName.yaml, blocked-edges/4.17.0-rc.1-OAuthServerDownIfSpaceInIDPName.yaml, blocked-edges/4.17.0-rc.2-OAuthServerDownIfSpaceInIDPName.yaml, blocked-edges/4.17.0-rc.3-OAuthServerDownIfSpaceInIDPName.yaml, blocked-edges/4.17.0-rc.5-OAuthServerDownIfSpaceInIDPName.yaml, blocked-edges/4.17.0-rc.6-OAuthServerDownIfSpaceInIDPName.yaml, blocked-edges/4.17.1-OAuthServerDownIfSpaceInIDPName.yaml, blocked-edges/4.17.2-OAuthServerDownIfSpaceInIDPName.yaml, blocked-edges/4.17.3-OAuthServerDownIfSpaceInIDPName.yaml
[OCPBUGS-44118](https://issues.redhat.com/browse/OCPBUGS-44118) has been filed and it identifies more affected clusters.
Both [OCPBUGS-43587](https://issues.redhat.com/browse/OCPBUGS-43587) and [OCPBUGS-44118](https://issues.redhat.com/browse/OCPBUGS-44118) shares the same symptom on the cluster, workaround, and fix.
So we use [AUTH-550](https://issues.redhat.com//browse/AUTH-550) as the assessment for both bugs.
=> AUTH-550: Set up OAuthServerDownIfSpaceInIDPName for 4.16 -> 4.17 paths (more cases)

blocked-edges/4.15.38-OVNIPsecConnectivity.yaml
[OCPBUGS-41823][1] is still `Assigned` for the development branch.
[1]: https://issues.redhat.com/browse/OCPBUGS-41823
=> SDN-5422: blocked-edges/4.15.38-OVNIPsecConnectivity: Not fixed yet

blocked-edges/4.17.3-OAuthServerDownIfSpaceInIDPName.yaml
[4.17.4][1] has both [OCPBUGS-43587][2] and [OCPBUGS-44118][3].
[1]: https://multi.ocp.releases.ci.openshift.org/releasestream/4-stable-multi/release/4.17.4
[2]: https://issues.redhat.com/browse/OCPBUGS-43587
[3]: https://issues.redhat.com/browse/OCPBUGS-44118
=> AUTH-550: blocked-edges/4.17.3-OAuthServerDownIfSpaceInIDPName: Fixed in 4.17.4

blocked-edges/4.14.40-OVNlibreswan.yaml
Checking [4.13 OVN CI][1] in [PromeCIeus][2]:
```
group by (__name__) ({__name__=~".*ipsec.*"})
```
only turns up `ovnkube_master_ipsec_enabled`, which we'd used previously, e.g. in 279798919e (#5334).  But checking [4.14 OVN CI][3], that same `__name__` search turns up:
* `openshift:openshift_network_operator_ipsec_state:info`,
* `openshift_network_operator_ipsec_state`, and
* `ovnkube_controller_ipsec_enabled`,
but not 4.13's `ovnkube_master_ipsec_enabled`.  The PromQL I'm adding here looks for the 4.14 `ovnkube_controller_ipsec_enabled`, if it can't find that it falls back to the 4.13 `ovnkube_master_ipsec_enabled`, and if it can't find that it falls back to the Kube-API standard `apiserver_storage_objects` we'd been using before for "am I OVN or not?".
[1]: …
=> SDN-5477: blocked-edges/4.14.40-OVNlibreswan: "is IPsec enabled?" PromQL

blocked-edges/4.14.40-OVNlibreswan.yaml
[4.14.41][1] includes [OCPBUGS-44379][2].
[1]: https://amd64.ocp.releases.ci.openshift.org/releasestream/4-stable/release/4.14.41
[2]: https://issues.redhat.com/browse/OCPBUGS-44379
=> SDN-5477: blocked-edges/4.14.40-OVNlibreswan: Fixed in 4.14.41

blocked-edges/4.15.23-HyperShiftNodePoolSkewBinaryDownload.yaml, blocked-edges/4.15.24-HyperShiftNodePoolSkewBinaryDownload.yaml, blocked-edges/4.15.25-HyperShiftNodePoolSkewBinaryDownload.yaml, blocked-edges/4.15.26-HyperShiftNodePoolSkewBinaryDownload.yaml, blocked-edges/4.15.27-HyperShiftNodePoolSkewBinaryDownload.yaml, blocked-edges/4.15.28-HyperShiftNodePoolSkewBinaryDownload.yaml, blocked-edges/4.15.29-HyperShiftNodePoolSkewBinaryDownload.yaml, blocked-edges/4.15.30-HyperShiftNodePoolSkewBinaryDownload.yaml, blocked-edges/4.16.10-HyperShiftNodePoolSkewBinaryDownload.yaml, blocked-edges/4.16.4-HyperShiftNodePoolSkewBinaryDownload.yaml, blocked-edges/4.16.5-HyperShiftNodePoolSkewBinaryDownload.yaml, blocked-edges/4.16.6-HyperShiftNodePoolSkewBinaryDownload.yaml, blocked-edges/4.16.7-HyperShiftNodePoolSkewBinaryDownload.yaml, blocked-edges/4.16.8-HyperShiftNodePoolSkewBinaryDownload.yaml, blocked-edges/4.16.9-HyperShiftNodePoolSkewBinaryDownload.yaml
Generated by writing the 4.15.23 an 4.16.4 files by hand and copying them out with:
```console
$ curl -s 'https://api.openshift.com/api/upgrades_info/graph?channel=candidate-4.15&arch=amd64' | jq -r '.nodes[] | .version' | grep '^4[.]15[.]\(2[4-9]\|[3-9][0-9]\)$' | while read VERSION; do sed "s/4.15.23/${VERSION}/" blocked-edges/4.15.23-HyperShiftNodePoolSkewBinaryDownload.yaml > "blocked-edges/${VERSION}-HyperShiftNodePoolSkewBinaryDownload.yaml"; done
$ curl -s 'https://api.openshift.com/api/upgrades_info/graph?channel=candidate-4.16&arch=amd64' | jq -r '.nodes[] | .version' | grep '^4[.]16[.]\([5-9]\|[1-9][0-9]\)$' | while read VERSION; do sed "s/4.16.4/${VERSION}/" blocked-edges/4.16.4-HyperShiftNodePoolSkewBinaryDownload.yaml > …
```
=> HOSTEDCP-1941: blocked-edges/*HyperShiftNodePoolSkewBinaryDownload: Declare new risk for 4.15.(z>=23) and 4.16.(z>=4)

build-suggestions/4.18.yaml
In 4.17.5 ,CMO will block cluster upgrades if the configurations in openshift-monitoring/cluster-monitoring-config or openshift-user-workload-monitoring/user-workload-monitoring-config fail to meet stricter validation criteria. This is to prompt users to clean up their configurations by removing unsupported fields and resolving any misconfigurations. The goal is to prevent CMO from becoming degraded (and unavailable) during the upgrade to version 4.18.
- 4.17.5 does include https://issues.redhat.com/browse/OCPBUGS-43690 https://amd64.ocp.releases.ci.openshift.org/features/4.17.5?from=4.17.4
This is the needed change, maybe the PR should be recreated via a bot.
=> MON-4093: Set 4.17.5 as the minor min for upgrades to 4.18.

build-suggestions/4.19.yaml, channels/candidate-4.19.yaml
Like 3eb8e55eb2 (#2758) and 585cc40919 (#5698) and similar, but for 4.19.  Generated with:
```console
$ hack/release-open.sh 4.19
$ git add build-suggestions/4.19.yaml channels/*4.19.yaml
```
=> *: Prepare for 4.19 development

blocked-edges/4.12.0-rc.7-AWSOldBootImage.yaml
With e1e5822ba1 ( #6268), the stabilization bot is looking at these again, and is concerned about this risk:
* FAILED AWSOldBootImages affects 4.12.0-rc.7.  Either declare a fix version or extend the risk to 4.12.0-rc.8.
Checking to see when [the MCO fix][1] landed:
```console
$ for X in 4.12.0-rc.7 4.12.0-rc.8 4.12.0; do echo -n "${X} "; oc adm release info --commits "quay.io/openshift-release-dev/ocp-release:${X}-x86_64" | grep machine-config-operator; done
4.12.0-rc.7   machine-config-operator                        https://github.com/openshift/machine-config-operator                        b29dceb12638f3d7f30f339729344de69824a09b
4.12.0-rc.8   machine-config-operator                        https://github.com/openshift/machine-config-operator …
```
=> COS-1942: blocked-edges/4.12.0-rc.7-AWSOldBootImage: Fixed in 4.12.0-rc.8

blocked-edges/4.15.40-OVNIPsecConnectivity.yaml
[OCPBUGS-41823][1] is still `Assigned`.
[1]: https://issues.redhat.com/browse/OCPBUGS-41823
=> SDN-5422: blocked-edges/4.15.40-OVNIPsecConnectivity: Not fixed yet

blocked-edges/4.18.0-ec.3-CMOSuddenStrictConfigValidation.yaml, blocked-edges/4.18.0-ec.4-CMOSuddenStrictConfigValidation.yaml, blocked-edges/4.18.0-rc.0-CMOSuddenStrictConfigValidation.yaml
4.18.0-ec.3 shipped the strict CMO config validation https://amd64.ocp.releases.ci.openshift.org/releasestream/4-dev-preview/release/4.18.0-ec.3 and **was built before** 4.17.5 where the "make CMO Upgradeable=false to ensure configurations pass strict validation before the 4.18 upgrade" was shipped https://amd64.ocp.releases.ci.openshift.org/releasestream/4-stable/release/4.17.5
=> add a known risk for 4.18.0-ec.3

blocked-edges/4.18.0-ec.3-CMOSuddenStrictConfigValidation.yaml, blocked-edges/4.18.0-ec.4-CMOSuddenStrictConfigValidation.yaml, blocked-edges/4.18.0-rc.0-CMOSuddenStrictConfigValidation.yaml
- ECs and RC numbers are dot-separated
- regexes need to capture [architecture suffixes](https://github.com/openshift/cincinnati-graph-data?tab=readme-ov-file#block-edges)
I was a bit trigger happy when reviewing https://github.com/openshift/cincinnati-graph-data/pull/6331
/cc @wking @machine424
=> `CMOSuddenStrictConfigValidation`: Fix regexes

hack/release-ga.sh, hack/release-open.sh, hack/release-stable-minor.sh
Following up on a075c5a494 (#6268), now that fa36ae0d2f (#6268) has extended that approach to the candidate and fast channels too.
=> OTA-1392: hack/release-*: Update scripts to add 4.(y-2).z to *-4.even channels

blocked-edges/4.17.0-OVNLocalnetWithNoSubnets.yaml, blocked-edges/4.17.1-OVNLocalnetWithNoSubnets.yaml, blocked-edges/4.17.2-OVNLocalnetWithNoSubnets.yaml, blocked-edges/4.17.3-OVNLocalnetWithNoSubnets.yaml, blocked-edges/4.17.4-OVNLocalnetWithNoSubnets.yaml, blocked-edges/4.17.5-OVNLocalnetWithNoSubnets.yaml, blocked-edges/4.17.6-OVNLocalnetWithNoSubnets.yaml
Address [SDN-5485](https://issues.redhat.com//browse/SDN-5485) / OCPBUGS-43454 which affects 4.17 until 4.17.7 where it is fixed. We have not managed to identify a precise technical PromQL to identify clusters with the exact problematic networking configuration so I am proposing to use a coarse approximation of what clusters are *likely* (based on the information available) to have such config (OpenShift Virtualization installations identified by the hyperconverged-cluster-operator CSV presence, and which at the same time have at least one `network-attachment-definitions.k8s.cni.cncf.io` resource instance.
Given the impact of the bug when hit (failure to create new workloads), it is better to steer the group of potentially affected clusters towards already available 4.17.7, even if we are …
=> SDN-5485: `OVNLocalnetWithNoSubnets`: ->4.17.[0-6] with virtualization

blocked-edges/4.18.0-rc.1-CMOSuddenStrictConfigValidation.yaml, build-suggestions/4.18.yaml
**`CMOSuddenStrictConfigValidation`: Extend to 4.18.0-rc.1**
RC1 still has edges from early ECs 0-2 without the validation, so is exposed:
```console
$ oc adm release info quay.io/openshift-release-dev/ocp-release:4.18.0-rc.1-x86_64 | grep Upgrades
Upgrades: 4.17.5, 4.17.6, 4.17.7, 4.17.8, 4.18.0-ec.0, 4.18.0-ec.1, 4.18.0-ec.2, 4.18.0-ec.3, 4.18.0-ec.4, 4.18.0-rc.0
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
A followup commit will bump the `z_min` in 4.18 build suggestions which will allow us to `fixedIn` the next RC, likely RC2
---
**build-suggestions/4.18: bump `z_min` to 4.18.0-ec.3**
Bumping to EC3 will prevent the next RC (likely RC2) to have edges from early ECs, upgrades from which are affected by `CMOSuddenStrictConfigValidation`. The bump will allow us to declare that risk as fixed …
=> `CMOSuddenStrictConfigValidation`: Extend to 4.18 RC1, bump 4.18 `z_min` to EC3

blocked-edges/4.15.41-OVNIPsecConnectivity.yaml
[OCPBUGS-41823][1] is still `Assigned`.
[1]: https://issues.redhat.com/browse/OCPBUGS-41823
=> SDN-5422: blocked-edges/4.15.41-OVNIPsecConnectivity: Not fixed yet

blocked-edges/4.16.0-rc.9-PreRelease.yaml
4.16.0 is the Generally Available release, as described in the message.  Declaring this addresses:
```
* FAILED PreRelease affects 4.16.0-rc.9.  Either declare a fix version or extend the risk to 4.16.0.
```
as `hack/stabilization-changes.py` adapts to 4d3beb6476 (#6412).
=> blocked-edges/4.16.0-rc.9-PreRelease: Fixed in 4.16.0

blocked-edges/4.16.25-NUMAResourcesOperatorCrashLoopBackOff.yaml, blocked-edges/4.16.26-NUMAResourcesOperatorCrashLoopBackOff.yaml, blocked-edges/4.17.7-NUMAResourcesOperatorCrashLoopBackOff.yaml, blocked-edges/4.17.8-NUMAResourcesOperatorCrashLoopBackOff.yaml
Impact statement: https://issues.redhat.com/browse/COS-3078
Steps done:
- Created `blocked-edges/4.16.25-NUMAResourcesOperatorCrashLoopBackOff.yaml` manually
- Run:
```shell
$ curl -s 'https://api.openshift.com/api/upgrades_info/graph?channel=candidate-4.16&arch=amd64' | jq -r '.nodes[] | .version' | grep '^4[.]16[.]\(2[6-9]\|[3-9][0-9]\)$' | while read VERSION; do sed "s/4.16.25/${VERSION}/" blocked-edges/4.16.25-NUMAResourcesOperatorCrashLoopBackOff.yaml > "blocked-edges/${VERSION}-NUMAResourcesOperatorCrashLoopBackOff.yaml"; done
```
- Created `blocked-edges/4.17.7-NUMAResourcesOperatorCrashLoopBackOff.yaml` manually
- Run:
```shell
$ curl -s 'https://api.openshift.com/api/upgrades_info/graph?channel=candidate-4.17&arch=amd64' | jq -r '.nodes[] | .version' | grep …
```
=> COS-3078: Declare `NUMAResourcesOperatorCrashLoopBackOff` risk

blocked-edges/4.18.0-rc.1-CMOSuddenStrictConfigValidation.yaml
Upgrades from ECs 0-2 are affected due to the risk.
The https://github.com/openshift/cincinnati-graph-data/pull/6405 PR bumped `build-suggestions/4.18` `z_min` to 4.18.0-ec.3 to prevent the next RC to have edges from the early affected ECs.
Verifying that the 4.18.0-rc.2 does not have upgrade paths from the affected versions:
```
$ oc adm release info quay.io/openshift-release-dev/ocp-release:4.18.0-rc.2-x86_64 | grep "Release Metadata" -A 4
Release Metadata:
Version:  4.18.0-rc.2
Upgrades: 4.17.5, 4.17.6, 4.17.7, 4.17.8, 4.17.9, 4.18.0-ec.3, 4.18.0-ec.4, 4.18.0-rc.0, 4.18.0-rc.1
Metadata:
url: https://access.redhat.com/errata/RHEA-2024:6122
```
Upgrades from the affected ECs 0-2 are not present.
=> NO-JIRA: blocked-edges/4.18.0-rc.1-CMOSuddenStrictConfigValidation.yaml: Set the risk as fixed in rc.2

blocked-edges/4.16.25-FCoEBootFromSANKernelDriverQedf.yaml, blocked-edges/4.16.26-FCoEBootFromSANKernelDriverQedf.yaml, blocked-edges/4.17.7-FCoEBootFromSANKernelDriverQedf.yaml, blocked-edges/4.17.8-FCoEBootFromSANKernelDriverQedf.yaml
Declare `FCoEBootFromSANKernelDriverQedf` risk
Impact statement: https://issues.redhat.com/browse/COS-3068
Created manually.
---
Set `FCoEBootFromSANKernelDriverQedf` risk as fixed in 4.16.27 and 4.17.9
=> COS-3068: Declare the `FCoEBootFromSANKernelDriverQedf` risk and mark it as fixed in 4.16.27 and 4.17.9

blocked-edges/4.15.42-OVNIPsecConnectivity.yaml
[OCPBUGS-41823][1] is still Assigned.
[1]: https://issues.redhat.com/browse/OCPBUGS-41823
=> SDN-5422: blocked-edges/4.15.42-OVNIPsecConnectivity: Not fixed yet

blocked-edges/4.18.0-rc.3-MachineConfigServerCARotation.yaml
We'll declare it fixed by 4.18.1, or whatever we call the first post-GA 4.18 release.  Because at GA-time, we raise that z_min to the GA release:
```console
$ grep z_min hack/release-ga.sh
sed -i -e "s|z_min: .*|z_min: ${LATEST}|" "build-suggestions/${MAJOR_MINOR}.yaml"
```
=> MCO-1481: blocked-edges/4.18.0-rc.3-MachineConfigServerCARotation: Extend risk

build-suggestions/4.18.yaml
[4.17.11][1] includes [OCPBUGS-38292][2], and we want clusters to pick up that logic before updating to 4.18 in generally-available channels.
[1]: https://amd64.ocp.releases.ci.openshift.org/releasestream/4-stable/release/4.17.11
[2]: https://issues.redhat.com/browse/OCPBUGS-38292
=> build-suggestions/4.18: Raise minor_min to 4.17.11

blocked-edges/4.18.0-rc.4-MachineConfigServerCARotation.yaml
As described in db99b0a215 (#6506), we're just carrying this along through the RCs, until we hit a post-GA release and raise z_min for new 4.18 release builds.
=> blocked-edges/4.18.0-rc.4-MachineConfigServerCARotation: Extend risk

channels/stable-4.12.yaml, channels/stable-4.13.yaml, channels/stable-4.14.yaml
4.12.z went EUS back in July, however we had a mandate to continue
plumbing them through to stable channels through January and that's
ended now. Since no additional 4.12.z go into stable-4.12, they shouldn't
go into stable-4.13 and stable-4.14 either. Those who continue with 4.12
should use eus channels which are tailored for that use.
=> OTA-1310: Remove stable channel 4.12.z feeders

blocked-edges/4.18.0-rc.5-MachineConfigServerCARotation.yaml
As described in db99b0a215 (#6506), we're just carrying this along through the RCs, until we hit a post-GA release and raise `z_min` for new 4.18 release builds.
=> MCO-1481: blocked-edges/4.18.0-rc.5-MachineConfigServerCARotation: Extend risk

blocked-edges/4.18.0-rc.6-MachineConfigServerCARotation.yaml
As described in db99b0a215 (#6506), we're just carrying this along through the RCs, until we hit a post-GA release and raise `z_min` for new 4.18 release builds.
=> MCO-1481: blocked-edges/4.18.0-rc.6-MachineConfigServerCARotation: Extend risk

blocked-edges/4.18.0-rc.7-MachineConfigServerCARotation.yaml, blocked-edges/4.18.0-rc.8-MachineConfigServerCARotation.yaml
As described in db99b0a215 (#6506), we're just carrying this along through the RCs, until we hit a post-GA release and raise `z_min` for new 4.18 release builds.
=> MCO-1481: blocked-edges/4.18.0-rc.[78]-MachineConfigServerCARotation: Extend risk

blocked-edges/4.18.0-rc.9-MachineConfigServerCARotation.yaml
As described in db99b0a215 (blocked-edges/4.18.0-rc.3-MachineConfigServerCARotation: Extend risk, 2024-12-20, #6506), we're just carrying this along through the RCs, until we hit a post-GA release and raise z_min for new 4.18 release builds.
=> MCO-1481: blocked-edges/4.18.0-rc.9-MachineConfigServerCARotation: Extend risk

blocked-edges/4.18.0-rc.10-MachineConfigServerCARotation.yaml
Same as https://github.com/openshift/cincinnati-graph-data/pull/6727
As described in db99b0a215 (blocked-edges/4.18.0-rc.3-MachineConfigServerCARotation: Extend risk, 2024-12-20, #6506), we're just carrying this along through the RCs, until we hit a post-GA release and raise z_min for new 4.18 release builds.
=> MCO-1481: blocked-edges/4.18.0-rc.10-MachineConfigServerCARotation: Extend risk

blocked-edges/4.18.1-MachineConfigServerCARotation.yaml
As described in db99b0a215 (#6506), we're just carrying this along through the RCs, until we hit a post-GA release and raise `z_min` for new 4.18 release builds.
=> MCO-1481: blocked-edges/4.18.1-MachineConfigServerCARotation: Extend risk

OWNERS, OWNERS_ALIASES
@LalatenduMohanty's mostly OLM-focused now, and while I'm still fine with him approving changes, he probably no longer wants to get pinged by GitHub to review new pulls.
=> OWNERS: Shift Lala to emeritus_approvers

blocked-edges/4.18.1-MachineConfigServerCARotation.yaml
The risk affects updates from 4.18.0-ec.4 to later releases [[1]].
Upon the 4.18 GA release, we have bumped the `z_min` build suggestion in the `build-suggestions/4.18.yaml` file [[2]]. This means that the minimal version of the updates in the 4.18.z stream will be the 4.18.1 version for new releases.
Verifying that the new 4.18.2 release only includes the update from 4.18.1 in the 4.18.z stream (and not from the affected 4.18.0-ec.4 or other 4.18.z versions):
```sh
$ oc adm release info quay.io/openshift-release-dev/ocp-release:4.18.2-x86_64 | head -n 13
Name:           4.18.2
Digest:         sha256:46f9db00dac167897378825ea5f3cce0867743ac90498bbb61b0816daedd0d00
Created:        2025-02-27T23:04:23Z
OS/Arch:        linux/amd64
Manifests:      758
Metadata files: 2
Pull From: …
```
=> MCO-1481: blocked-edges/4.18.1-MachineConfigServerCARotation: Declare as fixed in 4.18.2

blocked-edges/4.17.16-HostedClusterIsProgressingStuckCondition.yaml, blocked-edges/4.17.17-HostedClusterIsProgressingStuckCondition.yaml, blocked-edges/4.17.18-HostedClusterIsProgressingStuckCondition.yaml, blocked-edges/4.17.19-HostedClusterIsProgressingStuckCondition.yaml
Generated by writing the 4.17.16 risk by hand, and then copying it out to the other releases files and changing the file version. Blocking upgrades from all OCP releases to `4.17.16`, `4.17.17`, `4.17.18` and `4.17.19`.
The Issue was introduced by these Jira bugs:
- [OCPBUGS-44927](https://issues.redhat.com//browse/OCPBUGS-44927)
- https://github.com/openshift/hypershift/pull/5238
- [OCPBUGS-48487](https://issues.redhat.com//browse/OCPBUGS-48487), [OCPBUGS-48488](https://issues.redhat.com//browse/OCPBUGS-48488), [OCPBUGS-48490](https://issues.redhat.com//browse/OCPBUGS-48490)
- https://github.com/openshift/hypershift/pull/5402
---
- Release 4.19 and 4.18 already contains the fix by:
- 4.18: https://github.com/openshift/hypershift/pull/5513
- 4.19: …
=> CNTRLPLANE-256: blocked-edges/4.17-HostedClusterIsProgressingStuckCondition: Declare risk

blocked-edges/4.17.19-HostedClusterIsProgressingStuckCondition.yaml
[4.17.20][1] includes [OCPBUGS-51339][2].
[1]: https://multi.ocp.releases.ci.openshift.org/releasestream/4-stable-multi/release/4.17.20
[2]: https://issues.redhat.com/browse/OCPBUGS-51339
=> CNTRLPLANE-256: blocked-edges/4.17.19-HostedClusterIsProgressingStuckCondition: Fixed in 4.17.20

build-suggestions/4.19.yaml
- Following PR sets the machine-config cluster operator's status condition of `Upgradeable` to `False` if a cluster is found to be on cgroupv1 
https://github.com/openshift/machine-config-operator/pull/4921 
- Every cluster has to pass through this change(which is in 4.18.6) before upgrading to 4.19 to make sure the cluster is migrated to cgroupv2
=> OCPNODE-3005: Bump 4.18 minor minimum version to 4.18.6

blocked-edges/4.18.1-OVNWithMultipleClusterNetworks.yaml, blocked-edges/4.18.2-OVNWithMultipleClusterNetworks.yaml, blocked-edges/4.18.3-OVNWithMultipleClusterNetworks.yaml, blocked-edges/4.18.4-OVNWithMultipleClusterNetworks.yaml, blocked-edges/4.18.5-OVNWithMultipleClusterNetworks.yaml, blocked-edges/4.18.6-OVNWithMultipleClusterNetworks.yaml, blocked-edges/4.18.7-OVNWithMultipleClusterNetworks.yaml
The command to extend the risks from `blocked-edges/4.18.1-OVNWithMultipleClusterNetworks.yam`:
```console
$ curl -s 'https://api.openshift.com/api/upgrades_info/graph?channel=candidate-4.18&arch=amd64' | jq -r '.nodes[] | .version' | grep '^4[.]18' | sort -V | grep -v '^4.18.1$' | grep -v '^4.18.0-ec' | grep -v '^4.18.0-rc' | while read VERSION; do sed "s/4.18.1/${VERSION}/" blocked-edges/4.18.1-OVNWithMultipleClusterNetworks.yaml > "blocked-edges/${VERSION}-OVNWithMultipleClusterNetworks.yaml"; done
```
=> CORENET-5832: Set up OVNWithMultipleClusterNetworks to block paths to 4.18

blocked-edges/4.11.31-AWSOldBootImageLackAfterburn.yaml, blocked-edges/4.11.31-leaked-machineconfig.yaml
Reverts openshift/cincinnati-graph-data#3336
`4.11.32` got into `stable-4.11` https://github.com/openshift/cincinnati-graph-data/pull/3346 shortly after the reverted fix https://github.com/openshift/cincinnati-graph-data/pull/3336.
Ideally we should fix `stabilization-changes.py` to complain about it.
Before that happens, we may clean up the dups manually:
```
$ rg 'LeakedMachineConfigBlocksMCO|AWSOldBootImagesLackAfterburn' -l | grep -v -E '4.12|4.13'| xargs rg 'fixedIn'
blocked-edges/4.11.31-AWSOldBootImageLackAfterburn.yaml
5:fixedIn: 4.11.33
blocked-edges/4.11.32-AWSOldBootImageLackAfterburn.yaml
5:fixedIn: 4.11.33
blocked-edges/4.11.31-leaked-machineconfig.yaml
5:fixedIn: 4.11.33
blocked-edges/4.11.32-leaked-machineconfig.yaml
5:fixedIn: 4.11.33
```
=> Revert "blocked-edges/4.11.31-*: 4.11.33 fixes `AWSOldBootImageLackAfterburn` and `LeakedMachineConfigBlocksMCO`"

blocked-edges/4.18.8-OVNWithMultipleClusterNetworks.yaml
[OCPBUGS-49994][1] is still `Assigned`.
[1]: https://issues.redhat.com/browse/OCPBUGS-49994
=> CORENET-5832: blocked-edges/4.18.8-OVNWithMultipleClusterNetworks: Not fixed yet

hack/release-stable-minor.sh
To follow up https://github.com/openshift/cincinnati-graph-data/pull/7037#issuecomment-2783965749
With this PR,
- the sed command can be overridden by "${SED_CM}"
- the script is more portable with #!/usr/bin/env As a Shebang [1].
After this PR: we can run the script on MacOS by the following
command:
```console
$ bash --version
GNU bash, version 5.2.37(1)-release (aarch64-apple-darwin24.2.0)
...
$ SED_CMD=gsed hack/release-stable-minor.sh 4.18
4.18 is an EUS release, will update stable and eus channels
Running stabilization-changes.py: iteration 1
Running stabilization-changes.py: iteration 2
Running stabilization-changes.py: iteration 3
Running stabilization-changes.py: iteration 4
See /var/folders/xp/g5y5gl3525g7c3fvfc75lkk40000gn/T/tmp.XaIEPThXo4 for stabilization-changes.py output if …
```
=> Make release-stable-minor.sh runnable on MacOS

blocked-edges/4.15.48-OVNIPsecPausedMCPConnectivity.yaml
[4.15.49][1] contains [OCPBUGS-36688][2] and [OCPBUGS-43099][3], picking up openshift/machine-config-operator#4937 and openshift/cluster-network-operator#2658.
[1]: https://amd64.ocp.releases.ci.openshift.org/releasestream/4-stable/release/4.15.49
[2]: https://issues.redhat.com/browse/OCPBUGS-36688
[3]: https://issues.redhat.com/browse/OCPBUGS-43099
=> CORENET-5630: blocked-edges/4.15.48-OVNIPsecPausedMCPConnectivity: Fixed in 4.15.49

build-suggestions/4.19.yaml
…update
Reference: https://issues.redhat.com/browse/OCPBUGS-54594
=> OCPBUGS-54594: ARM64 nodes to apply a bootloader update at 4.18.11 or later

build-suggestions/4.19.yaml
Machine config cluster operator's status condition message has been updated with a clearer explanation and a reference to the doc to switch the cgroupMode in OCP
Every cluster has to pass through this change before upgrading to 4.19 to make sure the cluster is migrated to cgroupv2 Ref: https://github.com/openshift/machine-config-operator/pull/4993
=> Bump 4.18 minor minimum version to 4.18.11

blocked-edges/4.18.10-MetallbBgpBfdFrrRpm.yaml, blocked-edges/4.18.11-MetallbBgpBfdFrrRpm.yaml
Clusters with `metallb-operator` CSV installed should be warned about updating to 4.18.10 and 4.18.11, because these OCP payloads ship a `metallb` image (which serves as the OLM operators operand) with a FRR RPM that causes issues for clusters using BFD and BGP.
I do not have a cluster at hand with metallb installed, but testing CSV presence is an established practice for matching an installed OLM operator, and I have tested the PromQL on ota-stage, just substituted the metallb-operator name for one of the CSVs installed there. I used https://github.com/metallb/metallb-operator/blob/main/bundle/manifests/metallb-operator.clusterserviceversion.yaml#L446C9-L446C25 as a source for what the CSV name is,
```
(
group by (_id, name) (csv_succeeded{_id="", name=~"metallb-operator[.].*"})
or on …
```
=> CNF-17689: Set up `MetallbBgpBfdFrrRpm` for 4.18.{10,11}

blocked-edges/4.18.1-CRIOLayerCompressionPulls.yaml, blocked-edges/4.18.2-CRIOLayerCompressionPulls.yaml, blocked-edges/4.18.3-CRIOLayerCompressionPulls.yaml, blocked-edges/4.18.4-CRIOLayerCompressionPulls.yaml, blocked-edges/4.18.5-CRIOLayerCompressionPulls.yaml, blocked-edges/4.18.6-CRIOLayerCompressionPulls.yaml
Fixed versions are already available, we are just steering clusters away from the affected ones.
=> OCPNODE-3074: Declare `CRIOLayerCompressionPulls` for 4.18.1..6

build-suggestions/4.19.yaml
[4.18.13][1] includes [OCPBUGS-55359][2] and [OCPBUGS-53427][3], which we want clusters to be evaluating before they launch updates to 4.19.
[1]: https://multi.ocp.releases.ci.openshift.org/releasestream/4-stable-multi/release/4.18.13
[2]: https://issues.redhat.com/browse/OCPBUGS-55359
[3]: https://issues.redhat.com/browse/OCPBUGS-53427
=> OCPBUGS-55359: build-suggestions/4.19: Raise minor_min to 4.18.13

blocked-edges/4.17.11-MCOContainerRuntimeConfigStaleFinalizer.yaml, blocked-edges/4.17.12-MCOContainerRuntimeConfigStaleFinalizer.yaml, blocked-edges/4.17.13-MCOContainerRuntimeConfigStaleFinalizer.yaml, blocked-edges/4.17.14-MCOContainerRuntimeConfigStaleFinalizer.yaml, blocked-edges/4.17.15-MCOContainerRuntimeConfigStaleFinalizer.yaml, blocked-edges/4.17.16-MCOContainerRuntimeConfigStaleFinalizer.yaml, blocked-edges/4.17.17-MCOContainerRuntimeConfigStaleFinalizer.yaml, blocked-edges/4.17.18-MCOContainerRuntimeConfigStaleFinalizer.yaml, blocked-edges/4.17.19-MCOContainerRuntimeConfigStaleFinalizer.yaml, blocked-edges/4.17.20-MCOContainerRuntimeConfigStaleFinalizer.yaml, blocked-edges/4.17.21-MCOContainerRuntimeConfigStaleFinalizer.yaml, blocked-edges/4.17.22-MCOContainerRuntimeConfigStaleFinalizer.yaml, blocked-edges/4.17.23-MCOContainerRuntimeConfigStaleFinalizer.yaml, blocked-edges/4.17.24-MCOContainerRuntimeConfigStaleFinalizer.yaml
- [OCPBUGS-52188](https://issues.redhat.com/browse/OCPBUGS-52188) is fixed in [4.17.25](https://amd64.ocp.releases.ci.openshift.org/releasestream/4-stable/release/4.17.25)
- PromQL approximating affected clusters to "Clusters with ContainerRuntimeConfig resources" which may be very coarse but should not be a big deal because fixed 4.17 versions are already available.
/hold
PR created but [OCPNODE-3119](https://issues.redhat.com/browse/OCPNODE-3119) still needs final confirmations and description cleanup
=> OCPNODE-3119: Declare `MCOContainerRuntimeConfigStaleFinalizer` for 4.17.11..24

blocked-edges/4.17.11-MCOContainerRuntimeConfigStaleFinalizer.yaml, blocked-edges/4.17.12-MCOContainerRuntimeConfigStaleFinalizer.yaml, blocked-edges/4.17.13-MCOContainerRuntimeConfigStaleFinalizer.yaml, blocked-edges/4.17.14-MCOContainerRuntimeConfigStaleFinalizer.yaml, blocked-edges/4.17.15-MCOContainerRuntimeConfigStaleFinalizer.yaml, blocked-edges/4.17.16-MCOContainerRuntimeConfigStaleFinalizer.yaml, blocked-edges/4.17.17-MCOContainerRuntimeConfigStaleFinalizer.yaml, blocked-edges/4.17.18-MCOContainerRuntimeConfigStaleFinalizer.yaml, blocked-edges/4.17.19-MCOContainerRuntimeConfigStaleFinalizer.yaml, blocked-edges/4.17.20-MCOContainerRuntimeConfigStaleFinalizer.yaml, blocked-edges/4.17.21-MCOContainerRuntimeConfigStaleFinalizer.yaml, blocked-edges/4.17.22-MCOContainerRuntimeConfigStaleFinalizer.yaml, blocked-edges/4.17.23-MCOContainerRuntimeConfigStaleFinalizer.yaml, blocked-edges/4.17.24-MCOContainerRuntimeConfigStaleFinalizer.yaml
Only updates from any 4.16 and 4.17 below 4.17.10 are affected, no need to bother 4.17 clusters that either already or never encountered the bug.
=> OCPNODE-3119: Restrict `from:` on `MCOContainerRuntimeConfigStaleFinalizer`

blocked-edges/4.18.0-rc.10-PreRelease.yaml, blocked-edges/4.19.0-ec.2-LabeledMachineConfigAndContainerRuntimeConfigBlocksMCO.yaml, blocked-edges/4.19.0-ec.3-LabeledMachineConfigAndContainerRuntimeConfigBlocksMCO.yaml
> @ota-monitor: Cincinnati stabilization:
> * FAILED PreRelease affects 4.18.0-rc.10.  Either declare a fix version or extend the risk to 4.18.1.
> * FAILED LabeledMachineConfigAndContainerRuntimeConfigBlocksMCO affects 4.19.0-ec.1 and is not fixed until 4.19.0-ec.4.  Extend the risk to 4.19.0-ec.2.
Unsure why these started to appear now, seems enabled by https://github.com/openshift/cincinnati-graph-data/pull/7239
I am not sure why https://github.com/openshift/cincinnati-graph-data/pull/7020 did not add files for ec2 and ec3 when it knew the fix is in ec4 but there is no harm in filling the blanks.
=> Reconcile stabilization-bot warnings

blocked-edges/4.18.0-KubeletStartFailingFromRestoreconTimeout.yaml, blocked-edges/4.18.1-KubeletStartFailingFromRestoreconTimeout.yaml, blocked-edges/4.18.10-KubeletStartFailingFromRestoreconTimeout.yaml, blocked-edges/4.18.11-KubeletStartFailingFromRestoreconTimeout.yaml, blocked-edges/4.18.12-KubeletStartFailingFromRestoreconTimeout.yaml, blocked-edges/4.18.2-KubeletStartFailingFromRestoreconTimeout.yaml, blocked-edges/4.18.3-KubeletStartFailingFromRestoreconTimeout.yaml, blocked-edges/4.18.4-KubeletStartFailingFromRestoreconTimeout.yaml, blocked-edges/4.18.5-KubeletStartFailingFromRestoreconTimeout.yaml, blocked-edges/4.18.6-KubeletStartFailingFromRestoreconTimeout.yaml, blocked-edges/4.18.7-KubeletStartFailingFromRestoreconTimeout.yaml, blocked-edges/4.18.8-KubeletStartFailingFromRestoreconTimeout.yaml, blocked-edges/4.18.9-KubeletStartFailingFromRestoreconTimeout.yaml
I'm not totally clear if this is the correct way to do this, and I'm not positive we'll go this route, but beginning the process to indicate we may need it.
=> OCPNODE-3245: Declare `KubeletStartFailingFromRestoreconTimeout` for 4.18.0..12

channels/stable-4.14.yaml, channels/stable-4.15.yaml, channels/stable-4.16.yaml
Like a56b5405 (#6584), but for 4.14, because [4.14 left its Maintenance phase and entered its EUS phase on 2025-05-01][1]:
```console
$ curl -s 'https://access.redhat.com/product-life-cycles/api/v1/products?name=Openshift+Container+Platform+4' | jq -r '.data[].versions[] | select(.name == "4.14").phases[] | .date + " " + .name'
2023-10-31T00:00:00.000Z General availability
2024-05-27T00:00:00.000Z Full support
2025-05-01T00:00:00.000Z Maintenance support
2025-10-31T00:00:00.000Z Extended update support
2026-10-31T00:00:00.000Z Extended update support Term 2
N/A Extended life phase
```
The most recent 4.14.z is 4.14.51, and it entered stable and related on 354234b97d (#7200), as expected for a release that went GA and entered fast channels before the Maintenance cutoff in 90aff68115 …
=> OCPBUGS-55193: channels/stable-*: Remove 4.14.z feeders from stable channels

blocked-edges/4.16.38-RHELFailedRebootMissingService.yaml, blocked-edges/4.16.39-RHELFailedRebootMissingService.yaml, blocked-edges/4.16.40-RHELFailedRebootMissingService.yaml, blocked-edges/4.16.41-RHELFailedRebootMissingService.yaml, blocked-edges/4.17.22-RHELFailedRebootMissingService.yaml, blocked-edges/4.17.23-RHELFailedRebootMissingService.yaml, blocked-edges/4.17.24-RHELFailedRebootMissingService.yaml, blocked-edges/4.17.25-RHELFailedRebootMissingService.yaml, blocked-edges/4.17.26-RHELFailedRebootMissingService.yaml, blocked-edges/4.17.27-RHELFailedRebootMissingService.yaml, blocked-edges/4.17.28-RHELFailedRebootMissingService.yaml, blocked-edges/4.17.29-RHELFailedRebootMissingService.yaml, blocked-edges/4.17.30-RHELFailedRebootMissingService.yaml, blocked-edges/4.17.31-RHELFailedRebootMissingService.yaml, blocked-edges/4.18.10-RHELFailedRebootMissingService.yaml, blocked-edges/4.18.11-RHELFailedRebootMissingService.yaml, blocked-edges/4.18.12-RHELFailedRebootMissingService.yaml, blocked-edges/4.18.13-RHELFailedRebootMissingService.yaml, blocked-edges/4.18.14-RHELFailedRebootMissingService.yaml, blocked-edges/4.18.15-RHELFailedRebootMissingService.yaml, blocked-edges/4.18.6-RHELFailedRebootMissingService.yaml, blocked-edges/4.18.7-RHELFailedRebootMissingService.yaml, blocked-edges/4.18.8-RHELFailedRebootMissingService.yaml, blocked-edges/4.18.9-RHELFailedRebootMissingService.yaml
The related impact statement: https://issues.redhat.com/browse/MCO-1702.
---
Created `blocked-edges/4.16.38-RHELFailedRebootMissingService.yaml` manually
Run:
```sh
$ curl -s 'https://api.openshift.com/api/upgrades_info/graph?channel=candidate-4.16&arch=amd64' | jq -r '.nodes[] | .version' | grep '^4[.]16[.]\(3[9-9]\|[4-9][0-9]\)$' | while read VERSION; do sed "s/4.16.38/${VERSION}/" blocked-edges/4.16.38-RHELFailedRebootMissingService.yaml > "blocked-edges/${VERSION}-RHELFailedRebootMissingService.yaml"; done
```
---
Created `blocked-edges/4.17.22-RHELFailedRebootMissingService.yaml` manually
Run:
```sh
$ curl -s 'https://api.openshift.com/api/upgrades_info/graph?channel=candidate-4.17&arch=amd64' | jq -r '.nodes[] | .version' | grep '^4[.]17[.]\(2[3-9]\|[3-9][0-9]\)$' | while read …
```
=> MCO-1702: Declare RHELFailedRebootMissingService Risk

graph-data.rs/Cargo.lock, graph-data.rs/Cargo.toml
We have to bump zeroize which blocks reqwest (similar to https://github.com/openshift/cincinnati/pull/1009).
https://github.com/openshift/cincinnati-graph-data/pull/6016#issuecomment-2825806965 is closed after rotting.
But its commit faad79a7c560818fd7f4e89e6e98e1596ab82b01 is picked into this PR.
=> [OTA-1464]Bump cincinnati to 88bb8cb7

blocked-edges/4.15.51-NonZonalAzureMachineSetScaling.yaml
[4.15.52][1] contains [OCPBUGS-56657][2].
[1]: https://multi.ocp.releases.ci.openshift.org/releasestream/4-stable-multi/release/4.15.52
[2]: https://issues.redhat.com/browse/OCPBUGS-56657
=> blocked-edges/4.15.51-NonZonalAzureMachineSetScaling: Fixed in 4.15.52

internal-channels/candidate.yaml
We don't want this self-referential update in public channels:
```console
$ oc adm release info quay.io/openshift-release-dev/ocp-release:4.20.0-ec.1-x86_64 -o json | jq -c '{digest, previous: .metadata.previous}'
{"digest":"sha256:b7acb7ffbaf23be6fd4d06ce10e68ef1209c131211f50af67316d718145410a9","previous":["4.19.0-rc.4","4.20.0-ec.1"]}
```
=> internal-channels/candidate: Tombstone 4.20.0-ec.1

hack/exposure-length.sh
Like https://github.com/openshift/cincinnati-graph-data/pull/7456, this pull handles the last script in the `hack` folder with `sed` cmd without the env. var.
=> Make exposure-length.sh mac-friendly

blocked-edges/4.18.1-OVNEgressIPFailure.yaml, blocked-edges/4.18.10-OVNEgressIPFailure.yaml, blocked-edges/4.18.11-OVNEgressIPFailure.yaml, blocked-edges/4.18.12-OVNEgressIPFailure.yaml, blocked-edges/4.18.13-OVNEgressIPFailure.yaml, blocked-edges/4.18.14-OVNEgressIPFailure.yaml, blocked-edges/4.18.15-OVNEgressIPFailure.yaml, blocked-edges/4.18.16-OVNEgressIPFailure.yaml, blocked-edges/4.18.17-OVNEgressIPFailure.yaml, blocked-edges/4.18.2-OVNEgressIPFailure.yaml, blocked-edges/4.18.3-OVNEgressIPFailure.yaml, blocked-edges/4.18.4-OVNEgressIPFailure.yaml, blocked-edges/4.18.5-OVNEgressIPFailure.yaml, blocked-edges/4.18.6-OVNEgressIPFailure.yaml, blocked-edges/4.18.7-OVNEgressIPFailure.yaml, blocked-edges/4.18.8-OVNEgressIPFailure.yaml, blocked-edges/4.18.9-OVNEgressIPFailure.yaml
```console
$ curl -s 'https://api.openshift.com/api/upgrades_info/graph?channel=candidate-4.18&arch=amd64' | jq -r '.nodes[] | .version' | grep '^4[.]18' | sort -V | grep -v '^4.18.1$' | grep -v '^4.18.0-ec' | grep -v '^4.18.0-rc' | while read VERSION; do sed "s/4.18.1/${VERSION}/" blocked-edges/4.18.1-OVNEgressIPFailure.yaml > "blocked-edges/${VERSION}-OVNEgressIPFailure.yaml"; done
```
/hold
Wait a bit for [CORENET-6114](https://issues.redhat.com//browse/CORENET-6114) to be polished up
=> CORENET-6114: Set up OVNEgressIPFailure to block paths to 4.18

blocked-edges/4.19.1-OldBootImagesComposeFSvsGrubProbe.yaml
Follow up https://redhat-internal.slack.com/archives/C02MX20TV24/p1750433340854259
https://issues.redhat.com/browse/OCPBUGS-52485 is still not resolved at the moment (June 20, 2025).
```
$ cp blocked-edges/4.19.0-OldBootImagesComposeFSvsGrubProbe.yaml blocked-edges/4.19.1-OldBootImagesComposeFSvsGrubProbe.yaml
```
Then replaced `to` in the new file.
=> Extend OldBootImagesComposeFSvsGrubProbe to 4.19.1

blocked-edges/4.18.18-OVNEgressIPFailure.yaml
Follow up https://redhat-internal.slack.com/archives/C02MX20TV24/p1750433340854259
https://issues.redhat.com/browse/OCPBUGS-57179 is still unresolved at the moment (June 20 2025).
```console
$ cp blocked-edges/4.18.17-OVNEgressIPFailure.yaml blocked-edges/4.18.18-OVNEgressIPFailure.yaml
```
Then replaced `to` in the new file.
=> Extend OVNEgressIPFailure to 4.18.18

blocked-edges/4.19.0-VSphereStorageMountIssues.yaml, blocked-edges/4.19.0-ec.0-VSphereStorageMountIssues.yaml, blocked-edges/4.19.0-ec.1-VSphereStorageMountIssues.yaml, blocked-edges/4.19.0-ec.2-VSphereStorageMountIssues.yaml, blocked-edges/4.19.0-ec.3-VSphereStorageMountIssues.yaml, blocked-edges/4.19.0-ec.4-VSphereStorageMountIssues.yaml, blocked-edges/4.19.0-ec.5-VSphereStorageMountIssues.yaml, blocked-edges/4.19.0-rc.0-VSphereStorageMountIssues.yaml, blocked-edges/4.19.0-rc.1-VSphereStorageMountIssues.yaml, blocked-edges/4.19.0-rc.2-VSphereStorageMountIssues.yaml, blocked-edges/4.19.0-rc.3-VSphereStorageMountIssues.yaml, blocked-edges/4.19.0-rc.4-VSphereStorageMountIssues.yaml, blocked-edges/4.19.0-rc.5-VSphereStorageMountIssues.yaml, blocked-edges/4.19.1-VSphereStorageMountIssues.yaml
Clusters running on the vSphere platform with the vSphere CSI driver mounting VSAN Files volumes whenever VSAN is not fully patched and up to date.
Nodes cannot mount NFS volumes from VSAN files provider.
Blocking all the affected edges
=> block edges from all 4.18 to 4.19 with vsphere provider storage issues

blocked-edges/4.18.19-OVNEgressIPFailure.yaml
https://issues.redhat.com/browse/OCPBUGS-57179 is not fixed
=> Extend OVNEgressIPFailure to 4.18.19

build-suggestions/4.19.yaml
Using Alertmanager apiVersion v1 in openshift-monitoring/cluster-monitoring-config or openshift-user-workload-monitoring/user-workload-monitoring-config will cause (InvalidConfigXXX) as OCP 4.19 is using Prometheus V3 and Alertmanager apiVersions v1 is not supported in it. With the change included in 4.18.19, it will set CMO upgradable=false if apiVersion: v1 is detected in the config maps. Hence making it as minor_min version before upgrading to 4.19
cc @machine424
=> MON-4270: Set 4.18.19 as the minor_min for 4.19 upgrade

blocked-edges/4.18.20-OVNEgressIPFailure.yaml
OCPBUGS-57179 targeting 4.20 is still in POST
=> `OVNEgressIPFailure`: Extend to 4.18.20

blocked-edges/4.19.0-IPsecLargeClusterConnectivity.yaml, blocked-edges/4.19.1-IPsecLargeClusterConnectivity.yaml, blocked-edges/4.19.2-IPsecLargeClusterConnectivity.yaml, blocked-edges/4.19.3-IPsecLargeClusterConnectivity.yaml, blocked-edges/4.19.4-IPsecLargeClusterConnectivity.yaml
We have set up similar known issues in the past. PromQL was adapted from an earlier `IPsecLargeClusterConnectivity` issue and changed to match on node count higher than 120.
=> CORENET-6196: Issue `IPsecLargeClusterConnectivity` on 4.18 -> 4.19

blocked-edges/4.19.5-IPsecLargeClusterConnectivity.yaml
[OCPBUGS-55453][1] is still `New`.
[1]: https://issues.redhat.com/browse/OCPBUGS-55453
=> CORENET-6196: blocked-edges/4.19.5-IPsecLargeClusterConnectivity: Extend risk

blocked-edges/4.19.0-AROMissingInternalLBSAN.yaml, blocked-edges/4.19.1-AROMissingInternalLBSAN.yaml, blocked-edges/4.19.2-AROMissingInternalLBSAN.yaml, blocked-edges/4.19.3-AROMissingInternalLBSAN.yaml, blocked-edges/4.19.4-AROMissingInternalLBSAN.yaml, blocked-edges/4.19.5-AROMissingInternalLBSAN.yaml
https://issues.redhat.com/browse/ARO-20086
https://access.redhat.com/solutions/7128495
Blocks all upgrades to 4.19 for ARO clusters. New Machines in 4.19 ARO clusters fail to come up due to a missing Internal LB IP missing in the SAN of the cert issued by MCO.
=> Block edges to 4.19 for ARO clusters 

blocked-edges/4.18.21-OVNEgressIPFailure.yaml
The 4.18 https://issues.redhat.com/browse/OCPBUGS-59531 is still in POST
=> `OVNEgressIPFailure`: Extend to 4.18.21

blocked-edges/4.19.0-VSphereStorageMountIssues.yaml, blocked-edges/4.19.0-ec.0-VSphereStorageMountIssues.yaml, blocked-edges/4.19.0-rc.4-VSphereStorageMountIssues.yaml, blocked-edges/4.19.0-rc.5-VSphereStorageMountIssues.yaml, blocked-edges/4.19.1-VSphereStorageMountIssues.yaml, blocked-edges/4.19.2-VSphereStorageMountIssues.yaml
It uses both `vSphere` and `VSphere` in https://github.com/openshift/cincinnati-graph-data/pull/7380
Other places with `cluster_infrastructure_provider` seems using `VSphere` all the time.
=> VSphereStorageMountIssues: vSphere -> VSphere in promql

blocked-edges/4.15.0-rc.0-EarlyAPICertRotation.yaml
Feels like it is missed in https://github.com/openshift/cincinnati-graph-data/pull/4864/files#diff-3f70c11efe92a235472ac9ba86a5642685ff0ed6c255fa4a6f286d0c90953c43R5
=> EarlyAPICertRotation: : unify the message

blocked-edges/4.18.21-OVNEgressIPFailure.yaml
[4.18.22][1] contains [OCPBUGS-59531][2].
[1]: https://amd64.ocp.releases.ci.openshift.org/releasestream/4-stable/release/4.18.22
[2]: https://issues.redhat.com/browse/OCPBUGS-59531
=> CORENET-6114: blocked-edges/4.18.21-OVNEgressIPFailure: Fixed in 4.18.22

blocked-edges/4.18.1-WhereaboutsControllerCreateContainerError.yaml, blocked-edges/4.18.10-WhereaboutsControllerCreateContainerError.yaml, blocked-edges/4.18.11-WhereaboutsControllerCreateContainerError.yaml, blocked-edges/4.18.12-WhereaboutsControllerCreateContainerError.yaml, blocked-edges/4.18.13-WhereaboutsControllerCreateContainerError.yaml, blocked-edges/4.18.14-WhereaboutsControllerCreateContainerError.yaml, blocked-edges/4.18.15-WhereaboutsControllerCreateContainerError.yaml, blocked-edges/4.18.16-WhereaboutsControllerCreateContainerError.yaml, blocked-edges/4.18.17-WhereaboutsControllerCreateContainerError.yaml, blocked-edges/4.18.18-WhereaboutsControllerCreateContainerError.yaml, blocked-edges/4.18.19-WhereaboutsControllerCreateContainerError.yaml, blocked-edges/4.18.2-WhereaboutsControllerCreateContainerError.yaml, blocked-edges/4.18.20-WhereaboutsControllerCreateContainerError.yaml, blocked-edges/4.18.21-WhereaboutsControllerCreateContainerError.yaml, blocked-edges/4.18.3-WhereaboutsControllerCreateContainerError.yaml, blocked-edges/4.18.4-WhereaboutsControllerCreateContainerError.yaml, blocked-edges/4.18.5-WhereaboutsControllerCreateContainerError.yaml, blocked-edges/4.18.6-WhereaboutsControllerCreateContainerError.yaml, blocked-edges/4.18.7-WhereaboutsControllerCreateContainerError.yaml, blocked-edges/4.18.8-WhereaboutsControllerCreateContainerError.yaml, blocked-edges/4.18.9-WhereaboutsControllerCreateContainerError.yaml
Create `blocked-edges/4.18.1-WhereaboutsControllerCreateContainerError.yaml` (`4.18.0` is [not in the channel](https://github.com/openshift/cincinnati-graph-data/blob/ed47d4126c1c63dae5f42dcf7d9e0d39658699d0/channels/candidate-4.18.yaml#L114-L131)) and generate the rest by:
```
$ curl -s 'https://api.openshift.com/api/upgrades_info/graph?channel=candidate-4.18&arch=amd64' | jq -r '.nodes[] | .version' | grep '^4[.]18' | sort -V | grep -v 0-ec | grep -v 0-rc | tail -n +2 | sed '/4.18.22/,$d' | while read VERSION; do gsed "s/4.18.1/${VERSION}/" blocked-edges/4.18.1-WhereaboutsControllerCreateContainerError.yaml > "blocked-edges/${VERSION}-WhereaboutsControllerCreateContainerError.yaml"; done
```
Add `fixedIn: 4.18.22` into `blocked-edges/4.18.21-WhereaboutsControllerCreateContainerError.yaml …
=> CORENET-6189: Set up WhereaboutsControllerCreateContainerError to block paths to 4.18

blocked-edges/4.19.0-InvalidArchitectureValueOfMachinesetsAnnotation.yaml, blocked-edges/4.19.1-InvalidArchitectureValueOfMachinesetsAnnotation.yaml, blocked-edges/4.19.2-InvalidArchitectureValueOfMachinesetsAnnotation.yaml, blocked-edges/4.19.3-InvalidArchitectureValueOfMachinesetsAnnotation.yaml, blocked-edges/4.19.4-InvalidArchitectureValueOfMachinesetsAnnotation.yaml, blocked-edges/4.19.5-InvalidArchitectureValueOfMachinesetsAnnotation.yaml, blocked-edges/4.19.6-InvalidArchitectureValueOfMachinesetsAnnotation.yaml, blocked-edges/4.19.7-InvalidArchitectureValueOfMachinesetsAnnotation.yaml, blocked-edges/4.19.8-InvalidArchitectureValueOfMachinesetsAnnotation.yaml
Create `blocked-edges/4.19.0-InvalidArchitectureValueOfMachinesetsAnnotation.yaml` and generate the rest by:
```
$ curl -s 'https://api.openshift.com/api/upgrades_info/graph?channel=candidate-4.19&arch=amd64' | jq -r '.nodes[] | .version' | grep '^4[.]19' | sort -V | grep -v 0-ec | grep -v 0-rc | tail -n +2 | sed '/4.19.9/,$d' | while read VERSION; do gsed "s/4.19.0/${VERSION}/" blocked-edges/4.19.0-InvalidArchitectureValueOfMachinesetsAnnotation.yaml > "blocked-edges/${VERSION}-InvalidArchitectureValueOfMachinesetsAnnotation.yaml"; done
```
Add `fixedIn: 4.19.9` into `blocked-edges/4.19.8-InvalidArchitectureValueOfMachinesetsAnnotation.yaml`
I think we may use PromQL to narrow down the damage range but with the fix shipped in `4.19.9` which landed in …
=> MCO-1834: Set up InvalidArchitectureValueOfMachinesetsAnnotation to block paths to 4.19

blocked-edges/4.19.9-NoCloudConfConfigMap.yaml
The fixed of OCPBUGS-60950 is shipped in [4.19.10](https://amd64.ocp.releases.ci.openshift.org/releasestream/4-stable/release/4.19.10).
=> NoCloudConfConfigMap is fixed in 4.19.10

build-suggestions/README.md
- Add a link to primary metadata
- Add the semantics about files in `build-suggestions`. It is taken from https://github.com/openshift/cincinnati-graph-data/pull/425
=> Add more docs about build suggestions

blocked-edges/4.19.13-HyperShiftProxyScheme.yaml
The backport for 4.19 is in POST [[1]].
[1]: https://issues.redhat.com/browse/OCPBUGS-61567
=> CNTRLPLANE-1407: blocked-edges/4.19.13-HyperShiftProxyScheme: Extend to 4.19.13

blocked-edges/4.19.13-IPsecLargeClusterConnectivity.yaml
The 4.21 bug is still in NEW [[1]].
[1]: https://issues.redhat.com/browse/OCPBUGS-55453
=> CORENET-6196: blocked-edges/4.19.13-IPsecLargeClusterConnectivity: Not fixed yet

blocked-edges/4.16.46-NMStateServiceFailure.yaml, blocked-edges/4.16.47-NMStateServiceFailure.yaml, blocked-edges/4.16.48-NMStateServiceFailure.yaml, blocked-edges/4.16.49-NMStateServiceFailure.yaml, blocked-edges/4.17.38-NMStateServiceFailure.yaml, blocked-edges/4.17.39-NMStateServiceFailure.yaml, blocked-edges/4.17.40-NMStateServiceFailure.yaml, blocked-edges/4.18.22-NMStateServiceFailure.yaml, blocked-edges/4.18.23-NMStateServiceFailure.yaml, blocked-edges/4.18.24-NMStateServiceFailure.yaml, blocked-edges/4.19.10-NMStateServiceFailure.yaml, blocked-edges/4.19.11-NMStateServiceFailure.yaml, blocked-edges/4.19.12-NMStateServiceFailure.yaml, blocked-edges/4.19.13-NMStateServiceFailure.yaml, blocked-edges/4.19.8-NMStateServiceFailure.yaml, blocked-edges/4.19.9-NMStateServiceFailure.yaml
Baremetal clusters that use NMState to create br-ex instead of configure-ovs. That means it is also specific to clusters running OVNKubernetes as the CNI.
- **[CORENET-6419](https://issues.redhat.com//browse/CORENET-6419): `NMStateServiceFailure`: Declare on 4.19.(8-13)**
- **[CORENET-6419](https://issues.redhat.com//browse/CORENET-6419): `NMStateServiceFailure`: Declare fixed in 4.19.14**
- **[CORENET-6419](https://issues.redhat.com//browse/CORENET-6419): `NMStateServiceFailure`: Declare on 4.18.(22-24)**
- **[CORENET-6419](https://issues.redhat.com//browse/CORENET-6419): `NMStateServiceFailure`: Declare fixed in 4.18.25**
- **[CORENET-6419](https://issues.redhat.com//browse/CORENET-6419): `NMStateServiceFailure`: Declare on 4.17.(38-40)**
- …
=> CORENET-6419: `NMStateServiceFailure`: Declare on 4.16 - 4.19

blocked-edges/4.19.12-MachineConfigNodesV1AlphaControlPlaneLabels.yaml, blocked-edges/4.19.13-MachineConfigNodesV1AlphaControlPlaneLabels.yaml
[Fixed in 4.19.14][1].  For the PromQL, the logic is:
* If you have any modern-role `control-plane` Nodes, you are not exposed (0), otherwise...
* ... if you have legacy-role `master` Nodes, you are exposed (1), otherwise...
* ... if the `kube_node_role` metric is working at all, you are not exposed (0), otherwise...
* ... we don't know if you are exposed or not (no response metric).
I'm preserving the `role` label in the output results to make it easier to understand how the PromQL functions if folks run it by hand.
[1]: https://issues.redhat.com/browse/OCPBUGS-62114?focusedId=28155286&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-28155286
=> MCO-1890: blocked-edges/4.19.1[23]-MachineConfigNodesV1AlphaControlPlaneLabels: Declare new risk

blocked-edges/4.17.40-NMStateServiceFailure.yaml
The 4.17.z bug is Verified [[1]].
4.17.41 changes list `OCPBUGS-61859: Override NMState service definition #5289` [[2]].
[1]: https://issues.redhat.com/browse/OCPBUGS-61859
[2]: https://amd64.ocp.releases.ci.openshift.org/releasestream/4-stable/release/4.17.41
=> CORENET-6419: `NMStateServiceFailure`: Declare fixed in 4.17.41
